DirectProgramming/DPC++/CombinationalLogic/mandelbrot/CMakeLists.txt
DirectProgramming/DPC++/CombinationalLogic/mandelbrot/License.txt
DirectProgramming/DPC++/CombinationalLogic/mandelbrot/README.md
DirectProgramming/DPC++/CombinationalLogic/mandelbrot/mandelbrot.sln
DirectProgramming/DPC++/CombinationalLogic/mandelbrot/mandelbrot.vcxproj
DirectProgramming/DPC++/CombinationalLogic/mandelbrot/mandelbrot.vcxproj.filters
DirectProgramming/DPC++/CombinationalLogic/mandelbrot/mandelbrot.vcxproj.user
DirectProgramming/DPC++/CombinationalLogic/mandelbrot/sample.json
DirectProgramming/DPC++/CombinationalLogic/mandelbrot/src/CMakeLists.txt
DirectProgramming/DPC++/CombinationalLogic/mandelbrot/src/main.cpp
DirectProgramming/DPC++/CombinationalLogic/mandelbrot/src/mandel.hpp

Signed-off-by: vmadanan <varsha.madananth@intel.com>

Adding mandelbrot sample to the repository

---

Libraries/oneDPL/gamma-correction/CMakeLists.txt
Libraries/oneDPL/gamma-correction/License.txt
Libraries/oneDPL/gamma-correction/README.md
Libraries/oneDPL/gamma-correction/gamma-correction.sln
Libraries/oneDPL/gamma-correction/gamma-correction.vcxproj
Libraries/oneDPL/gamma-correction/gamma-correction.vcxproj.filters
Libraries/oneDPL/gamma-correction/gamma-correction.vcxproj.user
Libraries/oneDPL/gamma-correction/sample.json
Libraries/oneDPL/gamma-correction/src/CMakeLists.txt
Libraries/oneDPL/gamma-correction/src/main.cpp
Libraries/oneDPL/gamma-correction/src/utils.hpp
Libraries/oneDPL/gamma-correction/src/utils/Img.hpp
Libraries/oneDPL/gamma-correction/src/utils/ImgAlgorithm.hpp
Libraries/oneDPL/gamma-correction/src/utils/ImgFormat.hpp
Libraries/oneDPL/gamma-correction/src/utils/ImgPixel.hpp
Libraries/oneDPL/gamma-correction/src/utils/Other.hpp
Libraries/oneDPL/stable_sort_by_key/CMakeLists.txt
Libraries/oneDPL/stable_sort_by_key/License.txt
Libraries/oneDPL/stable_sort_by_key/README.md
Libraries/oneDPL/stable_sort_by_key/sample.json
Libraries/oneDPL/stable_sort_by_key/src/CMakeLists.txt
Libraries/oneDPL/stable_sort_by_key/src/main.cpp

Added oneDPL samples: gamma-correction, stable_sort_by_key.
Signed-off-by: Fedorov, Andrey <andrey.fedorov@intel.com>

Added oneDPL samples: gamma-correction, stable_sort_by_key

---

DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/CMakeLists.txt
DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/License.txt
DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/README.md
DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/iso2dfd.sln
DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/iso2dfd.vcxproj
DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/iso2dfd.vcxproj.filters
DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/iso2dfd.vcxproj.user
DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/sample.json
DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/src/iso2dfd.cpp

Signed-off-by: avillarr <alberto.villarreal@intel.com>

Initial Commit to Open Source Repo

---

clang-format.sh

The script that checks if the source files match with google clang-format guidelines.

Add clang-format check

---

Tools/IoTConnectionTools/hello-iot-world/CMakeLists.txt
Tools/IoTConnectionTools/hello-iot-world/README.md
Tools/IoTConnectionTools/hello-iot-world/cpp/hello-iot-world.cpp
Tools/IoTConnectionTools/hello-iot-world/sample.json

Signed-off-by: Mihai Tudor Panu <mihai.tudor.panu@intel.com>
Compiler name changed throughout in text and code files.
Fixes # 1299

hello-iot-world: update C++ compiler name throughout

---

Tools/SystemDebug/docs/Windbg.rst

Signed-off-by: Marta Navarro <marta.navarro@intel.com>

system_debug: formatting of windbg.rst

---

Libraries/oneDNN/tutorials/profiling/profile_utils.py
Libraries/oneDNN/tutorials/tutorial_analyze_isa_with_dispatcher_control.ipynb
Libraries/oneDNN/tutorials/tutorial_getting_started.ipynb
Libraries/oneDNN/tutorials/tutorial_simple_model.ipynb
Libraries/oneDNN/tutorials/tutorial_verbose_jitdump.ipynb

add error handling if users assign wrong oneapi path

---

Libraries/oneDNN/dpcpp_interoperability/sample.json

remove windows support for interops

---

Tools/IoTConnectionTools/hello-iot-world/README.md

Clarify what the code sample actually outputs in the brief description/what it is section.
Updates text in readme.md only.
Fixes #1288

readme.md: update short description

---

Frameworks/PyTorch/Getting-Started-Samples/PyTorch_HelloWorld/README.md

source activate pytorch ==> conda activate pytorch

fixed source command with conda command

---

Frameworks/TensorFlow/Intel-Model-Zoo-Samples/.ipynb_checkpoints/ResNet50_Inference-checkpoint.ipynb
Frameworks/TensorFlow/Intel-Model-Zoo-Samples/README.md
Frameworks/TensorFlow/Intel-Model-Zoo-Samples/ResNet50_Inference.ipynb
Frameworks/TensorFlow/Intel-Model-Zoo-Samples/sample.json

Creating Intel Model Zoo sample example

Add Intel Model Zoo Sample

---

DirectProgramming/DPC++/GraphTraversal/hidden-markov-models/src/hidden-markov-models.cpp

Host memory release issue fixed.
Additionally the description of the algorithm corrected.
ONSAM-1328
https://jira.devtools.intel.com/browse/ONSAM-1328

Host memory release fixed + User info corrections

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzip.cpp
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzipkernel.cpp

Minor fixes to enable GZIP compile against beta10

Minor fixes to enable GZIP compile against beta10

---

Frameworks/PyTorch/Getting-Started-Samples/PyTorch_HelloWorld/README.md
Frameworks/PyTorch/Intel-Extention-for-PyTorch-Getting-Started/README.md
Frameworks/PyTorch/torch-ccl-Getting-Started/README.md

Added getting started sample codes for IPEX and torch-ccl

---

Frameworks/README.md
Frameworks/iLiT/iLiT-Sample-for-Tensorflow/License.txt
Frameworks/iLiT/iLiT-Sample-for-Tensorflow/README.md
Frameworks/iLiT/iLiT-Sample-for-Tensorflow/alexnet.py
Frameworks/iLiT/iLiT-Sample-for-Tensorflow/alexnet.yaml
Frameworks/iLiT/iLiT-Sample-for-Tensorflow/ilit_quantize_model.py
Frameworks/iLiT/iLiT-Sample-for-Tensorflow/ilit_sample_tensorflow.ipynb
Frameworks/iLiT/iLiT-Sample-for-Tensorflow/mnist_dataset.py
Frameworks/iLiT/iLiT-Sample-for-Tensorflow/run_jupyter.sh
Frameworks/iLiT/iLiT-Sample-for-Tensorflow/sample.json

Add iLiT sampe for Tensorflow

---

Tools/ApplicationDebugger/array-transform/License.txt

Update the license file with line breaks.

ApplicationDebugger/array-transform: put line breaks in the license file

---

Tools/ApplicationDebugger/array-transform/CMakeLists.txt
Tools/ApplicationDebugger/array-transform/README.md
Tools/ApplicationDebugger/array-transform/sample.json

Add AoT compilation options to CMake. Also includes test configurations.

ApplicationDebugger/array-transform: add AoT compilation options

---

Libraries/oneMKL/matrix_mul_mkl/GNUmakefile
Libraries/oneMKL/matrix_mul_mkl/License.txt
Libraries/oneMKL/matrix_mul_mkl/README.md
Libraries/oneMKL/matrix_mul_mkl/makefile
Libraries/oneMKL/matrix_mul_mkl/matrix_mul_mkl.cpp
Libraries/oneMKL/matrix_mul_mkl/sample.json

This PR migrates the matrix_mul_mkl sample to the new repo, with a number of code updates/cleanups.

Migrate and update matrix_mul_mkl sample

---

AI-and-Analytics/Features-and-Functionality/IntelPyTorch_Extensions_AutoMixedPrecision/README.md
AI-and-Analytics/Features-and-Functionality/IntelPyTorch_TorchCCL_Multinode_Training/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPyTorch_GettingStarted/License.txt
AI-and-Analytics/Getting-Started-Samples/IntelPyTorch_GettingStarted/PyTorch_Hello_World.py
AI-and-Analytics/Getting-Started-Samples/IntelPyTorch_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPyTorch_GettingStarted/sample.json

Changed folder structure

---

Tools/Migration/folder-options-dpct/LICENSE.txt
Tools/Migration/folder-options-dpct/Makefile
Tools/Migration/folder-options-dpct/README.md
Tools/Migration/folder-options-dpct/foo/bar/util.cu
Tools/Migration/folder-options-dpct/foo/bar/util.h
Tools/Migration/folder-options-dpct/foo/main.cu
Tools/Migration/folder-options-dpct/sample.json
Tools/Migration/rodinia-nw-dpct/LICENSE.txt
Tools/Migration/rodinia-nw-dpct/Makefile
Tools/Migration/rodinia-nw-dpct/README.md
Tools/Migration/rodinia-nw-dpct/needleman-wunsch.sln
Tools/Migration/rodinia-nw-dpct/needleman-wunsch.vcxproj
Tools/Migration/rodinia-nw-dpct/needleman-wunsch.vcxproj.filters
Tools/Migration/rodinia-nw-dpct/needleman-wunsch.vcxproj.user
Tools/Migration/rodinia-nw-dpct/sample.json
Tools/Migration/rodinia-nw-dpct/src/needle.cu
Tools/Migration/rodinia-nw-dpct/src/needle.h
Tools/Migration/rodinia-nw-dpct/src/needle_kernel.cu
Tools/Migration/vector-add-dpct/LICENSE.txt
Tools/Migration/vector-add-dpct/Makefile
Tools/Migration/vector-add-dpct/README.md
Tools/Migration/vector-add-dpct/sample.json
Tools/Migration/vector-add-dpct/src/vector_add.cu
Tools/Migration/vector-add-dpct/vector-add.sln
Tools/Migration/vector-add-dpct/vector-add.vcxproj
Tools/Migration/vector-add-dpct/vector-add.vcxproj.filters
Tools/Migration/vector-add-dpct/vector-add.vcxproj.user

Signed-off-by: xmnboy <xmnboy@yahoo.com>
Three samples being added to demonstrate the use of the dpct migration tool. These samples have been approved and developed in conjunction with @tomlenth, Yury P. and @srdontha.
These three samples are going into a new folder named `Migration` inside the existing `Tools` folder. 
There is no CI section, yet, in the `sample.json` because the CI system will need to be modified in order to perform automated testing on these samples. 

Initial commit of dpct migration samples.

---

Libraries/oneTBB/tbb-async-sycl/src/tbb-async-sycl.cpp
Libraries/oneTBB/tbb-task-sycl/src/tbb-task-sycl.cpp

Remove dead code from TBB samples according to coding guideline updates.

---

DirectProgramming/DPC++/StructuredGrids/1d_HeatTransfer/README.md

Formatting fixes for superscript and code examples

Fix formatting of README for 1dheat

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/README.md
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt

Update gzip, change seed and remove USM flag.

GZIP update seed and remove USM flag

---

DirectProgramming/DPC++/ProjectTemplates/cmake-fpga/src/main.cpp
DirectProgramming/DPC++/ProjectTemplates/makefile-fpga/src/main.cpp

Updated include path per request from Swapna Dontharaju and Paul F.  Refer to DEV1A-1215.
Did not test.

DEV1A-1215: fix include paths

---

DirectProgramming/DPC++/StructuredGrids/1d_HeatTransfer/src/1d_HeatTransfer.cpp

clang-format changes

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzip_ll.cpp
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzipkernel_ll.cpp

- changed some stdout text to be friendly with regtests
- Changed references to intelfpga:: (replaced with intel::)
- Ran regtests

Minor gzip changes

---

Libraries/oneDNN/tutorials/tutorial_analyze_isa_with_dispatcher_control.ipynb
Libraries/oneDNN/tutorials/tutorial_getting_started.ipynb
Libraries/oneDNN/tutorials/tutorial_simple_model.ipynb

beta10 patch for oneDNN path name and file name changes

---

Libraries/oneVPL/dpcpp-blur/README.md
Libraries/oneVPL/dpcpp-blur/sample.json
Libraries/oneVPL/dpcpp-blur/src/dpcpp-blur.cpp
Libraries/oneVPL/hello-encode/CMakeLists.txt
Libraries/oneVPL/hello-encode/README.md
Libraries/oneVPL/hello-vpp/CMakeLists.txt
Libraries/oneVPL/hello-vpp/src/hello-vpp.cpp

Fix oneVPL sample warnings and build instructions

---

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/shannonization/shannonization_a10.vcxproj

Small change to VCXPROJ for the PACA10 version of this tutorial

Small vcxproj change to shannonization tutorial

---

AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/sample.json

Fixed Modin sample.json install issue. New PR (old one was attempting to push stale commits).

Fixed Modin sample.json

---

Tools/SystemDebug/efi_application/tools/make_boot_media.ps1

system_debug, tools: added exception handling for init errors

---

.gitmodules
Tools/SystemDebug/docs/EFIApplication.rst
Tools/SystemDebug/efi_application/README.md

System_debug: remove submodules due to CI issues

---

Tools/SystemDebugSample/sample.json

system_debug: remove submodule folders and fix json

---

Tools/ApplicationDebugger/array-transform/array-transform.vcxproj

Add "/Od" as the linker option.

ApplicationDebugger/array-transform: pass /Od at link time

---

Tools/SystemDebugSample/sample.json

system-debug: add in languages to samples.json

---

DirectProgramming/DPC++/ParallelPatterns/histogram/src/main.cpp

Update main.cpp to include dpl first.

---

Libraries/oneDPL/gamma-correction/gamma-correction.vcxproj

Add oneDPL headers to include path for VS project

Add oneDPL headers to include path for VS project

---

Libraries/oneTBB/tbb-async-sycl/tbb-async-sycl.vcxproj
Libraries/oneTBB/tbb-resumable-tasks-sycl/tbb-resumable-tasks-sycl.vcxproj
Libraries/oneTBB/tbb-task-sycl/tbb-task-sycl.vcxproj

Update TBB samples to use "tbb12.dll" lib for Gold release.

---

Libraries/oneDNN/dpcpp_interoperability/CMakeLists.txt
Libraries/oneDNN/dpcpp_interoperability/README.md
Libraries/oneDNN/dpcpp_interoperability/sample.json
Libraries/oneDNN/getting_started/CMakeLists.txt
Libraries/oneDNN/getting_started/README.md
Libraries/oneDNN/getting_started/sample.json
Libraries/oneDNN/simple_model/CMakeLists.txt
Libraries/oneDNN/simple_model/README.md
Libraries/oneDNN/simple_model/sample.json

fix cmake error for windows with dpcpp and remove Visaul Stuido IDE support

---

README.md

#Description
Update README for consistency with other oneAPI repos. Minor edits for readability:
- Add Contribute section, linking to CONTRIBUTING
- Add link to LICENSE from License section
- Update issue list to bullets (not numbers) as it is not ordered
- Update issue list for consistency and readability
- Make section title capitalization consistent
Editorial/formatting change for README
NA
NA

Add section to README

---

Libraries/oneDPL/gamma-correction/gamma-correction.vcxproj

Add oneDPL headers to include path for VS project. Follow up on #335 

Follow up on #335

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/README.md
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/gzip_ll.sln
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/gzip_ll.vcxproj
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/gzip_ll.vcxproj.user
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzip.cpp
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzip_ll.cpp
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzipkernel.cpp
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzipkernel_ll.cpp

Prevent A10 from targeting gzip_low_latency, fix windows SLN errors

---

Tools/ApplicationDebugger/array-transform/array-transform.vcxproj.user

ApplicationDebugger/array-transform: define program argument for VS Release mode

---

Libraries/oneDPL/gamma-correction/gamma-correction.vcxproj

replace tbb.dll with tbb12.dll

replace tbb.dll with tbb12.dll for Visual Studio Project

---

AI-and-Analytics/End-to-end-Workloads/Census/sample.json

Fix in sample.json for ModuleNotFoundError: No module named 'modin' 
On Ubuntu machine, created the conda environment using the latest intel-aikit-modin build and ran the census workload using the exact same steps as in the modified sample.json. The code ran successfully.
NOTE: There is still a defect in impi_rt due to which it does not correctly add libfabric to the LD_LIBRARY_PATH. I was told there is a JIRA open to fix this issue
Temporary workaround is to set the path explicitly as:
export …

Fix for ModuleNotFoundError: No module named modin

---

AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/sample.json
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/sample.json
AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/sample.json
AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/sample.json
AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/sample.json

Updated sample dependencies in sample.json for daal4py samples, Modin GS sample, and XGBoost GS sample.
Fixes # (issue) [N/A]

Update sample dependencies in sample.json

---

Libraries/oneDNN/dpcpp_interoperability/sample.json
Libraries/oneDNN/getting_started/sample.json
Libraries/oneDNN/simple_model/sample.json

TEMP FIX for oneapi-cli. EXPECT to ROLL BACK changes later.

---

AI-and-Analytics/End-to-end-Workloads/Census/sample.json

Changed the category to Toolkit/oneAPI AI And Analytics/End-to-end-Workloads/Census and modified the dependencies to "intelpython"
On Ubuntu machine, created the conda environment using the latest intel-aikit-modin build and ran the census workload using the exact same steps as in the modified sample.json. The code ran successfully.
NOTE: There is still a defect in impi_rt due to which it does not correctly add libfabric to the LD_LIBRARY_PATH. I was told there is a JIRA open to fix this issue
Temporary workaround is to set the path explicitly as:
export LD_LIBRARY_PATH=/path/to/envs/aikit-modin-test/lib/libfabric/:$LD_LIBRARY_PATH
Links and Details can be found in the samples WG Teams …

fix to sample.json categories and dependencies

---

AI-and-Analytics/Getting-Started-Samples/iLiT-Sample-for-Tensorflow/sample.json
Libraries/oneDNN/dpcpp_interoperability/sample.json
Libraries/oneDNN/getting_started/sample.json
Libraries/oneDNN/simple_model/sample.json

oneapi-cpi : rename dependency for oneDNN folder name change

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/README.md

Update gzip README.md -- fix typo in executable filenames

---

AI-and-Analytics/End-to-end-Workloads/Census/README.md

Updates made to Readme in accordance with the oneAPI guidance

Updates to README

---

DirectProgramming/DPC++/ParallelPatterns/dpc_reduce/src/main.cpp
DirectProgramming/DPC++/ParallelPatterns/histogram/src/main.cpp

Signed-off-by: timmie.smith <timmie.smith@intel.com>
Commit [2c980ae1](https://github.com/oneapi-src/oneDPL/commit/2c980ae17bd13ea8b18c86395811e1c5baecd7c5) caused the top level numeric header to no longer be included by the oneDPL extension algorithms. The result is that `std::transform_reduce` and `std::reduce` are no longer visible in main of this example as a result. Explicitly adding the numeric header allows the example to compile correctly with oneDPL main.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

Add numeric header to ensure std::transform_reduce and std::reduce are available

---

AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/requirements.txt
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/requirements.txt
AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/requirements.txt
AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/requirements.txt
AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/requirements.txt

Added requirements.txt for sample packages specified in README for 5 AI Kit samples.

Added requirements.txt for sample packages specified in README

---

AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/TensorFlow_HelloWorld.py

Update the TensorFlow MKLDDN VERBOSE in the Helloworld example.

Update the TensorFlow Helloworld

---

AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/README.md

[DOC] Fix typo

---

README.md

Updating top-level README to include two new FPGA tutorials.

---

README.md

correct spelling in README

---

Libraries/oneMKL/fourier_correlation/GNUmakefile
Libraries/oneMKL/fourier_correlation/License.txt
Libraries/oneMKL/fourier_correlation/README.md
Libraries/oneMKL/fourier_correlation/fcorr_1d_buffers.cpp
Libraries/oneMKL/fourier_correlation/fcorr_1d_usm.cpp
Libraries/oneMKL/fourier_correlation/makefile
Libraries/oneMKL/fourier_correlation/sample.json

Signed-off-by: hagabb <henry.a.gabb@intel.com>
This pull request is to add a Fourier correlation sample to the Libraries/oneMKL section of the oneAPI-samples repository. The sample consists of two new codes: one that implements a 1D Fourier correlation using explicit buffering and another that implements it with USM. The latter also includes a maxloc reduction. The sample shows how to compose more complicated mathematical operations using multiple oneMKL kernel functions while paying attention to host-device data placement and data transfer.
Fixes # (issue) N/A
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details …

Adding the Fourier correlation sample

---

Libraries/oneMKL/monte_carlo_european_opt/GNUmakefile
Libraries/oneMKL/monte_carlo_european_opt/makefile
Libraries/oneMKL/monte_carlo_european_opt/mc_european.cpp
Libraries/oneMKL/monte_carlo_european_opt/mc_european_usm.cpp
Libraries/oneMKL/monte_carlo_pi/GNUmakefile
Libraries/oneMKL/monte_carlo_pi/makefile
Libraries/oneMKL/monte_carlo_pi/mc_pi.cpp
Libraries/oneMKL/monte_carlo_pi/mc_pi_device_api.cpp
Libraries/oneMKL/monte_carlo_pi/mc_pi_usm.cpp
Libraries/oneMKL/random_sampling_without_replacement/GNUmakefile
Libraries/oneMKL/random_sampling_without_replacement/makefile
Libraries/oneMKL/random_sampling_without_replacement/sample.json

Rework monte carlo pi sample for oneMKL RNG. Changed sicl::ONEAPI::reduce approach to atomics

[oneMKL][RNG] rework monte carlo pi device sample

---

AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/IntelPython_daal4py_Distributed_Kmeans.ipynb
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/IntelPython_daal4py_Distributed_Kmeans.py
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/README.md
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/IntelPython_daal4py_Distributed_LinearRegression.ipynb
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/IntelPython_daal4py_Distributed_LinearRegression.py
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/README.md
AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/sample.json
AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/README.md

Updated sample readmes for daal4py samples, XGBoost sample, and Modin sample to reflect latest AI Kit branding, removed deleted branch from sample.json for cleanliness

Update READMEs and sample.json

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/README.md

Updating DB design's README
README change only - no testing.

Update to DB design's README to clarify acceleration queries

---

Libraries/oneDNN/tutorials/profiling/README.md
Libraries/oneDNN/tutorials/profiling/profile_utils.py
Libraries/oneDNN/tutorials/tutorial_analyze_isa_with_dispatcher_control.ipynb
Libraries/oneDNN/tutorials/tutorial_getting_started.ipynb
Libraries/oneDNN/tutorials/tutorial_simple_model.ipynb
Libraries/oneDNN/tutorials/tutorial_verbose_jitdump.ipynb

Fixes # index out of range in oneDNN verbose log tutorial 
- [X ] Command Line

fix for index out of range

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/README.md

- content updates according to new release

change contents according to the new release

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/README.md

Minor DB reference design update to README

---

AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/src/vector-add-buffers.cpp
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/src/vector-add-usm.cpp

vector-add sample needs to have longer execution time for correct illustration of Advisor GPU Roofline feature.
Optional parameter of vector size is added, its default value is 10000.
vector-add-buffers version is updated to use std::vector instead of std::array to avoid crash when increasing vector size.
Links and Details can be found in the …

vector-add: ability to change vector size

---

.github/PULL_REQUEST_TEMPLATE.md

Update the pull request template, as discussed with Joe.

Updates to the pull request template

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt

Signed-off-by: Anandh Venkateswaran <anandh.venkateswaran@intel.com>
Updating the seed to achieve an fmax > 300 MHz
N/A
- [ x] Bug fix (non-breaking change which fixes an issue)
Compiled the design to hardware with the new seed to confirm the fmax target of 300 MHz is met.

Update seed used during hardware compiles for FPGA Reference Design gzip_low_latency

---

common/dpc_common.hpp

Intel legal guidelines insist on have copyright on first line. The only exception is when it is impossible.
There also shouldn't be any non-ascii tokens in a text file (the recommendation from legal is to use a lower case '(c)'.
The include guard will work for any compiler (gcc and MSVC alike). This makes the Microsoft-specific pragma redundant.
Also fixed typo and case consistency issue.

Legal, functional and consistency considerations.

---

README.md

Added new FPGA samples that were added for 2021.3.  Also sorted FPGA samples into alphabetical order within each grouping.

Updates to the toplevel README file to add new FPGA samples.

---

AI-and-Analytics/End-to-end-Workloads/README.md
AI-and-Analytics/Features-and-Functionality/README.md
AI-and-Analytics/Getting-Started-Samples/README.md
AI-and-Analytics/README.md

Add README files to explain AI samples.
None.
- [X ] New feature (non-breaking change which adds functionality)
NA
NA

Add README files to explain AI samples

---

Libraries/oneDNN/tutorials/README.md
Libraries/oneDNN/tutorials/codes_for_ipynb/add_loop.patch
Libraries/oneDNN/tutorials/sample.json
Libraries/oneDNN/tutorials/tutorial_vtune_profiling.ipynb

This Jupyter Notebook demonstrates how to use VTune Profiler to profile oneDNN samples and find out performance bottlenecks.
pandas, matplotlib
Administrative
Review

oneDNN VTune profiling tutorial

---

Tools/ApplicationDebugger/array-transform/README.md
Tools/ApplicationDebugger/jacobi/README.md

Change program output in README in order to pass IPLDT checks. @barisaktemur

Tools/ApplicationDebugger: update program output in README files.

---

AI-and-Analytics/Getting-Started-Samples/LPOT-Sample-for-Tensorflow/README.md

Also, I corrected several (R) to …

LPOT get started update for Devcloud node and mode

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/README.md

Made major changes to create separate workflows for users who are running a sample on a local installation and another workflow (section) for users who are running samples on DevCloud. 
1. I did not see an option to run in batch mode, so the instructions do not refer to batch mode.
Fixes Issue# 
None.
Please delete options that are not relevant. Add a 'X' to the one that is …

Rearranged README to have a local section and DevCloud Section

---

AI-and-Analytics/Features-and-Functionality/README.md

added new samples description in README.

Update README.md for tables of AI samples

---

AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/README.md

NOTE: Prior to accepting pull request, please review the commented sections in the README.md:
Fixes Issue# 
None.
Please delete …

updated node and mode information in readme for Tensorflow get started

---

AI-and-Analytics/Getting-Started-Samples/IntelPyTorch_GettingStarted/README.md

NOTE: Prior to accepting pull request, please review the commented sections in the README.md:
Fixes Issue# 
None.
Please delete …

Readme updates for PyTorch Getting Started sample

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Horovod_Multinode_Training/README.md

TF Horovod Readme node mode update

---

AI-and-Analytics/End-to-end-Workloads/Census/README.md

Made major changes to create separate workflows for users who are running a sample on a local installation and another workflow (section) for users who are running samples on DevCloud. 
1. I did not see an option to run in batch mode, so the instructions do not refer to batch mode.
2. In the node table, if a node is applicable to this sample, please change the node name to **BOLD** so users can easily identify which nodes are available. I am not sure if the table is even valid for this sample, since there are not any instructions on how to …

updated Census readme to add DevCloud instructions

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/README.md

Made major changes to create separate workflows for users who are running a sample on a local installation and another workflow (section) for users who are running samples on DevCloud. 
1. I did not see an option to run in batch mode, so the instructions do not refer to batch mode.
2. In the node table, if a node is applicable to this sample, please change the node name to **BOLD** so users can easily identify which nodes are available. I am not sure if the table is even valid for this sample, since there are not any instructions on how to …

Updated readme for TF ModelzooInference

---

AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/README.md

node and mode updates to linear regression readme

---

AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/README.md

1. In the node table, if a node is applicable to this sample, please change the node name to **BOLD** so users can easily identify which nodes are available.
Fixes Issue# 
None.
Text was reviewed and approved by Dan Petre, Donna Boyer, and Joe Oster.
- [x ] VSCode

updated Lidar readme to add DevCloud instructions

---

AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/README.md
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/README.md

Rachel Oberman told me to remove the interactive mode section from the readmes for Distributed LR and KMeans.
Removed interactive section from two readme files.
Fixes Issue# 
None
- [x ] New feature (non-breaking change which adds functionality)
- [ x] VSCode

Removed Interactive Mode from Distributed Sample Readmes

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/tutorial_optimize_TensorFlow_pretrained_model.ipynb

add contents for LPOT fp32 optimization as another model optimization option.
NA

Tf inf lpot

---

DirectProgramming/DPC++/CombinationalLogic/mandelbrot/README.md

Added instructions for how to run mandelbrot in DevCloud
Added DevCloud instructions to readme.md. @argretzi and @m-petrova please review and merge.
Fixes Issue# 
None

Devcloud instructions for mandelbrot

---

DirectProgramming/C++/StructuredGrids/iso3dfd_omp_offload/README.md

Updated the Readme.md for the iso3 dfd sample to include instructions on how to run the sample on the Devcloud in batch mode. Reviewed these changes with @slgogar Sunny Gogar. Sunny should be the one to review and approve/merge this PR.
Fixes Issue# 
https://jira.devtools.intel.com/browse/ONSAM-1388
None
- [ x]  Documentation
- [x ] VSCode

Bdmoore1 iso3 dfd dev cloud instructions

---

DirectProgramming/DPC++/GraphTraversal/hidden-markov-models/README.md

Updated Hidden Markov Model readme to include instructions for Running on DevCloud.
Added instructions for running on DevCloud in batch mode.
Fixes Issue# 
- [x ] New feature (non-breaking change which adds functionality)

hmm readme

---

DirectProgramming/DPC++/N-BodyMethods/Nbody/README.md

Updated Nbody with instructions for how to run on Devcloud.
Added instructions for how to run in batch mode on Devcloud.
Fixes Issue# 
- [ x] Documentation 

nbody readme update

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/src/main.cpp

Super small change to fix wording of a class name.

Small change to merge_sort kernel names

---

Tools/Advisor/matrix_multiply_advisor/README.md
Tools/Advisor/matrix_multiply_advisor/src/multiply.hpp

Added instructions for how to run in batch mode on DevCloud.
Added instructions for how to run in batch mode on DevCloud.
Fixes Issue# 

Update matmul-advisor readme

---

DirectProgramming/DPC++/ParallelPatterns/histogram/README.md

Updated histogram readme for how to run sample on DevCloud in batch mode.
Updated histogram readme for how to run sample on DevCloud in batch mode.
Fixes Issue# 
- [x ] Command Line

histogram readme.md

---

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/Makefile
DirectProgramming/C++/GraphTraversal/MergesortOMP/Makefile

Reverts oneapi-src/oneAPI-samples#595

Revert "Switch to icpx compiler; Add -ipo flag to the linker"

---

AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/README.md

Fixed some punctuation and capitalization.
Fixed punctuation and capitalization.
Fixes Issue# 
- [x ] Documentation
- [ x] VSCode

Minor updates to Modin readme

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt

We need to update the seeds at every release so that the code sample displays the advertised performance.
Fixes Issue# 
N/
a
N/A
Ran the example_designs/gzip regtest using my branch, with seed=6, verified the throughput is > 11.0 GB/s.

Update gzip (High BW) seed for 2021.4 

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt

Signed-off-by: Anandh Venkateswaran <anandh.venkateswaran@intel.com>
A10 performance recently dropped. Updating the seed.
Ran example_designs/gzip regtest against my branch and verified the performance met the target.

Update gzip seed for a10 2021.4

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/README.md

README update for performance numbers and disclaimer about performance.
N/A

Merge sort README update

---

AI-and-Analytics/README.md

the fix for a typo in README. issue was found by a customer. 

Fix for a typo in README

---

AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/README.md

Added missing dependency to readme and supporting note for Ubuntu use.

Updated README for PointPillars sample

---

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/Makefile
DirectProgramming/C++/CompilerInfrastructure/Intrinsics/Makefile
DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_dot_sample.cpp
DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_double_sample.cpp
DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_ftz_sample.cpp
DirectProgramming/C++/GraphTraversal/MergesortOMP/Makefile
DirectProgramming/C++/GraphTraversal/MergesortOMP/src/merge_sort.cpp
DirectProgramming/DPC++/SpectralMethods/DiscreteCosineTransform/src/DCT.cpp
DirectProgramming/DPC++/SpectralMethods/DiscreteCosineTransform/src/DCT.hpp
Libraries/oneMKL/black_scholes/black_scholes.cpp
Libraries/oneMKL/black_scholes/code_wrapper.tpp

We had a few last minute changes to 2021.4, this PR is to pull those changes into the Development branch

Pul late changes from 2021.4 into Development branch

---

Tools/GPU-Occupancy-Calculator/README.md
Tools/GPU-Occupancy-Calculator/index.html

typo in Readme url and minor fix in index.html
Tested in Browser

minor fixes typo in Tools/GPU-Occupancy-Calculator

---

Tools/ApplicationDebugger/jacobi/README.md
Tools/ApplicationDebugger/jacobi/src/jacobi-bugged.cpp
Tools/ApplicationDebugger/jacobi/src/jacobi-fixed.cpp

Restructure the sample, so there are function for initialization, main computation, prepare for the next iteration.
Add error computation.
Add built-in plan for debugging session that user is expected to follow.
Add hints to the user on how bugs can be found.
Extend README and add comments to the code.
Improves user experience.
None
@barisaktemur @tomlenth @xmnboy

Tools/ApplicationDebugger/jacobi: rework the jacobi sample.

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt

Updated seeds for gzip to achieve target performance
Ran example_designs/* regtests and verified performance.

Gzip seeds 2022.1

---

AI-and-Analytics/End-to-end-Workloads/Census/README.md
AI-and-Analytics/End-to-end-Workloads/Census/census_modin.ipynb
AI-and-Analytics/End-to-end-Workloads/Census/sample.json

Fixes Issue# 
Administrative
Review

PR 628 Conda issues: intel-aikit-modin dose not work, install modin-all from conda-forge

---

DirectProgramming/DPC++/OpenCLInterop/src/dpcpp_with_opencl_objects.dp.cpp

Fix OpenCL interoperability deprecations part 1.
Fixes Issue# 
None

Fix deprecations part 1

---

Libraries/oneMKL/computed_tomography/computed_tomography.cpp

Replace sycl::vector_class with std::vector
None

ONSAM-1440

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/src/CMakeLists.txt

Signed-off-by: Aditi Kumaraswamy <aditi.kumaraswamy@intel.com>
Updating the qrd seed to achieve target performance 
Ran regression tests and verified performance.

[FPGA] Updating QRD designs default seed 2022.1

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/README.md
DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/src/CMakeLists.txt

Updating the seed for QRD on Arria 10. Seed 31 achieves 24.7k which is better than we had before.

Updating the QRD seed for A10 to achieve better performance

---

Libraries/oneDNN/dpcpp_interoperability/README.md
Libraries/oneDNN/getting_started/README.md
Libraries/oneDNN/simple_model/README.md

put a note to explain how we copy the source codes into build folder

put a note to explain how we copy the source codes into build folder

---

DirectProgramming/DPC++/ProjectTemplates/Hello_World_GPU/src/main.cpp
DirectProgramming/DPC++/ProjectTemplates/cmake-gpu/src/main.cpp
DirectProgramming/DPC++/ProjectTemplates/makefile-gpu/src/main.cpp

Fixing runtime error by removing deprecated code in 3 samples. Also removing old syntax.
Fixes Issue# https://jira.devtools.intel.com/browse/ONSAM-1395
None.
Tested on devcloud and on nntssg066-x64.inn.intel.com (for Linux samples) and nnlrei012.inn.intel.com (for Windows samples)

Depracated kernel fix

---

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/Makefile
DirectProgramming/C++/CompilerInfrastructure/Intrinsics/Makefile
DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_dot_sample.cpp
DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_double_sample.cpp
DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_ftz_sample.cpp
DirectProgramming/C++/GraphTraversal/MergesortOMP/Makefile
DirectProgramming/C++/GraphTraversal/MergesortOMP/src/merge_sort.cpp
DirectProgramming/DPC++/SpectralMethods/DiscreteCosineTransform/src/DCT.cpp
DirectProgramming/DPC++/SpectralMethods/DiscreteCosineTransform/src/DCT.hpp
Libraries/oneMKL/black_scholes/black_scholes.cpp
Libraries/oneMKL/black_scholes/code_wrapper.tpp

Fixes Issue# 
Administrative
Review

testing from master to test branch

---

Tools/ApplicationDebugger/array-transform/README.md
Tools/ApplicationDebugger/jacobi/README.md

Signed-off-by: Abdul Basit Ijaz <abdul.b.ijaz@intel.com>
IPLDT scan shows issues in Read me file regarding usage of some trademarks.
Fixes Issue# 
None
Fies usage of trademarks in Application debugger samples read me file.
Verified in Application Debugger CI where samples ipldt scan runs fine:
http://ullgdb002.iul.intel.com:8080/job/acl/job/pipeline/9385/

ApplicationDebugger: fix ipldt scan issues in readme files

---

DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/CMakeLists.txt
DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/License.txt
DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/README.md
DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/read_only_cache.sln
DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/read_only_cache.vcxproj
DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/sample.json
DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/src/CMakeLists.txt
DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/src/read_only_cache.cpp

Creating a new tutorial that describes the usage of the read-only cache feature.
Administrative
Review

New Read-only cache FPGA Feature Tutorial

---

AI-and-Analytics/End-to-end-Workloads/Census/README.md
AI-and-Analytics/End-to-end-Workloads/Census/sample.json

Fixes Issue# 
Administrative
Review

install intel-aikit-modin from intel channel instead of modin-all

---

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/README.md

Adding in debug instructions for one README. Once this PR is approved, I will add in the same instruction to all sample README files.
Adding in debug instructions for one README. Once this PR is approved, I will add in the same instruction to all sample README files.
Fixes Issue#  DOC-9021
None
- [ x] documentation
- [x ] VSCode

Sample debug instructions

---

AI-and-Analytics/Getting-Started-Samples/IntelPyTorch_GettingStarted/README.md

Changed Getting-Started Samples to Getting-Started-Samples.
Changed two instances of **Getting-Started Samples** to **Getting-Started-Samples**.
Fixes Issue# no Jira
None
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] VSCode

Pytorch sample readme

---

Libraries/oneCCL/oneCCL_Getting_Started/README.md

some changes for README according to the feedback from oneCCL team

Update README.md 

---

AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/README.md
AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/inc_sample_tensorflow.ipynb

- Edited the text.
- Added information on how to create a kernel to run the notebook in the DevCloud.
- Added information on how to clone the Conda environment if you do not have root access.

INC Sample for TensorFlow. Editing the readme and the Jupyter notebook.

---

DirectProgramming/DPC++FPGA/Tutorials/Features/loop_coalesce/README.md

Updating FPGA tutorial loop_coalesce README to fix namespace for attribute

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/README.md

Missing links in README.md. remove the links because no notebooks files in the repo. 
Instead, we ask users to copy notebooks from AI kit installation folder.

update README.md for some missing links

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzipkernel_ll.cpp
DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/src/merge_sort.hpp
DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/MVDR.hpp
DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/src/compute_units.cpp
DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/pipe_array/src/pipe_array.cpp
DirectProgramming/DPC++FPGA/include/pipe_utils.hpp

Title says it all. Updated all samples using the shared utility.

Moving the PipeArray utility to the fpga_tools namespace

---

AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/src/pointpillars/pointpillars.cpp

Fixes an issue with compilation reported by a client with the PointPillars sample.
Fixes Issue# 
Tested on a local machine.

Fix for PoinPillars sample

---

DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/simple-add-buffers.vcxproj
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/simple-add-usm.vcxproj
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/vector-add-buffers.vcxproj
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/vector-add-usm.vcxproj

Fix warning in Visual studio with shared files with another project
Fixes Issue# 
None

Fix shared project folders

---

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/README.md
DirectProgramming/C++/CompilerInfrastructure/Intrinsics/README.md
DirectProgramming/C++/CompilerInfrastructure/OpenMP_Offload_Features/README.md
DirectProgramming/C++/GraphTraversal/MergesortOMP/README.md
DirectProgramming/C++/Jupyter/OpenMP-offload-training/README.md
DirectProgramming/C++/ParallelPatterns/openmp_reduction/README.md
DirectProgramming/C++/StructuredGrids/iso3dfd_omp_offload/README.md

For each readme in the DirectProgramming/C++ folder, I reviewed and updated to include consistent instructions for:
- Using VS Code
- sourcing or running setvars
- troubleshooting with the diagnostics utility
Partially Fixes Issue#
https://jira.devtools.intel.com/browse/DOC-9252
None
- [x ] Documentation
- [x ] VSCode

Review of C++ Sample READMEs

---

DirectProgramming/DPC++/CombinationalLogic/mandelbrot/README.md
DirectProgramming/DPC++/CombinationalLogic/sepia-filter/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/complex_mult/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/matrix_mul/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/README.md
DirectProgramming/DPC++/GraphAlgorithms/all-pairs-shortest-paths/README.md
DirectProgramming/DPC++/GraphTraversal/bitonic-sort/README.md
DirectProgramming/DPC++/GraphTraversal/hidden-markov-models/README.md
DirectProgramming/DPC++/MapReduce/MonteCarloPi/README.md
DirectProgramming/DPC++/N-BodyMethods/Nbody/README.md
DirectProgramming/DPC++/OpenCLInterop/README.md
DirectProgramming/DPC++/ParallelPatterns/PrefixSum/README.md
DirectProgramming/DPC++/ParallelPatterns/dpc_reduce/README.md
DirectProgramming/DPC++/ParallelPatterns/histogram/README.md
DirectProgramming/DPC++/ParallelPatterns/loop-unroll/README.md
DirectProgramming/DPC++/ProjectTemplates/cmake-fpga/README.md
DirectProgramming/DPC++/ProjectTemplates/cmake-gpu/README.md
DirectProgramming/DPC++/ProjectTemplates/makefile-fpga/README.md
DirectProgramming/DPC++/ProjectTemplates/makefile-gpu/README.md
DirectProgramming/DPC++/SparseLinearAlgebra/merge-spmv/README.md
DirectProgramming/DPC++/SpectralMethods/DiscreteCosineTransform/README.md
DirectProgramming/DPC++/StructuredGrids/1d_HeatTransfer/README.md
DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/README.md
DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/README.md
DirectProgramming/DPC++/StructuredGrids/particle-diffusion/README.md

For each of the README files in the DPC++ folder, I updated sections on setvars, VS Code, and the Diagnostics Utility to all be consistent across the README files.
@ishaghosh27 Please review this PR.
Fixes Issue# 
None
- [x ] VSCode

DPC++ Samples: setvars, VS Code, Diagnostics Utility

---

AI-and-Analytics/End-to-end-Workloads/Census/README.md
AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/README.md
AI-and-Analytics/End-to-end-Workloads/README.md
AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_Performance/README.md
AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_daal4pyPrediction/README.md
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/README.md
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/README.md
AI-and-Analytics/Features-and-Functionality/IntelScikitLearn_Extensions_SVC_Adult/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Horovod_Multinode_Training/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/README.md
AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/README.md
AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPyTorch_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/readme.md

For each readme in the AI-and-Analytics folder, I reviewed and updated to include consistent instructions for:
- Using VS Code
- sourcing or running setvars
- troubleshooting with the diagnostics utility
- 
**Partially** Fixes Issue# 
https://jira.devtools.intel.com/browse/DOC-9252
- [ x] Documentation change
- [x ] VSCode

AI-samples-Readme-Updates

---

DirectProgramming/DPC++FPGA/Tutorials/Features/loop_initiation_interval/README.md

Minor README update only.  Sample output was missing a line.

Update sample output in loop_initiation_interval README file

---

DirectProgramming/DPC++/GraphTraversal/bitonic-sort/src/bitonic-sort.cpp

Removing unnecessary host synchronizations improves performance.

Remove explicit synchronizations for bitonic sort sample

---

AI-and-Analytics/Features-and-Functionality/IntelPyTorch_Extensions_AutoMixedPrecision/README.md
AI-and-Analytics/Features-and-Functionality/IntelPyTorch_TorchCCL_Multinode_Training/README.md

Fixes Issue# 
Administrative
Review

Update torch-ccl and AMP samples

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/scripts/enable_log.patch
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/tutorial_optimize_TensorFlow_pretrained_model.ipynb

add a note to bring up a limitation of freeze_optimize_v2.pu
Fixes Issue# 
https://jira.devtools.intel.com/browse/TFDO-5220

a note for limitation of freeze_optimize_v2.py

---

AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/README.md

- Used a new template.
- Edited the text and structure.
- Added information on how to create a kernel to run the notebook in the DevCloud.
- Removed information about activating conda environment without root access (not yet applicable)
- [*] Command Line

Intel Modin Getting Started Sample. Readme edits.

---

Libraries/oneDNN/tutorials/tutorial_verbose_jitdump.ipynb
Libraries/oneDNN/tutorials/tutorial_vtune_profiling.ipynb

a fix for a compilation issue due to a product change.
Fixes Issue# ONSAM-1476 
NA

fix for ONSAM-1476 

---

Libraries/oneCCL/README.md
Libraries/oneCCL/oneCCL_Getting_Started/README.md

changes for oneccl 2021.6 release

changes for oneccl 2021.6 release

---

DirectProgramming/DPC++/MapReduce/MonteCarloPi/MonteCarloPi.vcxproj

Change linker optimization for release mode
Fixes Issue# 
None

Fix for ONSAM-1480

---

DirectProgramming/DPC++FPGA/include/README.md

Updating the FPGA shared include directory README with missing files and reordered the files to match the alphabetical order.

Updating README for FPGA shared include directory.

---

AI-and-Analytics/README.md
AI-and-Analytics/q
AI-and-Analytics/version_check.py

modify Q script for the latest DevCloud and add sanity check
no

modify Q script for the latest DevCloud and add sanity check

---

AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/README.md

Used a new template.
Edited the text and structure.

Intel Python daal4py Get Started Sample. Readme edits.

---

DirectProgramming/DPC++/DenseLinearAlgebra/jacobi_iterative/sycl_migrated/src/jacobi.cpp
DirectProgramming/DPC++/DenseLinearAlgebra/jacobi_iterative/sycl_migrated_optimized/src/jacobi.cpp

Signed-off-by: PradeepPotteti <potteti.pradeep@gmail.com>
jacobi_iterative application (DenseLinearAlgebra) optimization
Fixes Issue# 

Jacobi sample optimization

---

DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/README.md
DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/Welcome.ipynb

Jupyter oneapi: updated readme and Welcome page

Jupyter oneapi: updated readme and Welcome page

---

AI-and-Analytics/Jupyter/Numba_DPPY_Essentials_training/README.md

Fixed typo parallel
Fixes Issue# 
Administrative
Review

Fixed typo, second try

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/cholesky/README.md
DirectProgramming/DPC++FPGA/ReferenceDesigns/cholesky/src/cholesky.hpp
DirectProgramming/DPC++FPGA/ReferenceDesigns/cholesky/src/cholesky_demo.cpp
DirectProgramming/DPC++FPGA/ReferenceDesigns/cholesky/src/memory_transfers.hpp

Improving the comments and syntax of the cholesky reference design

FPGA: Improving comments in Cholesky and fixing broken link

---

AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/README.md

Removed and changed DPCPP instances. Updated some formatting. Changed linux sudo instructions. Did not change graphic.
Changed or removed DPCPP instances. Updated branding in a few cases. Updated Linux sudo command to match wording in guides.
Fixes Issue# 
None/
- [X ] VSCode

Changed DPCPP instances and updated branding

---

AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/README.md
DirectProgramming/C++/CompilerInfrastructure/OpenMP_Offload_Features/README.md

Change several instances of DPC++ and DPCPP to SYCL. Updated branding and corrected some formatting issues. 
Fixes Issue# 

Jmkinsky 6 2 2022

---

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/README.md
DirectProgramming/C++/CompilerInfrastructure/OpenMP_Offload_Features/README.md
DirectProgramming/C++/ParallelPatterns/openmp_reduction/README.md
DirectProgramming/C++/StructuredGrids/iso3dfd_omp_offload/README.md
DirectProgramming/DPC++/CombinationalLogic/mandelbrot/README.md
DirectProgramming/DPC++/CombinationalLogic/sepia-filter/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/complex_mult/README.md

Changed DPC++ instance and oblique references to SYCL appropriate language in 7 files.
Updated 7 files:
File: DirectProgramming\C++\CompilerInfrastructure\OpenMP_Offload_Features\README.md
Changes: Updated DPC++ to SYCL instances where needed. Updated link references. Updated note on setting vars since I was in the file. Corrected some branding issues.
File: DirectProgramming\C++\ParallelPatterns\openmp_reduction\README.md
Changes: Updated branding. Fixed two formatting issues. Updated note on setting vars since I was in the file. Changes one instance of DPC++ in link text.
File: DirectProgramming\C++\StructuredGrids\iso3dfd_omp_offload\README.md
Changes: Corrected one branding issue related to DPC++ compiler and updated/corrected some formattting issues. Updated note on setting vars …

Multi-file DPC++ to SYCL changes

---

DirectProgramming/DPC++/DenseLinearAlgebra/jacobi_iterative/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/matrix_mul/README.md

Changed instances of DPC++ to SYCL where appropriate in 2 files.
File: DirectProgramming\DPC++\DenseLinearAlgebra\jacobi_iterative\README.md
Changes: Removed instances of DPC++ where necessary. Updated branding and formatting issues.
File: DirectProgramming\DPC++\DenseLinearAlgebra\matrix_mul\README.md
Changes: Changed instances of DPC++ to SYCL where appropriate. Updated note about setting vars. Fixed formatting issues.  
Fixes Issue# 
N/A

DPC++ to SYCL changes continued

---

AI-and-Analytics/Jupyter/Numba_dpex_Essentials_training/05_dpex_Kmeans/run_kmeans_atomic.sh
AI-and-Analytics/Jupyter/Numba_dpex_Essentials_training/Welcome.ipynb

Updated Welcome.ipynb and a small change in one of the script files
Fixes Issue# 

updated Readme in the notebooks

---

DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/README.md
DirectProgramming/DPC++/GraphAlgorithms/all-pairs-shortest-paths/README.md
DirectProgramming/DPC++/GraphTraversal/bitonic-sort/README.md
DirectProgramming/DPC++/GraphTraversal/hidden-markov-models/README.md

Updated multiple files to change DPC++ to SYCL where appropriate. Updated formatting and updated links.
Changed multiple files to continue work to change DPC++ to SYCL where appropriate.
File: ...\DirectProgramming\DPC++\DenseLinearAlgebra\simple-add\README.md
Changes: Changes some instances of DPC++ to SYCL. Updated some branding. Corrected links. Corrected multiple formatting issues. Updated setting vars information. Removed redundant instances of diagnostics text.
File: ...\DirectProgramming\DPC++\DenseLinearAlgebra\vector-add\README.md
Changes: Changes some instances of DPC++ to SYCL. Updated some branding. Corrected links. Corrected multiple formatting issues. Updated diagnostics text section. Updated setting vars information.
File: …

DPC++ to SYCL changes to multiple files (again)

---

DirectProgramming/DPC++/GraphTraversal/odd-even-merge-sort/README.md
DirectProgramming/DPC++/MapReduce/MonteCarloPi/README.md
DirectProgramming/DPC++/N-BodyMethods/Nbody/README.md
DirectProgramming/DPC++/OpenCLInterop/README.md
DirectProgramming/DPC++/ParallelPatterns/dpc_reduce/README.md
DirectProgramming/DPC++/ParallelPatterns/histogram/README.md

More changes related to DPC++ in readme files. First batch of changes with fully restructured files.
First batch of files with structural changes to match the agreed upon template. 
File: ...\DirectProgramming\DPC++\GraphTraversal\odd-even-merge-sort\README.md
Changes: Removed some instances of DPC++. Rewrote some sentences to adapt to SYCL comformance. Updated vars information. Updated multiple formatting issues. Updated branding where needed. Restructured or moved sections based on new template structure agreements. 
File: ...\DirectProgramming\DPC++\MapReduce\MonteCarloPi\README.md
Changes: Updated branding. Change DPCC++ to SYCL or rewrote as necessary. Updated vars information. Corrected multiple formatting issues. Restructured or moved sections based on new template structure …

DPC++ to SYCL changes (yet again)

---

DirectProgramming/DPC++/ParallelPatterns/PrefixSum/README.md
DirectProgramming/DPC++/ParallelPatterns/loop-unroll/README.md
DirectProgramming/DPC++/ProjectTemplates/Hello_World_GPU/README.md
DirectProgramming/DPC++/ProjectTemplates/cmake-fpga/README.md
DirectProgramming/DPC++/ProjectTemplates/cmake-gpu/README.md
DirectProgramming/DPC++/ProjectTemplates/makefile-fpga/README.md
DirectProgramming/DPC++/ProjectTemplates/makefile-gpu/README.md

Updating readme in loop-unroll, prefix sum, and projecttemplates
Updated 7 README.md files
File: ...\DirectProgramming\DPC++\ParallelPatterns\loop-unroll\README.md
Changes: Restructured the topic to match current readme structure agreements. Updated setting vars information. Corrected multiple formatting issues. Change DPC++ to SYCL* as needed.
File: ...\DirectProgramming\DPC++\ParallelPatterns\PrefixSum\README.md
Changes: Restructured the topic to match current readme structure agreements. Updated math formatting. Corrected multiple formatting issues. Change DPC++ to SYCL* as needed. Updated branding issues. Updated setting vars information. 
File: ...\DirectProgramming\DPC++\ProjectTemplates\cmake-fpga\README.md
Changes: Updated the "what you will learn" information to match the main …

Updating readme in loop-unroll, prefix sum, and projecttemplates

---

DirectProgramming/DPC++/SparseLinearAlgebra/merge-spmv/README.md
DirectProgramming/DPC++/SpectralMethods/DiscreteCosineTransform/README.md
DirectProgramming/DPC++/StructuredGrids/1d_HeatTransfer/README.md
DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/README.md
DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/README.md
DirectProgramming/DPC++/StructuredGrids/particle-diffusion/README.md

Updated README.md files for DPC++ to SYCL and to match new template.
Updated README.md files for DPC++ to SYCL and to match new template.
File: ...\DirectProgramming\DPC++\SparseLinearAlgebra\merge-spmv\README.md
Changes: Changed some instances of DPC++ to SYCL. Changed file structure to conform with new README.md template agreements. Updated vars information. Correct multiple formatting issues. Changed heading case usage in a couple of places. Rewrote a few lines of text.
File: ...\DirectProgramming\DPC++\SpectralMethods\DiscreteCosineTransform\README.md
Changes: Removed DPC++ from title. Changed multiple instances of DPC++ to SYCL. Changed file structure to conform with new README.md template agreements. Updated vars information. Corrected multiple formatting issues. Rewrote a few lines …

Another round of README.md changes

---

DirectProgramming/DPC++/CombinationalLogic/mandelbrot/README.md

Updated the README.md for DPC++ Combinational Logic > Mandelbrot. Rewrote and restructured most sections.
Completely restructured the README.md file. Updated multiple sections and rewrote instructions for clarity.
Fixes Issue# 
N/A
N/A

readme update for dpc++>com-logic>mandelbrot

---

DirectProgramming/DPC++/DenseLinearAlgebra/complex_mult/README.md

Updated and restructured the Complex Multiplication README.md file to match the new template. Corrected multiple formatting and branding issues.
Updated README.md file to match new template. 
N/A

Restructure Complex Multiplication README.md file

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/README.md
DirectProgramming/DPC++FPGA/ReferenceDesigns/decompress/README.md
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/README.md
DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/README.md
DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/README.md
DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/README.md
DirectProgramming/DPC++FPGA/ReferenceDesigns/qri/README.md
DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/autorun/README.md
DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/buffered_host_streaming/README.md
DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/README.md
DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/double_buffering/README.md

Changing just DPC++ to SYCL where appropriate and updating branding to match legal requirements. No other restructuring except where absolutely essentials.
Continue work DPC++ to SYCL changes in DPC++FPGA directories.
Changing just DPC++ to SYCL where appropriate and updating branding to match legal requirements. No other restructuring except where absolutely essentials. Changed the following 11 files.
\oneAPI-samples\DirectProgramming\DPC++FPGA\ReferenceDesigns\db\README.md
\oneAPI-samples\DirectProgramming\DPC++FPGA\ReferenceDesigns\decompress\README.md
\oneAPI-samples\DirectProgramming\DPC++FPGA\ReferenceDesigns\gzip\README.md
\oneAPI-samples\DirectProgramming\DPC++FPGA\ReferenceDesigns\merge_sort\README.md
\oneAPI-samples\DirectProgramming\DPC++FPGA\ReferenceDesigns\mvdr_beamforming\RE …

DPC++ to SYCL changes in FPGA readmes - another batch

---

DirectProgramming/DPC++/CombinationalLogic/sepia-filter/README.md

Extensive changes to structure. Rewrites for clarity.
Update sepia filter README.md to conform to new template. Rewrote and restructure many sections for clarity. 
Fixes Issue# 
N/A

Update sepia filter readme.md to match new template

---

DirectProgramming/DPC++/DenseLinearAlgebra/matrix_mul/README.md

A nearly complete rewrite of the README.md file.
Nearly complete rewrite of the matmul README.md file. Added missing information. Restructured to match new template.
Fixes Issue# 
Usability
N/A

Matrix Multiply README.md update

---

Libraries/oneCCL/oneCCL_Getting_Started/README.md
Libraries/oneCCL/tutorials/README.md
Libraries/oneDNN/getting_started/README.md
Libraries/oneDPL/gamma-correction/README.md
Libraries/oneDPL/stable_sort_by_key/README.md
Libraries/oneMKL/black_scholes/README.md
Libraries/oneMKL/block_cholesky_decomposition/README.md
Libraries/oneMKL/block_lu_decomposition/README.md
Libraries/oneMKL/computed_tomography/README.md
Libraries/oneMKL/matrix_mul_mkl/README.md
Libraries/oneMKL/monte_carlo_european_opt/README.md
Libraries/oneMKL/monte_carlo_pi/README.md
Libraries/oneMKL/random_sampling_without_replacement/README.md
Libraries/oneMKL/sparse_conjugate_gradient/README.md
Libraries/oneMKL/student_t_test/README.md
Libraries/oneTBB/README.md
Libraries/oneTBB/tbb-async-sycl/README.md
Libraries/oneTBB/tbb-resumable-tasks-sycl/README.md
Libraries/oneTBB/tbb-task-sycl/README.md
Libraries/oneVPL/dpcpp-blur/README.md

Completed all DPC++ to SYCL changes in libraries directories/sub-directories. Changing just DPC++ to SYCL where appropriate and updating branding to match legal requirements.
Completed all DPC++ to SYCL changes in libraries directories/sub-directories.
Changing just DPC++ to SYCL where appropriate and updating branding to match legal requirements. No other restructuring except where absolutely essentials; fixed major content and formatting issues in multiple files. Fixed multiple branding issues. (Note: Excluded files in libraries that did not contain "DPC++" instances.)
Updated the following 20 files:
\oneAPI-samples\Libraries\oneCCL\oneCCL_Getting_Started\README.md
\oneAPI-samples\Libraries\oneCCL\tutorials\README.md
\oneAPI-samples\Libraries\oneDNN\getting_started\README.md …

Update README.md files in libraries directories for DPC++ to SYCL changes.

---

AI-and-Analytics/Features-and-Functionality/IntelPyTorch_Extensions_AutoMixedPrecision/README.md

Updates of the IPEX AMP training with BF16
Fixes Issue# 
Administrative …

update IPEX AMP sample

---

DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/README.md

Restructured and rewrote most of the simple add readme.md file.
Restructured Simple Add README.md to conform with new template. Corrected many formatting issues. Rewrote and restructured sections for clarity.
Fixes Issue# 
N/A

Update simple add readme.md file

---

DirectProgramming/DPC++/ParallelPatterns/histogram/src/main.cpp

Fixing error: Assertion in histogram example occurred
Copied changes from
https://github.com/oneapi-src/oneDPL/pull/573/files
into examples repository.

Fix errors in histogram example

---

AI-and-Analytics/End-to-end-Workloads/Census/README.md
AI-and-Analytics/End-to-end-Workloads/README.md
AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_Performance/README.md
AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_daal4pyPrediction/README.md
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/README.md
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/README.md
AI-and-Analytics/Features-and-Functionality/Intel_Extension_For_SKLearn_Performance_SVC_Adult/README.md
AI-and-Analytics/Features-and-Functionality/README.md
AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/README.md
AI-and-Analytics/Getting-Started-Samples/IntelAIKitContainer_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/readme.md
AI-and-Analytics/Getting-Started-Samples/README.md
AI-and-Analytics/Jupyter/Numba_dpex_Essentials_training/README.md
AI-and-Analytics/README.md
Libraries/oneDAL/IntelPython_daal4py_Distributed_Kmeans/README.md
Libraries/oneDAL/IntelPython_daal4py_Distributed_LinearRegression/README.md
Libraries/oneDAL/IntelPython_daal4py_Getting_Started/README.md

Changed name from Intel oneAPI AI Analytics Toolkit to Intel AI Analytics Toolkit in multiple files.
Changed product/marketing name from "Intel oneAPI AI Analytics Toolkit" to "Intel AI Analytics Toolkit" in multiple files. No other changes. 
Fixes Issue# 
N/A

AI Toolkit name change

---

DirectProgramming/DPC++/GraphTraversal/odd-even-merge-sort/README.md

Updating structure to match new template and updated branding. Rewrote for clarity and to match the jacobi-iterative example.
Restructured the README for clarity. Changed the sample name in the readme.md to match what is in the sample.json file. Updated some formatting. Rewrote for clarity.
Fixes Issue# 
N/A
- [ x] VSCode

Update odd-even mergesort README

---

DirectProgramming/DPC++/GraphAlgorithms/all-pairs-shortest-paths/README.md

Restructure and updated readme to match current template.
Updated all pairs shortest paths sample README.md to conform with new template. Updated branding and product names as needed. Reformatted and restructured as needed.
Fixes Issue# 
N/A
-
- [x ] VSCode

Update all pairs shortest paths readme

---

DirectProgramming/DPC++/OpenCLInterop/README.md

Restructured to match new template. Updated branding. Fixed one link. Fixed some minor formatting issues. 
Fixes Issue# 

Updated OpenCL Interop README.md

---

DirectProgramming/DPC++/GraphTraversal/hidden-markov-models/README.md

Restructured to match new template, and updated for clarity.
Fixes Issue# 
N/A

Update hidden markov README.md

---

DirectProgramming/DPC++/GraphTraversal/bitonic-sort/README.md

Updated information. Included new information on running sample on Windows. Restructured to match the new template.
Fixes Issue# 
N/A

Update Bitonic README.md files

---

DirectProgramming/DPC++/MapReduce/MonteCarloPi/README.md

Restructured README.md to match new template. Updated branding. Rewrote for clarity.
Fixes Issue# 
N/A

Updated MonteCarloPi README

---

DirectProgramming/DPC++/ParallelPatterns/PrefixSum/README.md

Restructured to match new template. Added Windows build and run information. Fixed some formatting issues. Updated branding.
Fixes Issue# 

Update Prefix Sum README.md

---

DirectProgramming/DPC++/ParallelPatterns/dpc_reduce/README.md

Updated to match new template. Rewrote sections for clarity. Updated branding.
Fixes Issue# 
N/A

Update the dpc reduce README.md

---

DirectProgramming/DPC++/ParallelPatterns/histogram/README.md

Updated structure to match new template. Clarified the input and output information. Updated several sections to improve clarity.
Fixes Issue# 
N/A

Update histogram README.md

---

DirectProgramming/DPC++/ParallelPatterns/loop-unroll/README.md

Restructured readme to match new template. Updated branding. Rewrote for clarity and added some Windows information.
Fixes Issue# 
N/A

Update loop unroll readme.md

---

DirectProgramming/DPC++/ParallelPatterns/histogram/README.md

Removed FPGA hardware from optimized for table.
Fixes Issue# 
N/A
Administrative
Review

Updated Histogram readme again

---

DirectProgramming/DPC++/SparseLinearAlgebra/merge-spmv/README.md

Updated structure to match new template. Rewrote sections for clarity. Updated Windows information. Added missing sections and information.
Fixes Issue# 
N/A

Update merge spmv readme

---

DirectProgramming/DPC++/SpectralMethods/DiscreteCosineTransform/README.md

Restructured to match new template. Corrected Windows build information. Fixed some formatting issues.
Fixes Issue# 
N/A

Updated DCT sample Readme.md file.

---

DirectProgramming/C++/Jupyter/OpenMP-offload-training/USM/run.sh
DirectProgramming/C++/Jupyter/OpenMP-offload-training/USM/run_usm_explicit.sh
DirectProgramming/C++/Jupyter/OpenMP-offload-training/datatransfer/run.sh
DirectProgramming/C++/Jupyter/OpenMP-offload-training/datatransfer/run_data.sh
DirectProgramming/C++/Jupyter/OpenMP-offload-training/intro/run.sh
DirectProgramming/C++/Jupyter/OpenMP-offload-training/parallelism/run.sh
DirectProgramming/Fortran/Jupyter/OpenMP-offload-training/USM/run.sh
DirectProgramming/Fortran/Jupyter/OpenMP-offload-training/datatransfer/run.sh
DirectProgramming/Fortran/Jupyter/OpenMP-offload-training/datatransfer/run_data.sh
DirectProgramming/Fortran/Jupyter/OpenMP-offload-training/intro/run.sh
DirectProgramming/Fortran/Jupyter/OpenMP-offload-training/parallelism/run.sh

This fixes submission environment for some users on DevCloud that require it
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Command Line
- [x ] oneapi-cli
- [x ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

Environment Variable Needed for Certain Executions

---

DirectProgramming/DPC++/StructuredGrids/1d_HeatTransfer/README.md

Updated to match new template structure. Added Windows information. Fixed formatting issues. Updated devcloud information.
Fixes Issue# 
N/A

Updated 1dHeatTransfer README.md

---

DirectProgramming/DPC++/DenseLinearAlgebra/matrix_mul/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/matrix_mul/build.sh
DirectProgramming/DPC++/DenseLinearAlgebra/matrix_mul/build_omp.sh
DirectProgramming/DPC++/DenseLinearAlgebra/matrix_mul/run.sh
DirectProgramming/DPC++/DenseLinearAlgebra/matrix_mul/run_omp.sh
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/build.sh
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/build_fpga.sh
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/build_fpga_emu.sh
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/run.sh
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/run_fpga.sh
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/run_fpga_emu.sh
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/build.sh
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/build_fpga.sh
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/build_fpga_emu.sh
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/run.sh
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/run_fpga.sh
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/run_fpga_emu.sh
DirectProgramming/DPC++/GraphAlgorithms/all-pairs-shortest-paths/README.md
DirectProgramming/DPC++/GraphAlgorithms/all-pairs-shortest-paths/build.sh
DirectProgramming/DPC++/GraphAlgorithms/all-pairs-shortest-paths/run.sh
DirectProgramming/DPC++/GraphTraversal/bitonic-sort/README.md
DirectProgramming/DPC++/GraphTraversal/bitonic-sort/build.sh
DirectProgramming/DPC++/GraphTraversal/bitonic-sort/run.sh
DirectProgramming/DPC++/GraphTraversal/hidden-markov-models/README.md
DirectProgramming/DPC++/GraphTraversal/hidden-markov-models/build.sh
DirectProgramming/DPC++/GraphTraversal/hidden-markov-models/run.sh

The DevCloud uses a batch system for processing. To get the samples to run, users need to know how to create the script or know how to request an interactive mode.
To make it easier for DevCloud users to run the sample, I created scripts to build (build.sh) and run (run.sh) on DevCloud. Proper documentation explaining the process has been added to README.md.
In the hidden-markov-models example, there have been some major changes to the documentation. We decided to create separate scripts instead of explaining to users how to do it themselves. This makes it easier for the user to run the samples right after connecting to DevCloud using only one command and it improves the UX
This change  will be later followed by others for the remaining samples
List any external dependencies created as a …

 Github repo and DevCloud better integration

---

DirectProgramming/C++/CompilerInfrastructure/Intrinsics/Makefile

Fixes Issue# 
Administrative
Review

Makefile changes to support sse3 for icpx

---

DirectProgramming/Fortran/Jupyter/OpenMP-offload-training/README.md

Restructured to match part of new template. Updated branding. Fixed some formatting issues. Added information on connecting to DevCloud and running these notebooks.
Fixes Issue# 
N/A

Update jupyter openmp offload readme

---

DirectProgramming/Fortran/CombinationalLogic/openmp-primes/README.md

Updated to match new template as much as possible. Fixed multiple markdown formatting issues. Corrected many links. Rewrote for clarity.
Fixes Issue# 
N/A

Update fortran openmp primes readme

---

AI-and-Analytics/End-to-end-Workloads/Census/README.md
AI-and-Analytics/End-to-end-Workloads/README.md

Restructured the readme to match the new template, fixed formatting issues, updated branding, and rewrote it for clarity. Added new information about running it in Intel® DevCloud via JupyterLab, as that seems the most practical method for running this type of sample.
Also updated ..\oneAPI-samples\AI-and-Analytics\End-to-end-Workloads\README.md. Fixed some formatting and branding issues.(Included in this pull request for convenience.)
Fixes Issue# 
N/A

Updated census sample readme

---

AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/README.md

Restructured the entire match our new template structure. Changed the sample name in the readme to match the sample.json file. Added information on setting vars for base toolkit and openvino.
Fixes Issue# 
N/A

Update point pillar readme.md

---

DirectProgramming/Fortran/DenseLinearAlgebra/optimize-integral/README.md

Restructured it to match the new template as much as possible. Added new sections, corrected formatting issues, changed heading levels, updated branding, and rewrote for clarity.
Fixes Issue# 
N/A

Update Fortran Optimize Integral Readme

---

DirectProgramming/Fortran/DenseLinearAlgebra/vectorize-vecmatmult/README.md

Restructured the readme to match the new template as much as possible, corrected links, updated branding, changes heading levels, added new sections, fixed formatting issues, and rewrote for clarity.
Fixes Issue# 
N/A

Update Fortran Vectorize VecMatMult readme

---

DirectProgramming/DPC++/MapReduce/MonteCarloPi/src/monte_carlo_pi.cpp
DirectProgramming/DPC++/N-BodyMethods/Nbody/src/GSimulation.cpp

Remove extension namespaces from reduction.
Fixes Issue# 
None

ONSAM-1505

---

DirectProgramming/C++/CompilerInfrastructure/Intrinsics/README.md

Restructured to match new template. Corrected links. Updated branding. Corrected some formatting.
Fixes Issue# 
N/A

Update intrinsics readme.md file

---

DirectProgramming/C++/CompilerInfrastructure/OpenMP_Offload_Features/README.md

Restructured to match new template. Updated branding. Fixed formatting. Rewrote for clarity.
Fixes Issue# 
N/A

Update C++ OpenMP offload readme

---

DirectProgramming/C++/GraphTraversal/MergesortOMP/README.md

Restructured to match new template. Rewrote for clarity. Fixed formatting.
Fixes Issue# 
N/A

Update C++ mergesort readme

---

DirectProgramming/C++/ParallelPatterns/openmp_reduction/README.md

Restructured to match new format. Fixed some formatting issues. Rewrote for clarity.
Fixes Issue# 
N/A

Update C++ OpenMP reduction readme

---

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/README.md

Restructured this readme to match new template, rewrote for clarity, corrected formatting issues, and adding some missing information about the output.
Fixes Issue# 
N/A

Update the Mandlebrot OMP readme

---

DirectProgramming/DPC++/ParallelPatterns/loop-unroll/README.md

Updated readme with note on how to disable hangcheck. Added additional details about building on DevCloud.
Fixes Issue# 
N/A

Update loop unroll readme with hangcheck information

---

DirectProgramming/DPC++/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/sample.json

sample.json file was missing a GUID
Fixes Issue# 
None

sample.json file was missing a GUID

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/anr/README.md

Restructured to match the new template. Updated the markdown to conform to standard support. Moved several sections around, split Windows and Linux build and run information into separate sections, and added detail to the DevCloud section.
Fixes Issue# 
N/A

Update FPGA ANR ref design readme

---

DirectProgramming/DPC++/OpenCLInterop/src/dpcpp_with_opencl_objects.dp.cpp

Change SYCL headers
Fixes Issue# 
None.

ONSAM-1495

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/cholesky/README.md

Restructured the document extensively, split out the Linux and Windows build and run commands, added details to the DevCloud section, updated some branding, and rewrote some of the text for clarity.
Fixes Issue# 
N/A

Update FPGA Cholesky decomposition readme

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/board_test/README.md

Restructured this to match the new template. Spilt Linux and Windows instructions, rewrote for clarity, updated branding, fixed formatting, and added details to the DevCloud section.
Fixes Issue# 
N/A

Update FPGA board test readme

---

DirectProgramming/DPC++/ProjectTemplates/makefile-gpu/README.md

Updated to match new template. Changed some formatting. Fixed some branding, General rewrite.
Fixes Issue# 
N/A
Administrative
Review

Update Makefile GPU sample template readme

---

DirectProgramming/DPC++/ProjectTemplates/Hello_World_GPU/README.md

Updated to match new template. Changed some formatting. Fixed some branding, General rewrite.
Fixes Issue# 
N/A

Update Hello World MVS GPU template readme

---

DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/Makefile.fpga
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/Makefile.win.fpga
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/sample.json
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/Makefile.fpga
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/Makefile.win.fpga
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/README.md
DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/sample.json

The vector-add and simple-add samples have been reworked to have simpler makefiles and more explicit compilation commands.

Rework of vector-add and simple-add samples when targetting FPGAs

---

AI-and-Analytics/Jupyter/Predictive_Modeling_Training/AI_Kit_XGBoost_Predictive_Modeling.complete/00_Local_Setup/Local_Setup.ipynb
AI-and-Analytics/Jupyter/Predictive_Modeling_Training/AI_Kit_XGBoost_Predictive_Modeling/00_Local_Setup/Local_Setup.ipynb

Fixed https://jira.devtools.intel.com/browse/[DDP6-543](https://jira.devtools.intel.com/browse/DDP6-543)
Fixes Issue# 

Fixed for JIRA DDP6-543 AI_KIT_XGBoost_Predictive_Modeling

---

README.md

Added information on cloning stable version of repo.
Fixes Issue# 

Add git information to readme

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/sample.json

This is fixing badly formatted the mvdr sample.json file

FPGA: fix mvdr sample.json

---

DirectProgramming/DPC++/ProjectTemplates/cmake-gpu/README.md

Restructured to match new template. Corrected formatting issues. Updated branding. Removed Windows information.
Fixes Issue# 
N/A

Update GPU template readme

---

DirectProgramming/DPC++/ProjectTemplates/cmake-fpga/README.md

Restructured to match new template. Corrected formatting issues. Updated branding. Added DevCloud Information where necessary (since they could be on DevCloud too). Changed build information to match what was in the sample.json file. (This might be throw-away work, but I committed to it, so I’m doing it.)
Fixes Issue# 
N/A

Update FPGA Cmake template readme

---

DirectProgramming/C++/StructuredGrids/iso3dfd_omp_offload/README.md

Restructured the readme to match new template, rewrote several sections for clarity, and shortened the DevCloud information to make it more concise.
Restructured the readme to match new template, rewrote several sections for clarity, and shortened the DevCloud information to make it more concise.
Fixes Issue# 
N/A

Update C++ ISO3DFD readme file

---

DirectProgramming/DPC++/ProjectTemplates/makefile-fpga/README.md

Restructured to match new template. Corrected formatting issues. Updated branding. Added DevCloud Information where necessary (since they could be on DevCloud too). (This might be throw-away work, but I committed to it, so I’m doing it.)
Fixes Issue# 
N/A

Update makefile FPGA template readme

---

DirectProgramming/DPC++/CombinationalLogic/sepia-filter/src/sepia_dpcpp.cpp
DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/02_DPCPP_Program_Structure/lab/gpu_sample.cpp
DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/02_DPCPP_Program_Structure/src/gpu_sample.cpp
DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/06_Intel_VTune_Profiler/include/iso3dfd.h
DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/06_Intel_VTune_Profiler/src/iso3dfd.cpp
DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/06_Intel_VTune_Profiler/src/iso3dfd_kernels.cpp
DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/06_Intel_VTune_Profiler/src/utils.cpp
DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/07_DPCPP_Library/lab/ranges.cpp
DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/07_DPCPP_Library/src/ranges.cpp
DirectProgramming/DPC++/N-BodyMethods/Nbody/src/GSimulation.cpp
DirectProgramming/DPC++/ParallelPatterns/dpc_reduce/src/main.cpp
DirectProgramming/DPC++/ProjectTemplates/Hello_World_GPU/src/main.cpp
DirectProgramming/DPC++/ProjectTemplates/cmake-fpga/src/main.cpp
DirectProgramming/DPC++/ProjectTemplates/cmake-gpu/src/main.cpp
DirectProgramming/DPC++/ProjectTemplates/makefile-fpga/src/main.cpp
DirectProgramming/DPC++/ProjectTemplates/makefile-gpu/src/main.cpp
DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/src/iso2dfd.cpp
DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/src/max_interleaving.cpp

DPCPP 2023 breaking change: remove usage of 'cl' namespace from examples.
Fixes Issue# 
Administrative
Review

DPCPP 2023 : remove usage of cl namespace

---

DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/README.md

Restructured and rewrote based on new build files. Change connected to https://github.com/oneapi-src/oneAPI-samples/pull/1134. 
Fixes Issue# 
Must be merged with https://github.com/oneapi-src/oneAPI-samples/pull/1134.

Update the vector add readme

---

AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/IntelModin_GettingStarted.ipynb
AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/README.md

Fixes Issue# 
Administrative
Review

Add workaround for running Modin with Ray backend on Intel oneAPI DevCloud, updated README for DevCloud as well. 

---

DirectProgramming/DPC++FPGA/Tutorials/Features/private_copies/src/private_copies.cpp

Push device selectors into the function to avoid using the deprecated device_selector class

---

AI-and-Analytics/Jupyter/Predictive_Modeling_Training/AI_Kit_XGBoost_Predictive_Modeling.complete/00_Local_Setup/Local_Setup.ipynb
AI-and-Analytics/Jupyter/Predictive_Modeling_Training/AI_Kit_XGBoost_Predictive_Modeling/00_Local_Setup/Local_Setup.ipynb

Fixes Issue# 
Administrative
Review

Fixed typo on copy command in module 0

---

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/README.md

The function of Mandelbrot OMP Sample has been updated

mandelbrot README.md file updated 

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/crr/README.md

Restructured to match new template. Corrected formatting and branding issues. Updated some links. Added information on running in devcloud.
Fixes Issue# 
N/A

Updated CRR binomial readme.md file

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/README.md

Restructured the readme to match the new template. I revised and structure and formatting extensively. I updated branding and some links. Added information about running this on DevCloud.
Fixes Issue# 
N/A

Update DB reference design sample readme

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/README.md

Restructured the readme to match the new template. Corrected formatting, added information on running the sample in DevCloud, fixed branding and some links, added information on the reports, and significantly restructured the readme sections for clarity. Updated branding.
Fixes Issue# 
N/A

Update GZIP fpga sample readme

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/decompress/README.md

Restructured the readme to match the new template. Corrected formatting, added information on running the sample in DevCloud, fixed branding and some links, and significantly restructured the readme.
Fixes Issue# 
N/A

Update decompress fpga readme

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/README.md

Restructured this to readme to match the new template. Corrected some branding issues, several formatting issues, and corrected some spelling errors. Restructured the readme sections extensively. Added more complete information about running this in DevCloud.
Fixes Issue# 
N/A

Updated Merge Sort sample readme

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/README.md

Updated readme to match new template. Significantly restructured the sections, updated information on running in DevCloud, corrected branding, rewrote some sections for clarity, and fixed some links. Fixed multiple formatting issues.
Fixes Issue# 
N/A

Update MVDR beamforming sample readme

---

DirectProgramming/DPC++/GraphTraversal/odd-even-merge-sort/README.md

Added link to document on intel.com
Fixes Issue# 
N/A

Update oddevenmergesort readme

---

DirectProgramming/DPC++/StructuredGrids/guided_HSOpticalflow_SYCLMigration/README.md

Rewrote much of the content for clarity, updated the DevCloud section, corrected some branding, corrected spelling errors, and corrected some formatting.
Fixes Issue# 
N/A

Updated hs opticalflow readme

---

AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/CMakeLists.txt
AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/README.md
AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/include/pointpillars/pointpillars.hpp
AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/src/main.cpp
AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/src/pointpillars/pointpillars.cpp
AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/src/pointpillars/preprocess.cpp

This change implements a set of optimizations to minimize memory copies and API synchronization overhead as described in this SYCLCON 2020 talk (video).
Additionally this updates the sample to OpenVINO 2022.1's runtime API 2.0. It also removes support for host device since all the optimizations rely on a common backend between OpenVINO and SYCL.
Full set of changes:
- Remove host device support
- Re-enable CPU pipeline
- Require OpenVINO 2022.x
- Add support for data path argument
- Share inference output tensors with OneAPI queue.
- Update to OV 2.0 & share input tensors
- Add support for OpenVINO IR & add CLI support
- Update OneAPI & OpenVINO API calls
This change implements a set of optimizations to minimize memory copies and API synchronization overhead as described in this SYCLCON …

OpenVINO 2022.1 and SYCL optimizations

---

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/onchip_memory_cache/README.md
DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/onchip_memory_cache/src/CMakeLists.txt
DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/onchip_memory_cache/src/onchip_memory_cache.cpp
DirectProgramming/DPC++FPGA/Tutorials/Features/private_copies/README.md
DirectProgramming/DPC++FPGA/Tutorials/Features/private_copies/src/CMakeLists.txt
DirectProgramming/DPC++FPGA/Tutorials/Features/private_copies/src/private_copies.cpp
DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/README.md
DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/src/CMakeLists.txt
DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/src/read_only_cache.cpp

This reverts commit 43c2dcb7b405ee1beea1b2ab117591414aabf78f as this was still work in progress and should not have been merged.

Revert #1173 which was not ready to be merged

---

DirectProgramming/C++/GraphTraversal/MergesortOMP/README.md

MergeSort Function Detailing Information Added

MergeSort Function updated in Readmefile

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/README.md

Restructured to match the new template, updated some branding, restructured multiple sections, added information on running in DevCloud, fixed a lot of formatting issues, rewrote some text for clarity, and fixed some grammar/spelling issues.
Fixes Issue# 
N/A

Update QRD FPGA readme

---

DirectProgramming/DPC++FPGA/ReferenceDesigns/qri/README.md

Restructured to match the new template, updated some branding, restructured multiple sections, added information on running in DevCloud, fixed a lot of formatting issues, rewrote some text for clarity, and fixed some grammar/spelling issues.
Fixes Issue# 
N/A

Update fpga qri readme

---

Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/CMakeLists.txt
Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/License.txt
Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/README.md
Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/sample.json
Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/src/1_matrix_mul_null_pointer.cpp
Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/src/2_matrix_mul_multi_offload.cpp
Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/src/3_matrix_mul.cpp
Tools/ApplicationDebugger/guided_matrix_mult_InvalidContexts/CMakeLists.txt
Tools/ApplicationDebugger/guided_matrix_mult_InvalidContexts/License.txt
Tools/ApplicationDebugger/guided_matrix_mult_InvalidContexts/README.md
Tools/ApplicationDebugger/guided_matrix_mult_InvalidContexts/sample.json
Tools/ApplicationDebugger/guided_matrix_mult_InvalidContexts/src/1_matrix_mul_invalid_contexts.cpp
Tools/ApplicationDebugger/guided_matrix_mult_InvalidContexts/src/2_matrix_mul.cpp
Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/CMakeLists.txt
Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/License.txt
Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/README.md
Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/sample.json
Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/src/1_matrix_mul_race_condition.cpp
Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/src/2_matrix_mul.cpp
Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/src/3_matrix_mul.cpp

New guided samples for Intel application debugger.
Administrative
Review

Add new debugger samples

---

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/README.md

Restructured the readme to match the new template. Updated formatting. Updated some branding. Corrected grammar. Expanded information related to running on DevCloud. Changed sample name to match name in sample.json file.
Fixes Issue# 
N/A

Update Compute Units FPGA readme

---

Libraries/oneDNN/tutorials/tutorial_analyze_isa_with_dispatcher_control.ipynb

new feature to add oneDNN AMX ISA analysis
Fixes Issue# 
NA

updates for oneDNN AMX ISA analysis

---

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/explicit_data_movement/README.md

Restructured the readme to match the new template. Updated lots of formatting. Updated some branding. Expanded information related to running on DevCloud. Changed sample name to match name in sample.json file.
Fixes Issue# 
N/A

Update FPGA explicit data movement readme

---

AI-and-Analytics/Features-and-Functionality/IntelPyTorch_Extensions_AutoMixedPrecision/README.md

Fixes Issue# 
Administrative
Review

update broken link

---

AI-and-Analytics/Getting-Started-Samples/README.md

Update README samples list table.
The samples list table and samples were mismatched.

Update samples list

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/dsp_control/README.md

Update README to reflect the actual DSP controls support nowadays.
No code sample source code change.
No compiler change.
- oneAPI Optimization Guide update: https://hsdes.intel.com/appstore/article/#/14018243702
- Regtests update: https://github.com/intel-innersource/applications.fpga.oneapi.products.acl-test/pull/538
- README update
- Regtests: https://spetc.intel.com/testanalysis?trview=0&testRunIds=7350742&tapgsize=1500&tasort=testCasePath&tasortdir=asc

Update dsp_control README

---

AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.ipynb
AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.py
AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/License.txt
AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/README.md
AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/sample.json
AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/third-party-programs.txt

The sample shows how to achieve the same accuracy of the k-NN model classification while using numpy, numba, and numba_dpex.
Administrative
Review

Intel Python Numpy Numba_dpes kNN sample

---

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/onchip_memory_cache/README.md

Updated readme to match new template (with exceptions for FPGA), updated branding, updated some formatting, corrected some grammar.
Fixes Issue# 
N/A

Update onechip memory cache readme

---

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/buffered_host_streaming/src/HostStreamer.hpp

A race condition has been found in this design and this PR addresses it.

FPGA: Fix race condition in the buffered_host_streaming sample

---

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/pipe_array/README.md

Changed the sample name in the readme to match the name in the sample.json file. Restructured the readme to match the new template, with exceptions related to FPGA structure. Corrected formatting. Updated some branding. Rewrote and restructured some sections for clarity.
Fixes Issue# 
N/A

Update FPGA pipe array readme

---

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt

This is not the final seed update of the `gzip` sample for this release, but this will enable the product validation team to test this design properly.

FPGA: update gzip seed

---

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/mvdr_beamforming/README.md

Document that simulator for mvdr_beamforming can take a long time for Questa FE and Questa FSE
Fixes Issue# 
Readme change

Document that simulator for mvdr_beamforming can take a long time

---

release.json

Added release.json file for code samples CI.

Added release.json for samples CI

---

AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/sample.json

Removed Windows from validation step in ciTests field in the sample.json file. For ONSAM-1575.

Removed Windows from ciTests in sample.json

---

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/db/src/dbdata.cpp
DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/CompareGzip.cpp

This PR addresses the Coverity issues flagged on the FPGA part of the code samples.

FPGA: Address Coverity issues

---

Tools/index.html

This is a test of the GPU Occupancy Calculator on GitHub IO Pages

Added GPU Occupancy Calculator

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/matrix_mul/sample.json
Libraries/oneMKL/fourier_correlation/fcorr_1d_buffers.cpp
Libraries/oneMKL/fourier_correlation/fcorr_1d_usm.cpp
Libraries/oneMKL/fourier_correlation/fcorr_2d_usm.cpp

Updated the matrix_mul sample.json to run sample on Windows and removed compile warnings in fourier_correlation.

Removed compiler warnings in fourier_correlation and updated matrix_mul sample.json

---

AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/sample.json

Updated sample.json file for IntelTensorflow_GettingStarted sample to remove "windows" from the os field.

Updated sample.json file for IntelTensorflow_GettingStarted sample

---

DirectProgramming/C++SYCL/StructuredGrids/guided_iso3dfd_GPUOptimization/sample.json

Updated sample.json to use guided_iso3dfd.sln for Windows CI build steps

Updated sample.json to use guided_iso3dfd.sln for Windows CI build steps

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/sample.json
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/sample.json
DirectProgramming/C++SYCL/GraphTraversal/hidden-markov-models/sample.json
DirectProgramming/C++SYCL/Jupyter/cuda-to-sycl-migration-training/sample.json
DirectProgramming/C++SYCL/MapReduce/MonteCarloPi/sample.json
DirectProgramming/C++SYCL/StructuredGrids/iso2dfd_dpcpp/sample.json
DirectProgramming/C++SYCL/StructuredGrids/particle-diffusion/sample.json
Libraries/oneMKL/computed_tomography/sample.json
Libraries/oneMKL/monte_carlo_european_opt/sample.json
Tools/Benchmarks/STREAM/sample.json

GPU required sample.json updates to several code samples for CI testing.

GPU required sample.json updates 

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/sample.json
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/sample.json
DirectProgramming/C++SYCL/GraphTraversal/hidden-markov-models/sample.json
DirectProgramming/C++SYCL/Jupyter/cuda-to-sycl-migration-training/sample.json
DirectProgramming/C++SYCL/MapReduce/MonteCarloPi/sample.json
DirectProgramming/C++SYCL/StructuredGrids/iso2dfd_dpcpp/sample.json
DirectProgramming/C++SYCL/StructuredGrids/particle-diffusion/sample.json
Libraries/oneMKL/computed_tomography/sample.json
Libraries/oneMKL/monte_carlo_european_opt/sample.json
Tools/Benchmarks/STREAM/sample.json

Reverts oneapi-src/oneAPI-samples#1534

Revert "GPU required sample.json updates "

---

Libraries/oneCCL/oneCCL_Getting_Started/sample.json

oneDPL GSG sample.json fixes

---

DirectProgramming/C++SYCL/StructuredGrids/guided_iso3dfd_GPUOptimization/sample.json

Guided_iso3dfd sample.json fix

Guided_iso3dfd sample.json fix

---

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/sample.json

Fixes Issue# 
Administrative
Review

updated product name with correct branding

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/sample.json
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/sample.json
DirectProgramming/C++SYCL/GraphTraversal/hidden-markov-models/sample.json
DirectProgramming/C++SYCL/Jupyter/cuda-to-sycl-migration-training/sample.json
DirectProgramming/C++SYCL/MapReduce/MonteCarloPi/sample.json
DirectProgramming/C++SYCL/StructuredGrids/iso2dfd_dpcpp/sample.json
DirectProgramming/C++SYCL/StructuredGrids/particle-diffusion/sample.json
Libraries/oneMKL/computed_tomography/sample.json
Libraries/oneMKL/monte_carlo_european_opt/sample.json
Tools/Benchmarks/STREAM/sample.json

Added gpuRequired to sample.json for 10 samples that require a specific GPU to run the sample in the samples CI.
- [X} Implement fixes for ONSAM Jiras

Added gpuRequired to sample.json for 10 samples

---

AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/sample.json

Update sample.json to correct product name
Fixes Issue# 
Administrative
Review

Update sample.json to correct product name

---

AI-and-Analytics/Features-and-Functionality/IntelPyTorch_TrainingOptimizations_AMX_BF16/sample.json
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/sample.json
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/sample.json
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/sample.json
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/sample.json
AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/sample.json
AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/sample.json
AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/sample.json
AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/sample.json
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/sample.json

Updated sample names in the sample.json file for 10 samples.

Update sample names in sample.json

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/simple-add/src/CMakeLists.txt
DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/src/CMakeLists.txt

C++SYCL, VecAdd, SimAdd, CMakeLists.txt comments changes
Fixes Issue #1448

C++SYCL, VecAdd, SimAdd, CMakeLists.txt comments changes, fix #1448

---

AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_Performance/IntelPython_XGBoost_Performance.ipynb

To support pandas 2.0 version, Replaced df.append with df.concat
Fixes Issue# 
Administrative …

Replaced df.append with df.concat

---

DirectProgramming/C++/StructuredGrids/iso3dfd_omp_offload/README.md

update README
Fixes Issue #660

C++, iso3dfd, update README.md, fix #660

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ac_int/README.md

Restructured to match the new template, with differences for FPGA templates. Updated name in readme to match name in sample.json. Made minor changes to some formatting. Updated some branding. Added category to sample readme. Corrected some grammar and spelling issues.
Fixes Issue# 
N/A

AC Int sample readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md

Restructured to match the new template, with differences for FPGA templates. Made minor changes to some formatting. Updated some branding. Added category to sample readme. Corrected some grammar and spelling issues.
Fixes Issue# 
N/A

FPGA device_global sample readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/dsp_control/README.md

Restructured to match the new template, with differences for FPGA templates. Made minor changes to some formatting. Updated some branding. Added category to sample readme. Corrected some grammar and spelling issues.
Fixes Issue# 
N/A

FPGA DSP sample readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/invocation_interfaces/README.md
DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/invocation_interfaces/sample.json

Restructured to match the new template, with differences for FPGA templates. Updated sample name case in the sample.json file and readme. Made minor changes to some formatting. Updated some branding. Added category to sample readme. Corrected some grammar and spelling issues.
Fixes Issue# 
N/A

FPGA Invocation Interfaces sample readme

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/latency_control/README.md

Restructured to match the new template, with differences for FPGA templates. Made minor changes to some formatting. Updated some branding. Added category to sample readme. Corrected some grammar and spelling issues.
Fixes Issue# 
N/A

FPGA latency control sample readme

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/kernel_args_restrict/README.md

Restructured to match new template-with adjustments for FPGA samples. Changed the sample name in the readme to match the sample name in the sample.json file. Added category to readme. Updated and corrected some formatting. Updated minor branding issues. Updated example output.
Fixes Issue# 
N/A

FPGA Kernel Args Restrict sample readme

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_fusion/README.md

Restructured to match new template-with adjustments for FPGA samples. Added category to readme. Updated some branding. Corrected some formatting issues.  Corrected some spelling and grammar issues.
Fixes Issue# 
N/A

FPGA loop fusion readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_coalesce/README.md

Restructured to match new template-with adjustments for FPGA samples. Updated sample name in readme to match sample name in sample.json file. Added category to readme. Updated some branding. Corrected some formatting issues.
Fixes Issue# 
N/A

FPGA loop coalesce readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_ivdep/README.md

Restructured to match new template-with adjustments for FPGA samples. Added category to readme. Updated some branding. Corrected some formatting issues. Rewrote copy for clarity.
Fixes Issue# 
N/A

FPGA loop ivdep sample readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/lsu_control/README.md

Restructured to match new template-with adjustments for FPGA samples. Added category to readme. Updated some branding. Corrected some formatting issues. Rewrote copy for clarity. Updated some of the report navigation information in the readme.
Fixes Issue# 
N/A

FPGA LSU control sample readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/max_interleaving/README.md

Restructured to match new template-with adjustments for FPGA samples. Added category to readme. Corrected some formatting issues. Rewrote copy for clarity.
Fixes Issue# 
N/A

FPGA max_interleaving sample readme update

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/02_sycl_dpct_migrated/CMakeLists.txt
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/02_sycl_dpct_migrated/src/jacobi.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/02_sycl_dpct_migrated/src/main.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/03_sycl_migrated/CMakeLists.txt
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/03_sycl_migrated/src/jacobi.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/03_sycl_migrated/src/main.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/04_sycl_migrated_optimized/CMakeLists.txt
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/04_sycl_migrated_optimized/src/jacobi.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/04_sycl_migrated_optimized/src/main.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/README.md
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_SYCLMigration/sample.json

CMakefile change to execute on gpu and cpu seperately. README update.

Jacobi Iterative Sample

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_unroll/README.md

Restructured to match new template-with adjustments for FPGA samples. Updated sample name in readme to match sample name in sample.json file. Added category to readme. Updated some branding. Corrected some formatting issues. Rewrote copy for clarity.
Fixes Issue# 
N/A

FPGA loop unroll sample readme

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/memory_attributes/README.md

Restructured to match new template-with adjustments for FPGA samples. Added category to readme. Changed the sample name in the readme to match the sample name found in the sample.json file. Corrected formatting issues. Corrected some branding issues. Rewrote some copy for clarity and grammar.
Fixes Issue# 
N/A

FPGA Memory Attributes sample readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/optimization_targets/README.md

Restructured to match new template-with adjustments for FPGA samples. Added category to readme. Updated/corrected formatting. Updated some branding. Rewrote some copy for clarity and/or grammar.
Fixes Issue# 
N/A

FPGA optimization targets sample readme update

---

DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/02_sycl_dpct_migrated/CMakeLists.txt
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/02_sycl_dpct_migrated/src/MonteCarloMultiGPU.cpp
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/03_sycl_migrated/CMakeLists.txt
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/03_sycl_migrated/src/MonteCarloMultiGPU.cpp
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/04_sycl_migrated_optimized/CMakeLists.txt
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/04_sycl_migrated_optimized/src/MonteCarloMultiGPU.cpp
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/README.md
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/sample.json

Code is changed to make it work on both CPU and GPU. Change in the CMakeFile to execute on CPU and GPU (including Level-Zero and OpenCL Backend).

MonteCarloMultiGPU Sample

---

Libraries/oneMKL/black_scholes/README.md

Fixes Issue# 
Administrative
Review

Update README.md to better describe HW needs

---

AI-and-Analytics/version_check.py

add version check for Intel ML components
No

add version checks for couple new ML components

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_simpleCudaGraphs_SYCLMigration/sample.json
DirectProgramming/C++SYCL/MapReduce/guided_quasirandomGenerator_SYCLMigration/sample.json
DirectProgramming/C++SYCL/guided_convolutionSeparable_SYCLmigration/sample.json

After adding some samples, the sample aggregator started reporting errors in the validation of sample.json files. In three samples, due to a missing comma, json files turned out to be invali
Fixes Issue# 
https://jira.devtools.intel.com/browse/ONSAM-1601
https://jira.devtools.intel.com/browse/ONSAM-1600
https://jira.devtools.intel.com/browse/ONSAM-1599
Manual testing. Debugging with sample-aggregator

Fix of errors reported by the sample aggregator. Invalid sample.json

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/pipes/README.md

Restructured to match new template-with adjustments for FPGA samples. Updated sample name in readme to match the sample name shown in the sample.json file. Added category to readme. Corrected formatting. Updated some branding. Rewrote some text for clarity and to correct some grammar.
Fixes Issue# 
N/A

FPGA pipes sample readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/printf/README.md

Restructured to match new template-with adjustments for FPGA samples. Updated sample name in readme to match the sample name shown in the sample.json file. Added category to readme. Corrected formatting. Updated some branding. Rewrote some text for clarity and to correct some grammar.
Fixes Issue# 
N/A

FPGA printf sample readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/private_copies/README.md
DirectProgramming/C++SYCL_FPGA/Tutorials/Features/private_copies/sample.json

Restructured to match new template-with adjustments for FPGA samples. Updated sample name in readme and sample name in sample.json file. Added category to readme. Corrected some markdown formatting. Updated some branding. Rewrote some text for clarity and to correct some grammar.
Fixes Issue# 
N/A

FPGA Private copies sample readme update

---

DirectProgramming/C++SYCL/MapReduce/guided_quasirandomGenerator_SYCLMigration/01_dpct_output/CMakeLists.txt
DirectProgramming/C++SYCL/MapReduce/guided_quasirandomGenerator_SYCLMigration/01_dpct_output/Samples/5_Domain_Specific/quasirandomGenerator/quasirandomGenerator.cpp.dp.cpp
DirectProgramming/C++SYCL/MapReduce/guided_quasirandomGenerator_SYCLMigration/02_sycl_migrated_optimized/CMakeLists.txt
DirectProgramming/C++SYCL/MapReduce/guided_quasirandomGenerator_SYCLMigration/02_sycl_migrated_optimized/Samples/5_Domain_Specific/quasirandomGenerator/quasirandomGenerator.cpp.dp.cpp
DirectProgramming/C++SYCL/MapReduce/guided_quasirandomGenerator_SYCLMigration/README.md
DirectProgramming/C++SYCL/MapReduce/guided_quasirandomGenerator_SYCLMigration/sample.json

Updated sample.json and CMakefile change to execute on gpu and cpu seperately. README update.

QuasirandomGenerator Sample

---

DirectProgramming/C++SYCL/guided_concurrentKernels_SYCLMigration/02_sycl_dpct_migrated/CMakeLists.txt
DirectProgramming/C++SYCL/guided_concurrentKernels_SYCLMigration/03_sycl_migrated/CMakeLists.txt
DirectProgramming/C++SYCL/guided_concurrentKernels_SYCLMigration/README.md

CMakefile change to execute on gpu and cpu seperately. README update.

Concurrent Kernel Sample

---

DirectProgramming/C++SYCL/GraphTraversal/guided_odd_even_merge_sort_SYCLMigration/02_sycl_dpct_migrated/CMakeLists.txt
DirectProgramming/C++SYCL/GraphTraversal/guided_odd_even_merge_sort_SYCLMigration/02_sycl_dpct_migrated/src/main.cpp
DirectProgramming/C++SYCL/GraphTraversal/guided_odd_even_merge_sort_SYCLMigration/03_sycl_migrated/CMakeLists.txt
DirectProgramming/C++SYCL/GraphTraversal/guided_odd_even_merge_sort_SYCLMigration/03_sycl_migrated/src/main.cpp
DirectProgramming/C++SYCL/GraphTraversal/guided_odd_even_merge_sort_SYCLMigration/README.md

CMakefile change to execute on gpu and cpu seperately. README update.

Odd even MergeSort Sample

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_PerformanceAnalysis/TF_PerfAnalysis.ipynb

fix missing dataset

---

Libraries/oneMKL/batched_linear_solver/sample.json

Make sample.json file valid for oneMKL batched linear solver code sample
Fixes Issue#ONSAM-1604

Fix sample JSON in oneMKL batched linear solver code sample

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/scheduler_target_fmax/README.md
DirectProgramming/C++SYCL_FPGA/Tutorials/Features/scheduler_target_fmax/sample.json

Restructured to match new template-with adjustments for FPGA samples. Updated sample name in readme and in sample.json file. Added category to readme. Corrected some markdown formatting. Updated some branding. Rewrote some text for clarity and to correct some grammar.
Fixes Issue# 
N/A

FPGA scheduler_target_fmax_mhz sample readme

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/stall_enable/README.md

Restructured to match new template-with adjustments for FPGA samples. Updated name in readme and sample.json file. Added category to readme. Corrected some markdown formatting. Updated some branding. Rewrote some text for clarity and to correct some grammar. Included emulation example outputs to readme.
Fixes Issue# 
N/A

FPGA use_stall_enable_clusters sample readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/speculated_iterations/README.md

Restructured to match new template-with adjustments for FPGA samples. Updated name in readme and sample.json file. Added category to readme. Corrected some markdown formatting. Updated some branding. Rewrote some text for clarity and to correct some grammar.
Fixes Issue# 
N/A

FPGA Speculated Iterations sample readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md

Restructured to match new template – with exceptions for FPGA samples. Restructed build and run instructions for clarity. Updated or fixed formatting issues. Updated some branding. Added category. Rewrote some copy due to some grammar and spelling issues.
Fixes Issue# 
N/A

FPGA Compile sample readme update

---

Libraries/oneDNN/README.md

Added link to onednn product page as requested.
Fixes Issue# 
N/A

Update onednn top readme

---

DirectProgramming/C++SYCL/guided_concurrentKernels_SYCLMigration/README.md
DirectProgramming/C++SYCL/guided_concurrentKernels_SYCLMigration/sample.json

ConcurrentKernel Sample

---

DirectProgramming/C++SYCL/guided_convolutionSeparable_SYCLmigration/sample.json

Convolutionseparable sample

---

DirectProgramming/C++SYCL/GraphTraversal/guided_odd_even_merge_sort_SYCLMigration/sample.json

OddEvenMergeSort Sample

---

DirectProgramming/C++/Jupyter/OpenMP-offload-training/README.md

Restructured to match new template—more or less. Change readme name to match the name of the sample found in the sample.json file. Added category to readme (as indicated in the sample.json file). Corrected some formatting. Updated some branding.
Fixes Issue# 
N/A

OpenMP Offload C++ Tutorials readme update

---

DirectProgramming/C++SYCL/guided_concurrentKernels_SYCLMigration/README.md
DirectProgramming/C++SYCL/guided_concurrentKernels_SYCLMigration/sample.json

Fixed some minor formatting issues. Fixed spacing and spelling issues. Changed the sample name title case and added a space (based on the original sample name on which this sample is based). Updated the sample.json file with the same name change.
Fixes Issue# 
N/A

Concurrent Kernels sample readme update

---

Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/CMakeLists.txt
Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/License.txt
Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/README.md
Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/sample.json
Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/src/a1_matrix_mul_zero_buff.cpp
Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/src/a2_matrix_mul.cpp
Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/src/b1_matrix_mul_null_usm.cpp
Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/src/b2_matrix_mul_usm.cpp
Tools/ApplicationDebugger/guided_matrix_mult_SLMSize/CMakeLists.txt
Tools/ApplicationDebugger/guided_matrix_mult_SLMSize/License.txt
Tools/ApplicationDebugger/guided_matrix_mult_SLMSize/README.md
Tools/ApplicationDebugger/guided_matrix_mult_SLMSize/sample.json
Tools/ApplicationDebugger/guided_matrix_mult_SLMSize/src/1_matrix_mul_SLM_size.cpp
Tools/ApplicationDebugger/guided_matrix_mult_SLMSize/src/2_matrix_mul.cpp

This PR contains two new debug samples, Guided Matrix Bad Buffers and SLM Size.
Administrative
Review

Guided Matrix Multiply Bad Buffers and SLM Size debug samples

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/README.md

Updated structure to match new template. Corrected some formatting. Corrected some branding. Corrected some spelling and grammar issues flagged by automated tools. Added category to readme. Updated information on using DevCloud. 
Fixes Issue# 
N/A

Jacobi Iterative Solver readme update

---

AI-and-Analytics/Jupyter/Predictive_Modeling_Training/README.md
AI-and-Analytics/Jupyter/Predictive_Modeling_Training/sample.json

Removed link references to sample owner's repo, and updated the link references to point to the oneAPI-sample repo instead. Removed sample owner’s name. Updated multiple branding and legal issues. Update some copy for clarity. Corrected formatting issues. Rearranged some sections to match new template structure as much as possible. Added prerequisites information. Updated name in sample.json file to match the name in the readme.
Fixes Issue# 
N/A

Predictive Modeling with XGBoost* and the Intel® AI Analytics Toolkit sample readme update

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/README.md
DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/src/use_library.cpp

Remove a dead comment and add a small note about compilation order
Fixes Issue# n/a
n/a
n/a this is strictly a comments/README change

FPGA: Fix two minor issues with the use_library tutorial

---

AI-and-Analytics/Jupyter/Numba_dpex_Essentials_training/README.md
AI-and-Analytics/Jupyter/Numba_dpex_Essentials_training/sample.json

Updated name in readme. Updated name in sample.json file to match the name in the readme. Removed sample owner’s name from readme. Updated multiple branding and legal issues. Updated some copy for clarity and to correct spelling errors. Added information on three missing directories and notebooks. Corrected formatting issues. Rearranged some sections to match new template structure as much as possible. Added prerequisites information. (Did not update any readme files in subdirectories.)
Fixes Issue# 
N/A

Numba Data Parallel Python* Training Jupyter Notebooks readme update

---

DirectProgramming/Fortran/guided_matrix_mul_OpenMP/README.md

Update file names (created by user in instructions) back to the original.
Fixes Issue# 
File names in README were mistakenly changed. This corrects the file names. 

Update file names to original

---

DirectProgramming/C++SYCL/StructuredGrids/iso2dfd_dpcpp/src/iso2dfd.cpp

Fixes Issue# ONSAM-1614
- [ X] Implement fixes for ONSAM Jiras
- [ X] Visual Studio
To reproduce:
Clone branch and compile/run on visual studio 2022 GUI

Fix to single precision (ONSAM-1614 issue)

---

AI-and-Analytics/Jupyter/Introduction_to_Machine_Learning/README.md
AI-and-Analytics/Jupyter/Introduction_to_Machine_Learning/sample.json

Restructured to match new template-as much as possible. Updated multiple branding and legal issues. Updated some copy for clarity and to correct spelling errors. Corrected formatting issues. Rearranged some sections to match new template structure as much as possible. Added prerequisites information. Expanded information on using samples locally and in DevCloud. Corrected spelling error and branding issues in sample.json description. (Did not update any readme files in subdirectories.)
Fixes Issue# 
N/A

Introduction to Machine Learning readme update

---

AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/INC_QuantizationAwareTraining_TextClassification.ipynb
AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/INC_QuantizationAwareTraining_TextClassification.py
AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/License.txt
AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/README.md
AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/requirements.txt
AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/sample.json

This code sample explains fine-tuning process for multi-class text classification with Intel Neural Compressor Quantization Aware Training 
Administrative
Review

Fine tuning text classification with INC quantization aware training

---

Tools/ApplicationDebugger/array-transform/README.md
Tools/ApplicationDebugger/array-transform/src/array-transform.cpp
Tools/ApplicationDebugger/jacobi/README.md

Clarify the supported platforms in Readme. It is not a stopper change, but would be nice to have it.
@tomlenth FYI

Tools/ApplicationDebugger: update readme

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobiCudaGraphs_SYCLMigration/sample.json

Sample.json fix for Jacobi CUDA Graphs SYCL Migration sample

Fixed sample.json in Jacobi Cuda Graphs SYCL Migration sample

---

DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/02_sycl_migrated/CMakeLists.txt
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/README.md

Revisited MonteCarloMultiGPU sample, and updated CMakeLists.txt with ONEAPI_DEVICE_SELECTOR.

Revisited MonteCarloMultiGPU SYCL Migration Sample

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobiCudaGraphs_SYCLMigration/README.md
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobiCudaGraphs_SYCLMigration/sample.json

Updated the README.md and sample.json files of migrated jacobiCudaGraphs Sample with the latest format changes. 

Jacobi CUDA Graphs sample - updated README.md and sample.json files

---

RenderingToolkit/GettingStarted/02_embree_gsg/sample.json
RenderingToolkit/GettingStarted/04_oidn_gsg/sample.json
RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/sample.json

Updated sample.json for IntroToRayTracingWithEmbree, 02_embree_gsg, 04_oidn_gsg to add GPU support for CI testing.
Fixes Issue#  ONSAM-1620

Updated sample.json for IntroToRayTracingWithEmbree, 02_embree_gsg, 04_oidn_gsg

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/ResNet50_Inference_gpu.ipynb

- Syntax error fix: removed ' character from variable
Bare metal machine and on Developer Cloud

[TensorFlow] Update ResNet50_Inference_gpu

---

DirectProgramming/Fortran/guided_matrix_mul_OpenMP/src/03_mm_GPU.f90

Update 03_mm_GPU.f90 to resolve build error.
This addresses a reported non-zero error code. The update is correcting an inconsistency between source files with single vs double precision.

Update Fortran Matrix multiply with OpenMP sample

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/mem_channel/src/mem_channel.cpp

Tests on Linux: https://spetc.intel.com/testsummary?trview=0&testRunIds=8396870 
HSDES: https://hsdes.intel.com/appstore/article/#/14019878966

Updated return type of get_profiling_info

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Horovod_Distributed_Deep_Learning/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Horovod_Distributed_Deep_Learning/sample.json
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Horovod_Distributed_Deep_Learning/scripts/cl_test.py
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Horovod_Distributed_Deep_Learning/tensorflow_with_horovod.ipynb

The purpose of this sample is to introduce multi-card inference and training for TensorFlow using Intel optimization for Horovod. This sample will guild users how to run Horovod examples on Intel GPU and required modifications to leverage Intel Extension for TenorFlow.
This sample was validated on baremelal machine with ATS-M cards as well as on the new Intel Developer Cloud (IDC) with 4 PVC cards.
Administrative
Review

[New Sample] Multi-card training/inference with Intel Optimization for Horovod + TensorFlow

---

AI-and-Analytics/End-to-end-Workloads/LanguageIdentification/sample.json

Install docker in sample.json file before running docker pull.
None

Lang id docker fix

---

AI-and-Analytics/End-to-end-Workloads/LanguageIdentification/sample.json
AI-and-Analytics/Features-and-Functionality/IntelPyTorch_GPU_InferenceOptimization_with_AMP/IntelPyTorch_GPU_InferenceOptimization_with_AMP.ipynb
AI-and-Analytics/Features-and-Functionality/IntelPyTorch_GPU_InferenceOptimization_with_AMP/IntelPyTorch_GPU_InferenceOptimization_with_AMP.py
AI-and-Analytics/Features-and-Functionality/IntelPyTorch_GPU_InferenceOptimization_with_AMP/License.txt
AI-and-Analytics/Features-and-Functionality/IntelPyTorch_GPU_InferenceOptimization_with_AMP/README.md
AI-and-Analytics/Features-and-Functionality/IntelPyTorch_GPU_InferenceOptimization_with_AMP/ci_test.py
AI-and-Analytics/Features-and-Functionality/IntelPyTorch_GPU_InferenceOptimization_with_AMP/requirements.txt
AI-and-Analytics/Features-and-Functionality/IntelPyTorch_GPU_InferenceOptimization_with_AMP/sample.json
AI-and-Analytics/Features-and-Functionality/IntelPyTorch_GPU_InferenceOptimization_with_AMP/third-party-programs.txt
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Horovod_Distributed_Deep_Learning/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Horovod_Distributed_Deep_Learning/sample.json
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Horovod_Distributed_Deep_Learning/scripts/cl_test.py
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Horovod_Distributed_Deep_Learning/tensorflow_with_horovod.ipynb
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/sample.json
DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/License.txt
DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/Makefile
DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/README.md
DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/sample.json
DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/src/driver.c
DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/src/multiply.c
DirectProgramming/C++/CompilerInfrastructure/guided_matmul_opt_report/src/multiply.h
README.md

This is the PR for the 2023.2 AI Kit release.

2023.2 AI Kit Release

---

AI-and-Analytics/Features-and-Functionality/IntelPytorch_Quantization/sample.json

Added "pip install ipykernel" in sample.json. (Ipykernel is not installed by default in the CI.)
Removed "source activate pytorch" in the sample.json. (Not a valid command in the CI.)
Fixes Issue # ONSAM-1637 

sample.json CI fix for IntelPytroch_Quantization sample

---

AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/sample.json
AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/sample.json

Fix sample.json files for:
* numpy vs numba kNN code sample
* INC quantization aware training code sample
The fix adds missing packages install.
Fixes Issue #ONSAM-1636 #ONSAM-1651

sample.json CI fix for INC quantization aware training and numpy vs numba kNN

---

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/readme.md
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/requirements.txt
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/sample.json

Fix sample.json files for: Intel_Extension_For_SKLearn_GettingStarted
Fixes Issue# 
The fix adds missing packages install.
Fixes Issue #ONSAM-1627 #ONSAM-1648
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Implement fixes for ONSAM Jiras …

sample.json CI fix for sample Intel_Extension_For_SKLearn_GettingStarted

---

DirectProgramming/C++SYCL/GraphTraversal/guided_odd_even_merge_sort_SYCLMigration/sample.json
DirectProgramming/C++SYCL/Jupyter/cuda-to-sycl-migration-training/sample.json
DirectProgramming/C++SYCL/MapReduce/guided_quasirandomGenerator_SYCLMigration/sample.json
DirectProgramming/C++SYCL/guided_convolutionSeparable_SYCLmigration/sample.json
DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/sample.json
DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/sample.json
DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/pipelined_kernels/sample.json

Updated sample.json name field for several samples.

Sample.json name fixes

---

AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_daal4pyPrediction/sample.json

Updated sample.json in IntelPython_XGBoost_daal4pyPrediction sample to install runipy for validating sample in the CI.
Fixes Issue# ONSAM_1647

sample.json CI fix for IntelPython_XGBoost_daal4pyPrediction sample

---

AI-and-Analytics/End-to-end-Workloads/LanguageIdentification/sample.json

Run sh script to launch docker with sudo privileges.
Fixes Issue# ONSAM-1642: https://jira.devtools.intel.com/browse/ONSAM-1642
None

run launch_docker.sh script with sudo privileges (development branch)

---

DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/Makefile

Fixed the gdb module in oneapi_essentials jupyter notebooks. changed makefile from "host" to gpu 
Fixes Issue# 
ONSAM-1625

fixed ONSAM-1625 

---

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/anr/src/anr_params.hpp

FPGA: add a missing header in the ANR sample

---

AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_Performance/IntelPython_XGBoost_Performance.py
AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_Performance/requirements.txt
AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_Performance/sample.json
AI-and-Analytics/Features-and-Functionality/Intel_Extension_For_SKLearn_Performance_SVC_Adult/Intel_Extension_for_SKLearn_Performance_SVC_Adult.py

1. fix pandas API as interfaces changes.
2. fix plot title incorrect message of SKLearn_Performance_SVC_Adult
Fixes Issue# 

Fix ONSAM-1654

---

DirectProgramming/C++SYCL/StructuredGrids/guided_iso3dfd_GPUOptimization/src/1_CPU_only.cpp
DirectProgramming/C++SYCL/StructuredGrids/guided_iso3dfd_GPUOptimization/src/2_GPU_basic.cpp
DirectProgramming/C++SYCL/StructuredGrids/guided_iso3dfd_GPUOptimization/src/3_GPU_linear.cpp
DirectProgramming/C++SYCL/StructuredGrids/guided_iso3dfd_GPUOptimization/src/4_GPU_private_memory_I.cpp
DirectProgramming/C++SYCL/StructuredGrids/guided_iso3dfd_GPUOptimization/src/4_GPU_private_memory_K.cpp
DirectProgramming/C++SYCL/StructuredGrids/guided_iso3dfd_GPUOptimization/src/5_GPU_optimized.cpp

Updated the guided_iso3dfd_GPUOptimization code sample to compile with 2024.0 compiler.
Fixes Issue#  ONSAM-1621, ONSAM-1626.

Updated guided_iso3dfd_GPUOptimization sample to compile with 2024.0

---

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/anr/src/column_stencil.hpp

I changed preprocessor unrolls to `#pragma unroll` when the compiler uses `ivdep(array)`.
Compiler could not achieve II=1 for some loops since `ivdep(array)` could not penetrate lambdas from the unroller.
N/A
Compiles to reporting and simulator with command line. Previously the compilation failed.

FPGA: Change template unrolls to pragma in ANR

---

AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/sample.json

fix ONSAM-1644
Update Intel Neural Compresson sample  sample.json for CI setup environment.
Fixes Issue# 
fix ONSAM-1644
I ran the command in sample.json to setup the environment and run  sample successfully.
#./run_jupyter.sh
In web browser, open the jupyterbook (link output above), 
select the file:  inc_sample_tensorflow.ipynb

Update INC sample sample.json

---

Publications/GPU-Opt-Guide/reduction/reduction_1.cpp
Publications/GPU-Opt-Guide/registers/block-load-store.cpp
Publications/GPU-Opt-Guide/sub-group/sub-group-6.cpp
Publications/GPU-Opt-Guide/sub-group/sub-group-7.cpp

This is backport of gh-1886 to the developent branch.

Use sycl::address_space_cast instead of sycl::multi_ptr constructor

---

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/sample.json

Fixed description in `sample.json` file. Refer [this](https://jira.devtools.intel.com/projects/ONSAM/issues/ONSAM-1558?filter=allopenissues) for details.

update description in ITEX sample.json

---

DirectProgramming/C++/GraphTraversal/MergesortOMP/Makefile
DirectProgramming/C++SYCL/DenseLinearAlgebra/complex_mult/Makefile
DirectProgramming/C++SYCL/SpectralMethods/guided_OceanFFT_SYCLMigration/sample.json
DirectProgramming/C++SYCL/guided_concurrentKernels_SYCLMigration/sample.json
DirectProgramming/C++SYCL/guided_convolutionSeparable_SYCLmigration/sample.json

Updated Makefiles for MergesortOMP and complex_mult samples.
Updated sample.json files for OceanFFT, concurrentKernels, convolutionSeparable SYCL migration samples.

Fixes for 2024.0

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/sample.json
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/scripts/ci_test.py

fixed [JIRA issue](https://jira.devtools.intel.com/browse/ONSAM-1640).

fixed IntelTensorFlow_InferenceOptimization "no such file or directory" error

---

AI-and-Analytics/Features-and-Functionality/IntelPyTorch_Extensions_Inference_Optimization/scripts/ci_test.py

fixed [this](https://jira.devtools.intel.com/browse/ONSAM-1641) issue.

Fixed IntelPyTorch_Extensions_Inference_Optimization "no such file or directory" error

---

DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/CPP_SYCL_Introduction.ipynb
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/lab/cpp_compute.cpp
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/lab/onedpl_compute_offload.cpp
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/lab/sycl_compute_offload.cpp
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/lab/sycl_compute_offload_parallelism.cpp
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/lab/sycl_vector_add.cpp
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/run_cpp_compute.sh
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/run_onedpl_compute_offload.sh
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/run_sycl_compute_offload.sh
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/run_sycl_compute_offload_parallelism.sh
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/run_sycl_vector_add.sh
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/src/cpp_compute.cpp
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/src/onedpl_compute_offload.cpp
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/src/sycl_compute_offload.cpp
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/src/sycl_compute_offload_parallelism.cpp
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/src/sycl_vector_add.cpp

Added CPP to SYCL examples in oneAPI Intro module, notebook and 4 examples
NA

updated Jupyter with CPP_SYCL Intro

---

DirectProgramming/C++SYCL/Jupyter/gpu-optimization-sycl-training/03_Memory_Optimization/03_Memory_Optimization.ipynb

Updated text in GPU Opt notebook module 03 and removed gen9 as default execution
NA

Updated text in GPU Opt notebook module 03

---

Libraries/oneDPL/maxloc_reductions/maxloc_operator.cpp

The maxloc_operator.cpp example in oneAPI-samples/Libraries/oneDPL/maxloc_reductions was modified to comply with the SYCL 2020 changes to sycl::maximum.
Fixes Issue# 
The changes to the SYCL 2020 specification and the example code are described in CMPLRLLVM-50960 (https://jira.devtools.intel.com/browse/CMPLRLLVM-50960).

Update the maxloc operator example to comply with SYCL 2020

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning/scripts/ci_test.py

fix [ONSAM-1638](https://jira.devtools.intel.com/browse/ONSAM-1638) JIRA issue

fixed IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning "no such file or directory" error

---

AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/sample.json
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning/scripts/ci_test.py

Fixed [ONSAM-1639](https://jira.devtools.intel.com/browse/ONSAM-1639)

Fixed IntelPytorch_Interactive_Chat_Quantization "no such file or directory" error

---

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/requirements.txt
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/sample.json
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/scripts/ci_test.py

Change sample.json for CI issue
Fixes Issue# 
https://jira.devtools.intel.com/browse/ONSAM-1645

[ITEX GSG sample] [ONSAM-1645]Create requirements.txt and Update sample.json

---

DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/01_oneAPI_Intro/CPP_SYCL_Introduction.ipynb

updated build/run cmd in Jupyter notebook to work on new devcloud
Fixes Issue# 
NA

updated build/run cmd in Jupyter notebook

---

DirectProgramming/C++SYCL/CombinationalLogic/sepia-filter/sample.json

Sample.json fix for sepia-filter

Sample.json fix for sepia-filter

---

DirectProgramming/C++SYCL/ParallelPatterns/loop-unroll/sample.json

Sample.json fix for loop-unroll

Sample.json fix for loop-unroll

---

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/sample.json

The sample.json of this sample was not updated when the cmake structure was modified.

FPGA: fix component interfaces comparison sample.json

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning/sample.json

Standardized calls to setvars.sh, ipykernel, and conda activation. Refer [ONSAM-1638](https://jira.devtools.intel.com/browse/ONSAM-1638)

IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning (ONSAM-1638)

---

AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/sample.json

Added a step to install `transformers`. Refer (ONSAM-1639)[https://jira.devtools.intel.com/browse/ONSAM-1639]

IntelPytorch_Interactive_Chat_Quantization (ONSAM-1639)

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/sample.json

updated `sample.json` to run setvars.sh before all other steps. Refer [ONSAM-1640](https://jira.devtools.intel.com/browse/ONSAM-1640)

IntelTensorFlow_InferenceOptimization (ONSAM-1640)

---

AI-and-Analytics/Features-and-Functionality/IntelPyTorch_Extensions_Inference_Optimization/sample.json

updated calls to setvars.sh script, python for ipykernel, and conda venv activation. Refer [ONSAM-1641](https://jira.devtools.intel.com/browse/ONSAM-1641)

IntelPyTorch_Extensions_Inference_Optimization (ONSAM-1640)

---

AI-and-Analytics/Jupyter/Predictive_Modeling_Training/Makefile
AI-and-Analytics/Jupyter/Predictive_Modeling_Training/sample.json

created make file & updated sample.json. Refer [ONSAM-1632](https://jira.devtools.intel.com/browse/ONSAM-1632)

Predictive_Modeling_Training (ONSAM-1632)

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/sample.json
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/scripts/ci_test.py

replaced runipy with jupyter execute API. Refer [ONSAM-1697](https://jira.devtools.intel.com/browse/ONSAM-1697)

IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8 (ONSAM-1697)

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Horovod_Distributed_Deep_Learning/sample.json

fixed ipykernel error and other minor changes. Refer [ONSAM-1635](https://jira.devtools.intel.com/browse/ONSAM-1635)

IntelTensorflow_Horovod_Distributed_Deep_Learning (ONSAM-1635)

---

Libraries/oneMKL/fourier_correlation/makefile

Fix for PR-1688

---

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/sample.json
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/scripts/ci_test.py

update sample.json to test for both CPU & GPU. Refer [ONSAM-1696](https://jira.devtools.intel.com/browse/ONSAM-1696)

Intel_Extension_For_TensorFlow_GettingStarted (ONSAM-1696)

---

Libraries/oneDPL/gamma-correction/gamma-correction.vcxproj
Libraries/oneTBB/tbb-async-sycl/tbb-async-sycl.vcxproj
Libraries/oneTBB/tbb-resumable-tasks-sycl/tbb-resumable-tasks-sycl.vcxproj
Libraries/oneTBB/tbb-task-sycl/tbb-task-sycl.vcxproj

Modified oneTBB and oneDPL Windows samples to use setvars.bat

---

AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/CMakeLists.txt
AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/get_dependencies.sh
AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/sample.json
AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/src/pointpillars/pointpillars.cpp

Updated the PointPillars sample to build and run in the CI system.
Fixes Issue# ONSAM-1698

Updated PointPillars sample to compile in the CI system.

---

DirectProgramming/C++/StructuredGrids/iso3dfd_omp_offload/README.md

Fixes Issue# 
Administrative
Review

update iso_omp links in Workflow section of README

---

Tools/VTuneProfiler/tachyon/sample.json
Tools/VTuneProfiler/tachyon/windows/msvs/build_serial.vcxproj
Tools/VTuneProfiler/tachyon/windows/msvs/build_with_openmp.vcxproj
Tools/VTuneProfiler/tachyon/windows/msvs/build_with_openmp_optimized.vcxproj
Tools/VTuneProfiler/tachyon/windows/msvs/build_with_tbb.vcxproj
Tools/VTuneProfiler/tachyon/windows/msvs/build_with_tbb_optimized.vcxproj
Tools/VTuneProfiler/tachyon/windows/msvs/tachyon.vcxproj

Fixes for Tachyon VTune sample.

Fixes for tachyon

---

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/README.md

updated ITEX sample for AI Kit name changes.
Fixes Issue# ONSAM-1716
No

ITEX sample update for AI Kit product name change

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/ResNet50_Inference.ipynb
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/ResNet50_Inference_gpu.ipynb

updated Model Zoo sample for AI Kit and Model Zoo name changes.
Fixes Issue# ONSAME-1716
NA

Model Zoo updates for product name changes

---

AI-and-Analytics/Getting-Started-Samples/IntelAIKitContainer_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelAIKitContainer_GettingStarted/run_oneapi_docker.sh

Changes for AI Tools Docker images
https://cqpreview.intel.com/content/www/us/en/test/idz/barbs-test-folder/uswd-work/ai-tools-gold.html
Fixes Issue# 
NA

Changes for AI Tools Docker images

---

AI-and-Analytics/End-to-end-Workloads/README.md
AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/INC_QuantizationAwareTraining_TextClassification.ipynb
AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/INC_QuantizationAwareTraining_TextClassification.py
AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/requirements.txt
AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/sample.json
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/ResNet50_Inference.ipynb
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/ResNet50_Inference_gpu.ipynb
AI-and-Analytics/Features-and-Functionality/README.md
AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/README.MD
AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/README.md
AI-and-Analytics/Getting-Started-Samples/IntelAIKitContainer_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelAIKitContainer_GettingStarted/run_oneapi_docker.sh
AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelModin_Vs_Pandas/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_oneCCL_Bindings_For_PyTorch_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/README.md
AI-and-Analytics/README.md

AI README.md Updates

---

Libraries/oneDPL/dynamic_selection/nstream/sample.json
Libraries/oneMKL/matrix_mul_mkl/sample.json

Fixes Issue# ONSAM-1722 and ONSAM-1723

Fixes for ONSAM-1722 and ONSAM-1723

---

Libraries/oneDPL/dynamic_selection/nstream/sample.json
Libraries/oneMKL/matrix_mul_mkl/sample.json
RenderingToolkit/GettingStarted/03_openvkl_gsg/sample.json

Jira fixes

---

AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/sample.json

Refer issue [ONSAM-1644](https://jira.devtools.intel.com/browse/ONSAM-1644) for details.

updated sample.json

---

DirectProgramming/C++SYCL/GraphTraversal/radix_sort_thrust_migrated/02_sycl_dpct_migrated/src/radixSortMigrated.cpp

Radix Sort Sycl migrated source code.
Removed Cuda Functions from source code

Radix sort migrated source code- cuda API removed

---

DirectProgramming/Fortran/DenseLinearAlgebra/vectorize-vecmatmult/README.md

Refer [ONSAM-1518](https://jira.devtools.intel.com/projects/ONSAM/issues/ONSAM-1518)

updated OS to linux

---

DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/gamma-correction/gamma-correction.vcxproj
Libraries/oneTBB/tbb-async-sycl/tbb-async-sycl.vcxproj
Libraries/oneTBB/tbb-resumable-tasks-sycl/tbb-resumable-tasks-sycl.vcxproj
Libraries/oneTBB/tbb-task-sycl/tbb-task-sycl.vcxproj

Cleaned up VS project files for TBB samples and gamma-correction

Cleaned up VS project files for TBB samples and gamma-correction

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobiCudaGraphs_SYCLMigration/02_sycl_migrated/Samples/3_CUDA_Features/jacobiCudaGraphs/jacobi.dp.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobiCudaGraphs_SYCLMigration/02_sycl_migrated/Samples/3_CUDA_Features/jacobiCudaGraphs/main.cpp.dp.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobiCudaGraphs_SYCLMigration/03_sycl_migrated_optimized/Samples/3_CUDA_Features/jacobiCudaGraphs/jacobi.dp.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobiCudaGraphs_SYCLMigration/03_sycl_migrated_optimized/Samples/3_CUDA_Features/jacobiCudaGraphs/main.cpp.dp.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobiCudaGraphs_SYCLMigration/README.md
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobiCudaGraphs_SYCLMigration/sample.json

Updated sample with changes applicable to oneAPI 2024.0 release, updated README.md and code files.

JacobiCUDAGraph SYCL Migration sample - 2024.0 update

---

DirectProgramming/C++SYCL/CombinationalLogic/mandelbrot/README.md
DirectProgramming/C++SYCL/CombinationalLogic/sepia-filter/README.md
DirectProgramming/C++SYCL/DenseLinearAlgebra/complex_mult/README.md
DirectProgramming/C++SYCL/DenseLinearAlgebra/matrix_mul/README.md
DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/README.md
DirectProgramming/C++SYCL/GraphAlgorithms/all-pairs-shortest-paths/README.md
DirectProgramming/C++SYCL/GraphTraversal/bitonic-sort/README.md
DirectProgramming/C++SYCL/GraphTraversal/hidden-markov-models/README.md
DirectProgramming/C++SYCL/Jupyter/cuda-to-sycl-migration-training/sample.json
DirectProgramming/C++SYCL/Jupyter/gpu-optimization-sycl-training/sample.json
DirectProgramming/C++SYCL/MapReduce/MonteCarloPi/README.md
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/sample.json
DirectProgramming/C++SYCL/N-BodyMethods/Nbody/README.md
DirectProgramming/C++SYCL/ParallelPatterns/PrefixSum/README.md
DirectProgramming/C++SYCL/ParallelPatterns/loop-unroll/README.md
DirectProgramming/C++SYCL/SparseLinearAlgebra/merge-spmv/README.md
DirectProgramming/C++SYCL/SpectralMethods/DiscreteCosineTransform/README.md
DirectProgramming/C++SYCL/StructuredGrids/1d_HeatTransfer/README.md
DirectProgramming/C++SYCL/StructuredGrids/iso2dfd_dpcpp/README.md
DirectProgramming/C++SYCL/StructuredGrids/iso3dfd_dpcpp/README.md
Libraries/oneDPL/dynamic_selection/nstream/README.md
Libraries/oneDPL/dynamic_selection/sepia-filter-ds/README.md
Libraries/oneDPL/gamma-correction/README.md
Libraries/oneTBB/tbb-async-sycl/README.md
Libraries/oneTBB/tbb-resumable-tasks-sycl/README.md
Libraries/oneTBB/tbb-task-sycl/README.md

Code sample README Updates carried over from 2024.0_updates branch.

README Updates

---

Libraries/oneDNN/tutorials/sample.json

fixed sample.json file. Refer [ONSAM-1784](https://jira.devtools.intel.com/browse/ONSAM-1784)

Libraries tutorials sample failed due to JSONDecodeError (ONSAM-1784)

---

DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/02_sycl_migrated/Samples/5_Domain_Specific/MonteCarloMultiGPU/MonteCarloMultiGPU.cpp.dp.cpp
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/02_sycl_migrated/Samples/5_Domain_Specific/MonteCarloMultiGPU/MonteCarlo_kernel.dp.cpp
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/README.md
DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/sample.json

Re-tested with oneAPI 2024.0.0.
Removed checkCudaErrors from migrated source code.
Updated the Readme.

Updated MonteCarloMultiGPU- oneAPI 2024.0

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/sample.json

Update sample.json for vector-add to work with Eclipse.

Update sample.json for vector-add to work with Eclipse

---

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/sample.json

Fixed python path. Refer [ONSAM-1776](https://jira.devtools.intel.com/browse/ONSAM-1776)

AI-KIT Intel_Extension_For_PyTorch_GettingStarted [ONSAM-1776]

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_simpleCudaGraphs_SYCLMigration/02_sycl_migrated/Samples/3_CUDA_Features/simpleCudaGraphs/simpleCudaGraphs.dp.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_simpleCudaGraphs_SYCLMigration/README.md
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_simpleCudaGraphs_SYCLMigration/sample.json

Updated sample with changes applicable to oneAPI 2024.0 release, updated README.md.

SimpleCUDAGraph SYCL Migration sample - 2024.0 update

---

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/niosv/software/simple_dma_test/src/simple_dma_test.c

improve commenting in Nios® V softcore processor code and add volatile keyword to pointer accesses to make them proof against future user modifications.
Fixes Issue# 
⚠️ Note: I did not run the regtest since I didn't change any of the SYCL code and the local command-line checks passed.

add some comments and make all pointer accesses volatile

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/tutorial_optimize_TensorFlow_pretrained_model.ipynb

error handling for empty throughput list
Error handling for empty throughput lise
Fixes Issue# onsam-1824
NA

Error handling

---

AI-and-Analytics/End-to-end-Workloads/LanguageIdentification/sample.json

updated sample.json to skip execution in CI. Refer [this](https://jira.devtools.intel.com/browse/ONSAM-1765)

AI-KIT LanguageIdentification sample failed due to "No such file or directory" error [ONSAM-1765]

---

Libraries/MPI/jacobian_solver/src/01_jacobian_host_mpi_one-sided/mpi3_onesided_jacobian.c
Libraries/MPI/jacobian_solver/src/02_jacobian_device_mpi_one-sided_gpu_aware/mpi3_onesided_jacobian_gpu_openmp.c
Libraries/MPI/jacobian_solver/src/02_jacobian_device_mpi_one-sided_gpu_aware/mpi3_onesided_jacobian_gpu_sycl.cpp
Libraries/MPI/jacobian_solver/src/03_jacobian_device_mpi_one-sided_device_initiated/mpi3_onesided_jacobian_gpu_sycl_device_initiated.cpp
Libraries/MPI/mpi_send_gpu/src/mpi_send_gpu_sycl.cpp

Fix ONSAM-1721
Fixes Issue# Fix ONSAM-1721
None

Fix ONSAM-1721

---

AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/README.MD

The purpose is to show how the new README template can be applied to one of AI samples to see how it works and get a sign-off from TCE. 
- gaps in AI sample READMEs
- inconsistency between AI sample READMEs
Not tested
- TCE Louie @louie-tsai 
- Samples team Jimmy @jimmytwei 
- DX Isha @ishaghosh27 Tom @tomlenth

Applying new template to one AI Getting Started sample

---

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/convolution2d/CMakeLists.txt

Reverts oneapi-src/oneAPI-samples#2205

Revert "FPGA: rename target name in the `convolution` sample"

---

AI-and-Analytics/Getting-Started-Samples/Intel_oneCCL_Bindings_For_PyTorch_GettingStarted/README.md

update readme according to UX team's request

Update Torch-ccl get started README.md according to UX team's request

---

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/README.md

Update IPEX Getting Started README according to UX team's request

update README according to template

---

AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.ipynb
AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.py

Update the code sample to reflect the newest numba-dpex API.
Fixes Issue#ONSAM-1854
Testen on GTA-X machine and Intel Developer Cloud

[ONSAM-1854] Fix for IntelPython_Numpy_Numba_dpex_kNN failure development branch

---

AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.ipynb
AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.py

Update the code sample to reflect the newest numba-dpex API.
Fixes Issue#ONSAM-1854
Testen on GTA-X machine and Intel Developer Cloud

[ONSAM-1854] Fix for IntelPython_Numpy_Numba_dpex_kNN failure release branch

---

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/README.md

Update the ITEX Getting Started README based on the template as request.

Modify the ITEX sample README based on the template

---

AI-and-Analytics/Getting-Started-Samples/IntelModin_Vs_Pandas/README.md

template 2024.1 Modin vs Pandas

---

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/readme.md

template 2024.1 changes by Stefana Raileanu

sklearnex template 2024.1

---

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/scripts/profile_utils.py

remove TF estimator codes since it is deprecated and replaced by keras API
https://www.tensorflow.org/guide/migrate/migrating_estimator
Fixes Issue# ONSAM-1862
NA

remove TF estimator since it is deprecated

---

Tools/GPU-Occupancy-Calculator/index.html

added new hw configs "RPL" to Occupancy Calculator

added new hw configs to Occupancy Calculator

---

src/db.py
src/docs/_static/sample_db_prd.json
src/docs/_static/script.js
src/docs/_static/styles.css
src/docs/_templates/base.html
src/docs/_templates/index.html

Revises db.py to include truncate_text() func and recreates sample_db_prd.json

App/dev test, WW14.4

---

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/ResNet50_Inference.ipynb
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/run.sh

updated run commands for 2024.1
Fixes Issue# ONSAM-1867
NA

ONSAM 1867 - updated run command for 2024.1

---

AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/README.md
AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/requirements.txt
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/requirements.txt
AI-and-Analytics/Getting-Started-Samples/Intel_oneCCL_Bindings_For_PyTorch_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_oneCCL_Bindings_For_PyTorch_GettingStarted/requirements.txt

add requirements file for samples
Fixes Issue# ONSAM 1884
List any external dependencies created as a result of this change.NA

ONSAM 1884 - add requirements file for samples

---

AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/README.MD
AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/readme.md
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_oneCCL_Bindings_For_PyTorch_GettingStarted/README.md

Fixes typo in Git clone instructions.
Fixes Issue# 
ONSAM-1865

Git clone readme update

---

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/convolution2d/README.md
DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/convolution2d/quartus_project_files/software/oneapi_2dconvolution.hpp
DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/convolution2d/src/convolution_kernel.hpp
DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/convolution2d/src/main.cpp

Fix some bugs that emerged due to compiler update
Fixes Issue# 
https://hsdes.intel.com/appstore/article/#/14022071606 (compiler update)
https://hsdes.intel.com/appstore/article/#/14022085545 (code sample coding error)

FPGA: Fix conv2d CSR errors

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/matrix_mul/src/matrix_mul_omp.cpp

Updated matrix_mul_omp.cpp with #pragma omp parallel.
Fixes Issue# ONSAM-1928

Update matrix_mul_omp.cpp with #pragma omp parallel

---

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/convolution2d/README.md

Update readme with latest qor numbers

FPGA: Update QoR numbers for the Convolution sample

---

Tools/GPU-Occupancy-Calculator/README.md
Tools/GPU-Occupancy-Calculator/index.html

updated GPU Occupancy Calculator - added new GPUs, updated calculator UI, added help section

updated GPU Occupancy Calculator

---

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/cholesky/README.md
DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/cholesky_inversion/README.md
DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/mvdr_beamforming/README.md
DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/pca/README.md
DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/qrd/README.md
DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/qri/README.md

Update the readme for the code samples that may crash with the 2024.2 release.

FPGA: Update README for code samples that are affected by crash

---

Libraries/oneMKL/guided_simpleCUBLAS_LU_SYCLMigration/sample.json

fixed **categories** field in sample.json file for simpleCUBLAS sample
tested manually with local sample-aggregator

Updated simpleCUBLAS sample.json to match the schema

---

Tools/ApplicationDebugger/guided_matrix_mult_SLMSize/README.md

Changes in the toolkits and compiler result in new messages in the debug scenario presented in this sample. The README.md file has been cleaned up to reflect those changes in the compiler and other tools.
Fixes Issue# 
ONSAM-1873: "Guided Matrix Multiplication Illegal SLM Size Sample no longer gives expected output"
None.
Impacts the README.md file, only. No changes in the sample code.

update guided matrix mult slm size README instructions

---

Tools/OpenACCToOpenMP/guided_MonteCarloMultiGPU_OpenMPMigration/License.txt
Tools/OpenACCToOpenMP/guided_MonteCarloMultiGPU_OpenMPMigration/Makefile
Tools/OpenACCToOpenMP/guided_MonteCarloMultiGPU_OpenMPMigration/README.md
Tools/OpenACCToOpenMP/guided_MonteCarloMultiGPU_OpenMPMigration/openMP_migrated_output/MonteCarloMultiGPU.c.report
Tools/OpenACCToOpenMP/guided_MonteCarloMultiGPU_OpenMPMigration/openMP_migrated_output/MonteCarloMultiGPU_translated.c
Tools/OpenACCToOpenMP/guided_MonteCarloMultiGPU_OpenMPMigration/sample.json
Tools/OpenACCToOpenMP/guided_MonteCarloMultiGPU_OpenMPMigration/third-party-programs.txt
Tools/OpenACCToOpenMP/guided_bilateralfilter_OpenMPMigration/License.txt
Tools/OpenACCToOpenMP/guided_bilateralfilter_OpenMPMigration/Makefile
Tools/OpenACCToOpenMP/guided_bilateralfilter_OpenMPMigration/README.md
Tools/OpenACCToOpenMP/guided_bilateralfilter_OpenMPMigration/openMP_migrated_output/bilateralFilter.c.report
Tools/OpenACCToOpenMP/guided_bilateralfilter_OpenMPMigration/openMP_migrated_output/bilateralFilter_translated.c
Tools/OpenACCToOpenMP/guided_bilateralfilter_OpenMPMigration/sample.json
Tools/OpenACCToOpenMP/guided_bilateralfilter_OpenMPMigration/third-party-programs.txt

Added two new samples bilateralfilter and MontecarloMultiGPU which are migrated using the tool [intel-application-migration-tool-for-openacc-to-openmp](https://github.com/intel/intel-application-migration-tool-for-openacc-to-openmp)
Administrative
Review

Adding 2 new openACC-openMP migrated samples

---

DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/14_SYCL_Multi_GPU_Programming/SYCL_Multi_GPU_Programming.ipynb
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/14_SYCL_Multi_GPU_Programming/lab/multi_gpu_mm.cpp
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/14_SYCL_Multi_GPU_Programming/lab/multi_gpu_vadd_split.cpp
DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/14_SYCL_Multi_GPU_Programming/src/multi_gpu_vadd_split.cpp

minor fixes to multi-gpu training, updated to support 8 GPUs in new IDC

minor fixes to multi-gpu training

---

DirectProgramming/C++SYCL/Jupyter/cuda-to-sycl-migration-training/TeacherKit.ipynb
DirectProgramming/C++SYCL/Jupyter/cuda-to-sycl-migration-training/Welcome.ipynb

There are some DOC which was having rendering issue in GitHub. 
Now it has been fixed.

Jupyter Doc formatting was not correct

---

Tools/VTuneProfiler/matrix_multiply_vtune/README.md

Updating README on Matrix_Multiply_Vtune Sample with clear instruction on building & running the sample. 
Fixes Issue# ONSAM-1994
None

Update How to Run Matrix_Multiply_VTune Sample in README (dev)

---

Tools/VTuneProfiler/matrix_multiply_vtune/README.md

Updating README on Matrix_Multiply_Vtune Sample with clear instruction on building & running the sample.
Fixes Issue# ONSAM-1994
None

Update how to run Matrix_Multiply_VTune Sample in README (rel)

---

Libraries/oneMKL/monte_carlo_european_opt/src/montecarlo_main.cpp

It was found that only oneMKL RNG Device API random engines are changing by `USE_*` macros. It would be better if we also change Host API random engines.

[oneMKL] Let's also change RNG Host API engines when an engines' macro is switched one

---

Libraries/oneMKL/binomial/src/binomial_sycl.cpp
Libraries/oneMKL/block_cholesky_decomposition/factor.cpp
Libraries/oneMKL/block_cholesky_decomposition/solve.cpp
Libraries/oneMKL/block_lu_decomposition/factor.cpp
Libraries/oneMKL/block_lu_decomposition/solve.cpp
Libraries/oneMKL/computed_tomography/computed_tomography.cpp
Libraries/oneMKL/monte_carlo_pi/mc_pi.cpp
Libraries/oneMKL/monte_carlo_pi/mc_pi_device_api.cpp
Libraries/oneMKL/monte_carlo_pi/mc_pi_usm.cpp
Libraries/oneMKL/random_sampling_without_replacement/lottery.cpp
Libraries/oneMKL/random_sampling_without_replacement/lottery_device_api.cpp
Libraries/oneMKL/random_sampling_without_replacement/lottery_usm.cpp
Libraries/oneMKL/sparse_conjugate_gradient/sparse_cg.cpp
Libraries/oneMKL/student_t_test/t_test.cpp
Libraries/oneMKL/student_t_test/t_test_usm.cpp

Fixed SYCL 2020 deprecation warnings for oneMKL Samples

[oneMKL] Fixed deprecation warnings

---

Libraries/oneMKL/binomial/src/binomial_main.cpp
Libraries/oneMKL/black_scholes/src/black_scholes.hpp
Libraries/oneMKL/monte_carlo_european_opt/src/montecarlo.hpp

Added exit codes to some samples

[oneMKL] Added exit codes to some samples

---

Tools/OpenACCToOpenMP/guided_Atomic_OpenMPMigration/License.txt
Tools/OpenACCToOpenMP/guided_Atomic_OpenMPMigration/Makefile
Tools/OpenACCToOpenMP/guided_Atomic_OpenMPMigration/README.md
Tools/OpenACCToOpenMP/guided_Atomic_OpenMPMigration/openMP_migrated_output/atomic.c.report
Tools/OpenACCToOpenMP/guided_Atomic_OpenMPMigration/openMP_migrated_output/atomic_translated.c
Tools/OpenACCToOpenMP/guided_Atomic_OpenMPMigration/sample.json
Tools/OpenACCToOpenMP/guided_Atomic_OpenMPMigration/third-party-programs.txt

Added a new OpenMP Atomic sample which is migrated using the tool [intel-application-migration-tool-for-openacc-to-openmp](https://github.com/intel/intel-application-migration-tool-for-openacc-to-openmp)
Administrative
Review

Adding openmp Atomic sample to openACCtoOpenMP tools folder

---

Libraries/oneDPL/pSTL_offload/ParSTLTests/CMakeLists.txt
Libraries/oneDPL/pSTL_offload/ParSTLTests/main.cpp
Libraries/oneDPL/pSTL_offload/README.md

Description: 
This sample provides a comprehensive benchmark of various C++ Standard Template Library (STL) algorithms by leveraging different execution policies (std::execution::seq, std::execution::par, and std::execution::par_unseq). It aims to showcase the performance implications of these execution policies when applied to large data sets.

Add Sample for PSTL Functionality Demonstrating Performance of Various C++ STL Algorithms

---

Publications/GPU-Opt-Guide/conditionals/convolution-global-conditionals-min-max.cpp
Publications/GPU-Opt-Guide/conditionals/convolution-global-conditionals.cpp

Fixed ONSAM-1953. Please also see [CMPLRLLVM-61903](https://jira.devtools.intel.com/browse/CMPLRLLVM-61903) for details.
Fixes Issue# 
ONSAM-1953
None

Fix ONSAM-1953

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/1_guided_jacobi_iterative_solver_cpu.cpp
DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/3_guided_jacobi_iterative_solver_multi_gpu.cpp
DirectProgramming/C++SYCL/StructuredGrids/iso2dfd_dpcpp/src/iso2dfd.cpp
DirectProgramming/C++SYCL/StructuredGrids/iso3dfd_dpcpp/src/iso3dfd_kernels.cpp
DirectProgramming/C++SYCL/StructuredGrids/iso3dfd_dpcpp/src/utils.cpp
DirectProgramming/C++SYCL/StructuredGrids/particle-diffusion/src/motionsim_kernel.cpp

Fix for two ONSAM JIRA tickets
Fixes Issue# 1868 and 1869
The test has been ran for all impacted samples using the 2025.0.0 (2025.0.0.20240806) version of the compiler

Fix for ONSAM 1868 and 1869

---

Libraries/MPI/jacobian_solver/src/include/common.h

[ONSAM-2023]: added missed header file

---

DirectProgramming/Python/DPNP_GettingStarted/License.txt
DirectProgramming/Python/DPNP_GettingStarted/README.md
DirectProgramming/Python/DPNP_GettingStarted/cg.py
DirectProgramming/Python/DPNP_GettingStarted/sample.json
DirectProgramming/Python/DPNP_GettingStarted/third-party-programs.txt

The `Intel® Python DPNP Getting Started` sample code shows how to find conjugate gradient using the Intel Python dpnp package.
Administrative
Review

Intel Python DPNP Getting Started

---

DirectProgramming/C++SYCL/SYCLMigration/guided_segmentationTree_SYCLMigration/02_sycl_migrated/include/dpct/dpl_extras/dpcpp_extensions.h

Fix for ONSAM 2027
Fixes Issue# 
ONSAM 2027

Fix ONSAM 2027

---

DirectProgramming/C++SYCL/SYCLMigration/guided_radixSortThrust_SYCLMigration/02_sycl_dpct_migrated/include/dpct/dpl_extras/dpcpp_extensions.h

Fix for onsam_2026
Fixes Issue#  onsam_2026

Fix_for_onsam_2026

---

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/svd/src/memory_transfers.hpp
DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/svd/src/svd.hpp

There was a functional change that went into the compiler recently that means it will now correctly identify memory dependences. One of the results of this is that this design will now emit a message that it is unable to achieve a user specified II. 
To regain this performance we can use annotated_ptr's in the SYCL HLS flow to specify a larger interface width which will allow for the compiler to coalesce stores to memory, thus resulting in being able to achieve the user specified II again.
This change also corrects the address space of a call to `device_ptr`
* N/A
* Manually ran the full-system and IPA flows through …

FPGA: Fix II error and update namespace for device_ptr

---

DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/lab/mm_dpcpp_basic_full.cpp
DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/lab/mm_dpcpp_common.cpp
DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/lab/mm_dpcpp_common_wg.cpp
DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/src/mm_dpcpp_basic_full.cpp
DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/src/mm_dpcpp_common.cpp
DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/src/mm_dpcpp_common_wg.cpp

updated cmath function for 2025.0 release, included cmath, changed fabs to std::fabs and sqrt yo std::sqrt
Fixes Issue#

updated cmath function for 2025.0

---

AI-and-Analytics/End-to-end-Workloads/JobRecommendationSystem/JobRecommendationSystem.ipynb
AI-and-Analytics/End-to-end-Workloads/JobRecommendationSystem/JobRecommendationSystem.py
AI-and-Analytics/End-to-end-Workloads/JobRecommendationSystem/License.txt
AI-and-Analytics/End-to-end-Workloads/JobRecommendationSystem/README.md
AI-and-Analytics/End-to-end-Workloads/JobRecommendationSystem/requirements.txt
AI-and-Analytics/End-to-end-Workloads/JobRecommendationSystem/sample.json
AI-and-Analytics/End-to-end-Workloads/JobRecommendationSystem/third-party-programs.txt

This sample illustrates the use of Intel® Extension for TensorFlow* to build and run an end-to-end AI workload on the example of the job recommendation system.
It consists of four main parts:
Data exploration and visualization - showing what the dataset is looking like, what are some of the main features and what is a data distribution in it.
Data cleaning and pre-processing - removal of duplicates, explanation all necessary steps for text pre-processing.
Fraud job postings removal - finding which of the job posting are fake using LSTM DNN and filtering them.
Job recommendation - calculation and providing top-n job descriptions similar to the chosen one.
Administrative
- [x ] Implement coding guidelines and ensure code quality. [see wiki for …

New code sample: Job Recommendation System - end-to-end workload

---

DirectProgramming/C++SYCL/DenseLinearAlgebra/address_sanitizer/src/bad_free.cpp

Fix UR_RESULT_ERROR_INVALID_MEM_OBJECT

[DeviceASAN] Fix bad_free.cpp

---

Libraries/oneMKL/binomial/src/binomial_sycl.cpp
Libraries/oneMKL/computed_tomography/computed_tomography.cpp
Libraries/oneMKL/fourier_correlation/fcorr_1d_buffers.cpp
Libraries/oneMKL/fourier_correlation/fcorr_1d_usm.cpp
Libraries/oneMKL/fourier_correlation/fcorr_2d_usm.cpp
Libraries/oneMKL/guided_american_options_SYCLmigration/README.md
Libraries/oneMKL/monte_carlo_pi/mc_pi.cpp
Libraries/oneMKL/monte_carlo_pi/mc_pi_device_api.cpp
Libraries/oneMKL/monte_carlo_pi/mc_pi_usm.cpp
Libraries/oneMKL/random_sampling_without_replacement/lottery.cpp
Libraries/oneMKL/random_sampling_without_replacement/lottery_device_api.cpp
Libraries/oneMKL/random_sampling_without_replacement/lottery_usm.cpp
Libraries/oneMKL/sparse_conjugate_gradient/sparse_cg2.cpp

Fixed some spelling issues for oneMKL samples

[oneMKL] Fix some spelling issues

---

Libraries/oneMKL/matrix_mul_mkl/matrix_mul_mkl.cpp

To increase informativeness of the sample, following changes were made:
1. added "all" types option
2. added exception handling for SYCL ones
3. added FP64 capability check
4. Updated device info printing, including platform (OpenCL/Level0) and driver version prints.
None

[oneMKL] matrix_mul_mkl update

---

AI-and-Analytics/Getting-Started-Samples/Modin_GettingStarted/requirements.txt
AI-and-Analytics/Getting-Started-Samples/Modin_GettingStarted/sample.json

Added requirements.txt to Modin_GettingStarted sample

Added requirements.txt to Modin_GettingStarted sample

---

DirectProgramming/C++SYCL/SpectralMethods/DiscreteCosineTransform/src/DCT.cpp

Fix for a JIRA ticket. This update also removes deprecated code.
Fixes Issue# ONSAM-2029

Fix ONSAM-2029

---

Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/README.md
Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/src/1_matrix_mul_null_pointer.cpp
Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/src/2_matrix_mul_multi_offload.cpp
Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/src/3_matrix_mul.cpp

Fixes Issue# None but the sample had issues due to language changes

Updates to Tools/ApplicationDebugger/guided_matrix_mult_Exceptions tutorial for 2025.0 and 2502.18 rolling release

---

Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/README.md
Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/src/1_matrix_mul_race_condition.cpp
Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/src/2_matrix_mul.cpp
Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/src/3_matrix_mul.cpp

Fixes Issue# ONSAM-1872, ONSAM-2058

Updates to RaceCondition tutorial for 2025.0 and 2502.18 rolling release

---

Tools/ApplicationDebugger/guided_matrix_mult_InvalidContexts/README.md
Tools/ApplicationDebugger/guided_matrix_mult_InvalidContexts/src/1_matrix_mul_invalid_contexts.cpp
Tools/ApplicationDebugger/guided_matrix_mult_InvalidContexts/src/2_matrix_mul.cpp

Updates to InvalidContexts tutorial for 2025.0 and 2502.18 rolling release

---

Tools/ApplicationDebugger/guided_matrix_mult_SLMSize/README.md
Tools/ApplicationDebugger/guided_matrix_mult_SLMSize/src/1_matrix_mul_SLM_size.cpp
Tools/ApplicationDebugger/guided_matrix_mult_SLMSize/src/2_matrix_mul.cpp

Updates to SLMSize tutorial for 2025.0 and 2502.18 rolling release

---

AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/README.md
AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_SKLearn_GettingStarted/readme.md

update readme ONSAM-2077

---

Tools/VTuneProfiler/matrix_multiply_vtune/README.md

Update README for matrix_multiply_vtune sample

---

Tools/GPU-Occupancy-Calculator/index.html

fixed BMG EU counts in GPU Occupancy Calculator

fixed BMG EU counts

---

AI-and-Analytics/End-to-end-Workloads/Census/census_modin.ipynb
AI-and-Analytics/End-to-end-Workloads/LanguageIdentification/Inference/lang_id_inference.ipynb
AI-and-Analytics/End-to-end-Workloads/LanguageIdentification/Training/lang_id_training.ipynb
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/IntelPython_daal4py_Distributed_Kmeans.ipynb
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/IntelPython_daal4py_Distributed_Kmeans.py
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/README.md
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning/enabling_automixed_precision_for_transfer_learning_with_tensorflow.ipynb
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_for_LLMs/GPTJ_finetuning.ipynb
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_for_LLMs/GPTJ_finetuning.py
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_for_LLMs/GPTJ_inference.ipynb
AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_for_LLMs/GPTJ_inference.py
AI-and-Analytics/Features-and-Functionality/Intel_Extension_For_SKLearn_Performance_SVC_Adult/Intel_Extension_for_SKLearn_Performance_SVC_Adult.ipynb
AI-and-Analytics/Features-and-Functionality/Intel_Extension_For_SKLearn_Performance_SVC_Adult/Intel_Extension_for_SKLearn_Performance_SVC_Adult.py
AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/quantize_with_inc.ipynb
AI-and-Analytics/Getting-Started-Samples/Modin_Vs_Pandas/Modin_Vs_Pandas.ipynb

This change adds missing `[CODE_SAMPLE_COMPLETED_SUCCESSFULLY]` messages to `*.ipynb` files.
Before this, there was no completion message output at the end of these files.
The below `*.ipynb` files were also fixed to match changes in their corresponding `*.py` files:
```
AI-and-Analytics/Features-and-Functionality/Intel_Extension_For_SKLearn_Performance_SVC_Adult/Intel_Extension_for_SKLearn_Performance_SVC_Adult.ipynb
AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/IntelPython_daal4py_Distributed_Kmeans.ipynb
```
`*.py` files were regenerated using the Jupyter convert to script command:
```
jupyter nbconvert --to script <filename>.ipynb
```
None.
Please describe the …

Add missing success messages

---

Libraries/oneCCL/oneCCL_Getting_Started/README.md

fix oneCCL readme command guide issue

---

AI-and-Analytics/version_check.py

This change cleans up the formatting and presentation of `version_check.py`. Before this, the formatting and presentation of the script output was inconsistent.
None.

Fix formatting and presentation in version_check.py

---

Libraries/oneMKL/computed_tomography/GNUmakefile
Libraries/oneMKL/computed_tomography/README.md
Libraries/oneMKL/computed_tomography/computed_tomography.cpp
Libraries/oneMKL/computed_tomography/makefile

Cherry-picking [PR#2564](https://github.com/oneapi-src/oneAPI-samples/pull/2564) on `main` branch.

[oneMKL samples][computed tomography] Revisions, refactoring and addition of a functional verification (cherry-pick of PR#2564)

---

DirectProgramming/C++SYCL/SYCL-Graph/diamond-dependency/sample.json
DirectProgramming/C++SYCL/SYCL-Graph/dot-product/CMakeLists.txt
DirectProgramming/C++SYCL/SYCL-Graph/dot-product/sample.json

- Adds run lines 
- Fixes cmake for dot-product samples
pinging @jimmytwei for visibility

Fix Sycl Graph Samples
