oneapi-src/oneAPI-samples

DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/CMakeLists.txt, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/License.txt, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/README.md, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/include/device_selector.hpp, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/include/iso3dfd.h, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/iso3dfd_dpcpp.sln, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/iso3dfd_dpcpp.vcxproj, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/iso3dfd_dpcpp.vcxproj.filters, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/iso3dfd_dpcpp.vcxproj.user, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/sample.json, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/src/CMakeLists.txt, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/src/iso3dfd.cpp, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/src/iso3dfd_kernels.cpp, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/src/utils.cpp
Signed-off-by: Gogar, Sunny L <sunny.l.gogar@intel.com>
=> Initial commit for iso3dfd_dpcpp code sample

DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/Makefile.fpga, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/Makefile.win, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/Makefile.win.fpga, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/README.md, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/sample.json, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/src/vector-add-usm.cpp, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/vector-add-buffers.vcxproj, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/vector-add-usm.vcxproj, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/vector-add.sln
moving the latest vector-add to new repo, updated sample.json, added vector-add-usm.vcxproj
Signed-off-by: jennifer
=> moving vector-add to new repo.

DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/CMakeLists.txt, DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/License.txt, DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/README.md, DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/iso2dfd.sln, DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/iso2dfd.vcxproj, DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/iso2dfd.vcxproj.filters, DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/iso2dfd.vcxproj.user, DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/sample.json, DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/src/iso2dfd.cpp, DirectProgramming/DPC++/StructuredGrids/particle-diffusion/CMakeLists.txt, DirectProgramming/DPC++/StructuredGrids/particle-diffusion/License.txt, DirectProgramming/DPC++/StructuredGrids/particle-diffusion/Particle_Diffusion.sln, DirectProgramming/DPC++/StructuredGrids/particle-diffusion/Particle_Diffusion.vcxproj, DirectProgramming/DPC++/StructuredGrids/particle-diffusion/Particle_Diffusion.vcxproj.filters, DirectProgramming/DPC++/StructuredGrids/particle-diffusion/Particle_Diffusion.vcxproj.user, DirectProgramming/DPC++/StructuredGrids/particle-diffusion/README.md, DirectProgramming/DPC++/StructuredGrids/particle-diffusion/draft, DirectProgramming/DPC++/StructuredGrids/particle-diffusion/sample.json, DirectProgramming/DPC++/StructuredGrids/particle-diffusion/src/CMakeLists.txt, DirectProgramming/DPC++/StructuredGrids/particle-diffusion/src/motionsim.cpp
Added particle-diffusion directory
=> Adding Particle Diffusion code sample to Open Source repo - 2

Libraries/oneDPL/gamma-correction/README.md, Libraries/oneDPL/gamma-correction/sample.json, Libraries/oneDPL/stable_sort_by_key/README.md, Libraries/oneDPL/stable_sort_by_key/sample.json
Updated all references of the DPC++ Compiler to the "Intel® oneAPI DPC++/C++ Compiler" under Libraries/oneDPL
- This change only affects samples' readmes and sample.json
Must be tested via the CI pipeline as the only possible breaking changes were to sample.json files
=> oneDPL samples README/samples.json - Updated DPC++/C++ Compiler labels

Tools/ApplicationDebugger/array-transform/README.md
Update the DevCloud note about GPU node usage.
Documentation update.
Tested on the DevCloud.
=> array-transform: update the devcloud note

DirectProgramming/DPC++FPGA/Tutorials/Features/speculated_iterations/speculated_iterations.vcxproj
Signed-off-by: Jessica Davies <jessica.davies@intel.com>
The FPGA speculated_iterations tutorial fails to build for Visual Studio, because the static assert on line 122 fails. To fix this, add the missing A10 board option to the vcxproj file.
=> Fix FPGA speculated_iterations static_assert failure for Visual Studio

Tools/Advisor/README.md, Tools/Advisor/matrix_multiply_advisor/Advisor_matrix_multiply_advisor_README.md, Tools/Advisor/matrix_multiply_advisor/CMakeLists.txt, Tools/Advisor/matrix_multiply_advisor/License.txt, Tools/Advisor/matrix_multiply_advisor/README.md, Tools/Advisor/matrix_multiply_advisor/matrix_multiply.sln, Tools/Advisor/matrix_multiply_advisor/matrix_multiply.vcxproj, Tools/Advisor/matrix_multiply_advisor/matrix_multiply.vcxproj.filters, Tools/Advisor/matrix_multiply_advisor/matrix_multiply.vcxproj.user, Tools/Advisor/matrix_multiply_advisor/sample.json, Tools/Advisor/matrix_multiply_advisor/src/matrix.cpp, Tools/Advisor/matrix_multiply_advisor/src/multiply.cpp, Tools/Advisor/matrix_multiply_advisor/src/multiply.hpp, Tools/VTuneProfiler/README.md, Tools/VTuneProfiler/matrix_multiply_vtune/CMakeLists.txt, Tools/VTuneProfiler/matrix_multiply_vtune/License.txt, Tools/VTuneProfiler/matrix_multiply_vtune/README.md, Tools/VTuneProfiler/matrix_multiply_vtune/matrix_multiply.sln, Tools/VTuneProfiler/matrix_multiply_vtune/matrix_multiply.vcxproj, Tools/VTuneProfiler/matrix_multiply_vtune/matrix_multiply.vcxproj.filters, Tools/VTuneProfiler/matrix_multiply_vtune/matrix_multiply.vcxproj.user, Tools/VTuneProfiler/matrix_multiply_vtune/sample.json, Tools/VTuneProfiler/matrix_multiply_vtune/src/matrix.cpp, Tools/VTuneProfiler/matrix_multiply_vtune/src/multiply.cpp, Tools/VTuneProfiler/matrix_multiply_vtune/src/multiply.hpp
I followed the instructions to copy from gitlab
- [ x] Sample Migration (Moving sample from old repository after completing checklist established)
=> Add vtune and advisor sample

Tools/IoTConnectionTools/ibm-device/CMakeLists.txt, Tools/IoTConnectionTools/ibm-device/License.txt, Tools/IoTConnectionTools/ibm-device/README.md, Tools/IoTConnectionTools/ibm-device/cpp/deviceSample.c, Tools/IoTConnectionTools/ibm-device/sample.json
A sample to test IBM device connection. It is not approved by Sample Workgroup yet so marked as  WIP.
=> IBM IoT sample

Tools/SystemDebug/docs/EFIApplication.rst
Fixes type-o on git command pulling this repo. 
=> system debug: remove trailing 's' in git command

Libraries/oneDNN/dpcpp_interoperability/README.md, Libraries/oneDNN/getting_started/README.md, Libraries/oneDNN/simple_model/README.md
=> Update README.md for compiling/running samples on Windows OS

Tools/ApplicationDebugger/array-transform/src/array-transform.cpp
* Use the `auto` keyword for the `parallel_for` parameter.
* Correct the type of a variable.
* Use the simplified accessor definition.
Minor style improvement.
=> ApplicationDebugger/array-transform: apply minor style improvements

Tools/SystemDebug/docs/EFIApplication.rst, Tools/SystemDebug/efi_application/README.md
Clarifies need for 64 bit builds on windows builders. 
=> system debug: make documentation clearer that X64 option is required

Libraries/oneMKL/black_scholes/GNUmakefile, Libraries/oneMKL/black_scholes/makefile, Libraries/oneMKL/monte_carlo_pi/GNUmakefile, Libraries/oneMKL/monte_carlo_pi/makefile
This PR adds -fno-sycl-early-optimizations to the command line of oneMKL samples using RNG device APIs to work around a known issue in the beta09 compiler.
=> Add workaround flag to oneMKL RNG device API samples

DirectProgramming/DPC++/ParallelPatterns/histogram/README.md
Add W/A to README of histogram sample to avoid some issues on GPU
Signed-off-by: Sobolev, Dmitriy <dmitriy.sobolev@intel.com>
The W/A has been added to be able to run the sample on GPU with L0 using oneAPI beta09.
Must be tested via the CI pipeline as the only possible breaking changes were to README.md file
=> Add W/A to README of histogram sample to avoid some issues on GPU

Libraries/oneMKL/sparse_conjugate_gradient/makefile
There was a missed Linux-style path separator in the Windows makefile for sparse_conjugate_gradient.
=> sparse_conjugate_gradient: fix Windows path separator

Libraries/oneMKL/black_scholes/black_scholes.cpp
Removes device API tests from black_scholes on Windows, where it is hanging with beta09 RC2 (root cause TBD).
=> black_scholes: omit RNG device APIs on Windows

Libraries/oneVPL/dpcpp-blur/CMakeLists.txt, Libraries/oneVPL/dpcpp-blur/README.md, Libraries/oneVPL/dpcpp-blur/dpcpp-blur.vcxproj.user, Libraries/oneVPL/dpcpp-blur/sample.json, Libraries/oneVPL/dpcpp-blur/src/dpcpp-blur.cpp, Libraries/oneVPL/hello-decode/CMakeLists.txt, Libraries/oneVPL/hello-decode/README.md, Libraries/oneVPL/hello-encode/CMakeLists.txt, Libraries/oneVPL/hello-encode/README.md, Libraries/oneVPL/hello-vpp/CMakeLists.txt, Libraries/oneVPL/hello-vpp/README.md
Fix MSVC build/runtime issues in oneVPL samples
Fixes VPL7-290, VPL7-291, VPL7-292, VPL7-293, VPL7-294
=> Fix MSVC build/runtime issues in oneVPL samples

DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/License.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/README.md, DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/max_interleaving.sln, DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/max_interleaving.vcxproj, DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/sample.json, DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/src/build.ninja, DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/src/max_interleaving.cpp
Add max_interleaving DPC++FPGA tutorial
This tutorial demonstrates how to apply the max_interleaving attribute to loops and how it affects loop resource use.
=> Add max_interleaving DPC++ FPGA tutorial

Libraries/oneMKL/monte_carlo_european_opt/README.md, Libraries/oneMKL/monte_carlo_european_opt/mc_european.cpp, Libraries/oneMKL/monte_carlo_european_opt/mc_european_usm.cpp, Libraries/oneMKL/monte_carlo_pi/mc_pi.cpp, Libraries/oneMKL/monte_carlo_pi/mc_pi_device_api.cpp, Libraries/oneMKL/monte_carlo_pi/mc_pi_usm.cpp, Libraries/oneMKL/random_sampling_without_replacement/GNUmakefile, Libraries/oneMKL/random_sampling_without_replacement/License.txt, Libraries/oneMKL/random_sampling_without_replacement/README.md, Libraries/oneMKL/random_sampling_without_replacement/lottery.cpp, Libraries/oneMKL/random_sampling_without_replacement/lottery_device_api.cpp, Libraries/oneMKL/random_sampling_without_replacement/lottery_usm.cpp, Libraries/oneMKL/random_sampling_without_replacement/makefile, Libraries/oneMKL/random_sampling_without_replacement/sample.json
- W/a is added for reduce function (namespace changes from sycl::intel to sycl::ONEAPI::)
- European option pricing sample is cleaned and aligned with pi number evaluation sample
- Add new RNG sample: Multiple Simple Random Sampling without replacement
Manually tests for Linux and Windows CPU and GPU with oneMKL beta08 and oneMKL beta09 functionality
=> [oneMKL][RNG] Samples clean up for RNG, add new sample.

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/License.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/README.md, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/compute_units.sln, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/compute_units.vcxproj, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/sample.json, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/src/build.ninja, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/src/compute_units.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/src/compute_units.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/src/pipe_array.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/src/pipe_array_internal.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/src/unroller.hpp
This tutorial shows how to make multiple copies of kernels, called compute_units.
=> Add compute_units DPC++ FPGA tutorial

Tools/ApplicationDebugger/array-transform/src/array-transform.cpp
Set the type of GetDim's parameter to 'item', because when the
parameter of the kernel is declared as 'auto', the inferred type is
'item'.
=> ApplicationDebugger/array-transform: change the type of GetDim's parameter

Libraries/oneTBB/README.md, Libraries/oneTBB/tbb-resumable-tasks-sycl/CMakeLists.txt, Libraries/oneTBB/tbb-resumable-tasks-sycl/License.txt, Libraries/oneTBB/tbb-resumable-tasks-sycl/README.md, Libraries/oneTBB/tbb-resumable-tasks-sycl/sample.json, Libraries/oneTBB/tbb-resumable-tasks-sycl/src/CMakeLists.txt, Libraries/oneTBB/tbb-resumable-tasks-sycl/src/tbb-resumable-tasks-sycl.cpp, Libraries/oneTBB/tbb-resumable-tasks-sycl/tbb-resumable-tasks-sycl.sln, Libraries/oneTBB/tbb-resumable-tasks-sycl/tbb-resumable-tasks-sycl.vcxproj, Libraries/oneTBB/tbb-resumable-tasks-sycl/tbb-resumable-tasks-sycl.vcxproj.filters, Libraries/oneTBB/tbb-resumable-tasks-sycl/tbb-resumable-tasks-sycl.vcxproj.user
Adding new sample for oneTBB library - tbb-resumable-tasks-sycl, which shows how computation can be splitted between CPU and GPU (GPU part is execute inside the tbb::task::suspend function)
Tested manually on Linux and Windows (Visual Studio). Instructions can be found in the README.MD file.
=> Add tbb-resumable-tasks-sycl sample for oneTBB library

Tools/ApplicationDebugger/array-transform/README.md
1. Update the debugger name and add trademark note.
2. Update the compiler name.
3. Fine-tune spacing of the table.
4. Refer to the Get Started Guide for details.
5. Update the examples outputs.
=> ApplicationDebugger/array-transform: fine-tune README

Tools/ApplicationDebugger/array-transform/src/array-transform.cpp
Use the explicit type `id` for parallel_for's index parameter.  This
is necessary because the `auto` type is inferred by the compiler as
`item`; however, the `item` type impacts the debugger's Get Started
Guide.  There is a pretty printer defined for `id`, but not `item`.
A fix that improves documentation (Get Started Guide).
=> ApplicationDebugger/array-transform: use explicit type for parallel_for's index

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/README.md, DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/build.ninja, DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzip.cpp
Update GZIP for beta10 -- use USM for data transfer + update compile seed.
=> Beta10 GZIP performance update

Libraries/oneMKL/black_scholes/black_scholes.cpp, Libraries/oneMKL/block_cholesky_decomposition/dpbltrf.cpp, Libraries/oneMKL/block_cholesky_decomposition/dpbltrs.cpp, Libraries/oneMKL/block_cholesky_decomposition/factor.cpp, Libraries/oneMKL/block_cholesky_decomposition/solve.cpp, Libraries/oneMKL/block_lu_decomposition/dgeblttrf.cpp, Libraries/oneMKL/block_lu_decomposition/dgeblttrs.cpp, Libraries/oneMKL/block_lu_decomposition/factor.cpp, Libraries/oneMKL/block_lu_decomposition/solve.cpp, Libraries/oneMKL/matrix_mul_mkl/matrix_mul_mkl.cpp, Libraries/oneMKL/monte_carlo_european_opt/mc_european.cpp, Libraries/oneMKL/monte_carlo_european_opt/mc_european_usm.cpp, Libraries/oneMKL/monte_carlo_pi/mc_pi.cpp, Libraries/oneMKL/monte_carlo_pi/mc_pi_device_api.cpp, Libraries/oneMKL/monte_carlo_pi/mc_pi_usm.cpp, Libraries/oneMKL/random_sampling_without_replacement/lottery.cpp, Libraries/oneMKL/random_sampling_without_replacement/lottery_device_api.cpp, Libraries/oneMKL/random_sampling_without_replacement/lottery_usm.cpp, Libraries/oneMKL/sparse_conjugate_gradient/sparse_cg.cpp
Updates existing oneMKL samples for compatibility with beta10:
Changes retain beta09 compatibility. At the same time, old beta08 compatibility code has been dropped.
=> oneMKL sample updates for beta10

Tools/Migration/folder-options-dpct/sample.json, Tools/Migration/rodinia-nw-dpct/sample.json, Tools/Migration/vector-add-dpct/sample.json
Signed-off-by: xmnboy <xmnboy@yahoo.com>
Adding a temporary empty `ciTests` object so the sample tests can proceed without error. Additional software support is needed on the sample CI test system before we can support actual testing of the `dpct` tutorial samples.
Fixes email issue: _Re: Broken samples.json file merged to Sample Open Source repo_ 
> Today’s run of pre-production Samples CI failed with the following error:
> [01:46:39][Step 3/4] _______________________ ERROR collecting test_samples.py _______________________
> [01:46:39][Step 3/4] /usr/local/lib/python3.8/dist-packages/pluggy/hooks.py:286: in __call__
> [01:46:39][Step 3/4] return self._hookexec(self, self.get_hookimpls(), kwargs)
> [01:46:39][Step 3/4] /usr/local/lib/python3.8/dist-packages/pluggy/manager.py:93: in …
=> Add empty ciTest object so testing does not fail.

DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/src/vector-add-buffers.cpp, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/src/vector-add-usm.cpp
In beta10, the Intel header locations and the Intel SYCL extension namespace changed from "intel" to "INTEL" following the Khronos SYCL requirements. There is no deprecation period. This minor change updates the vector-add sample for beta10 compatibility.
This will fail on beta09. I consider this acceptable for master, since beta10 release tag is only 2 weeks away.
While in the neighborhood, I also fixed up the formatting of the async handler code.
=> Update header location and namespace for beta10

Libraries/oneMKL/black_scholes/black_scholes.cpp, Libraries/oneMKL/black_scholes/black_scholes.hpp, Libraries/oneMKL/black_scholes/black_scholes_buffer_vml.hpp, Libraries/oneMKL/black_scholes/black_scholes_usm_vml.hpp
Updates the Black-Scholes example to use the new `oneapi::mkl::vm::mode` enum introduced in beta10.
=> black_scholes: update for beta10

Libraries/oneMKL/computed_tomography/GNUmakefile, Libraries/oneMKL/computed_tomography/makefile, Libraries/oneMKL/matrix_mul_mkl/GNUmakefile, Libraries/oneMKL/matrix_mul_mkl/makefile, Libraries/oneMKL/monte_carlo_european_opt/GNUmakefile, Libraries/oneMKL/monte_carlo_european_opt/makefile, Libraries/oneMKL/monte_carlo_pi/GNUmakefile, Libraries/oneMKL/monte_carlo_pi/makefile, Libraries/oneMKL/random_sampling_without_replacement/GNUmakefile, Libraries/oneMKL/random_sampling_without_replacement/makefile, Libraries/oneMKL/sparse_conjugate_gradient/GNUmakefile, Libraries/oneMKL/sparse_conjugate_gradient/makefile
Adds "all" targets for oneMKL sample makefiles which do not have them. This is the default target for Eclipse.
=> Add 'all' target to oneMKL samples for Eclipse

DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/README.md, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/README.md
The 'Running on DevCloud' README section is missing from these key introductory samples. An issue was filed recently by a user who ran into trouble because he failed to specify a DevCloud node.
=> Add 'Running on DevCloud' README section to simple-add and vector-add

DirectProgramming/DPC++/ProjectTemplates/cmake-fpga/src/main.cpp, DirectProgramming/DPC++/ProjectTemplates/makefile-fpga/src/main.cpp
As discussed with @akertesz, update the casing of intel namespace to INTEL.
Fixes DEV1A-1215.
FYI @akertesz please review and merge.
Not tested.
=> DEV1A-1215: fix namespace casing

Tools/Migration/folder-options-dpct/Makefile, Tools/Migration/rodinia-nw-dpct/Makefile, Tools/Migration/vector-add-dpct/Makefile
Testing the three migration samples within Eclipse made it apparent that an "all" target was necessary, in order that the end-user can use the default Eclipse build action (make all) when these are imported into Eclipse via the Eclipse samples browser.
This change results in zero changes to the actual sample sources. It simply adds an "all" target in the Makefile that points to what was the previously default target. Thus, the result of a "make" command (without specifying a target) is unchanged. The only functional change is that now a "make all" command will not result in a make error message. The "make all" command is the default action performed in Eclipse when one takes the default "build" action on a Makefile project; these three projects are Makefile projects.
Please delete options …
=> Add "make all" target for better user experience in Eclipse for migration samples.

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/build.ninja
Support for this flag was removed from the compiler when the behavior became default. Accidentally forgot to remove the bad flag from the ninja file.
=> Update build.ninja, remove USM flag

Tools/IoTConnectionTools/analog-in/sample.json, Tools/IoTConnectionTools/aws-pub-sub/sample.json, Tools/IoTConnectionTools/azure-iothub-telemetry/sample.json, Tools/IoTConnectionTools/digital-in/sample.json, Tools/IoTConnectionTools/digital-out/sample.json, Tools/IoTConnectionTools/hello-iot-world/sample.json, Tools/IoTConnectionTools/ibm-device/sample.json, Tools/IoTConnectionTools/interrupt/sample.json, Tools/IoTConnectionTools/onboard-blink/sample.json, Tools/IoTConnectionTools/pwm/sample.json, Tools/IoTConnectionTools/up2-leds/sample.json
Signed-off-by: Mihai Tudor Panu <mihai.tudor.panu@intel.com>
Fixes CI warning for missing builder attribute from IoT Connection Tools code samples
=> add builder attribute to IoTConnectionTools sample.json files

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/License.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/README.md, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/sample.json, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/buffer_kernel.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/build.ninja, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/restricted_usm_kernel.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/zero_copy_data_transfer.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/zero_copy_data_transfer.sln, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/zero_copy_data_transfer.vcxproj
Adding new FPGA tutorial on how to use restricted USM to do zero-copy data transfer between the CPU and FPGA.
Expected to fail:
1) INTEL/intel namespace/filename incompatibility of beta09/beta10
2) Linux OS support - Ubuntu 20.4 not yet supported for FPGA
=> Adding FPGA tutorial 'zero_copy_data_transfer' (after beta10)

DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/Makefile.fpga, DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/Makefile.win.fpga, DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/sample.json, DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/src/simple-add-buffers.cpp, DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/src/simple-add-usm.cpp, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/Makefile.fpga, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/Makefile.win.fpga, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/sample.json, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/src/vector-add-buffers.cpp
Updating FPGA portion of simple-add and vector-add
1. Enabling USM targets in Makefile.fpga and Makefile.win.fpga
2. Updating samples.json to run the FPGA USM targets
3. Removing Beta09/Beta10 include hack
4. Adding noinit flag to output buffer accessor
=> Fix FPGA issues in vector-add and simple-add

Tools/ApplicationDebugger/array-transform/CMakeLists.txt
Use the STATUS kind instead of WARNING for the messages printed from CMake.
=> ApplicationDebugger/array-transform: use STATUS kind in CMake message

README.md
Six FPGA code samples have been added for the 2021.1 oneAPI production release ("gold"). One FPGA code sample has changed its name. I'm updating the top-level README's table to reflect these changes.
=> Update top-level README to add new FPGA code samples

DirectProgramming/DPC++FPGA/ReferenceDesigns/crr/src/main.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/db_utils/Accumulator.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/db_utils/fifo_sort.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query1/query1_kernel.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query11/query11_kernel.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query9/query9_kernel.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzipkernel.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/src/qrd.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/onchip_memory_cache/src/onchip_memory_cache.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/optimize_inner_loop/src/optimize_inner_loop.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/shannonization/src/IntersectionKernel.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/triangular_loop/src/triangular_loop.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/fpga_reg/src/fpga_reg.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_coalesce/src/loop_coalesce.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_ivdep/src/loop_ivdep.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/max_concurrency/src/max_concurrency.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/src/max_interleaving.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/memory_attributes/src/memory_attributes.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/speculated_iterations/src/speculated_iterations.cpp
The intelfpga:: attributes are deprecated in the 2021.1 production release in favor of a more universal syntax under the intel:: namespace. This change updates all FPGA samples that use these attributes to the new syntax. As a result, these attributes will be ignored if compiled against beta10.
=> Change FPGA samples' intelfpga:: attributes to updated intel:: syntax

DirectProgramming/DPC++/ProjectTemplates/cmake-fpga/src/CMakeLists.txt
Apply the same fix from PR 287 to the FPGA CMake project template.
https://github.com/oneapi-src/oneAPI-samples/pull/287
=> Apply CMAKE_CXX_FLAGS warnings fix to FPGA cmake template

DirectProgramming/DPC++FPGA/ReferenceDesigns/crr/sample.json
The Windows sample.json target has a slight error in the path of the input file, causing a CI failure on Windows. This fixes it.
=> Update crr's sample.json

DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/README.md
Signed-off-by: Abhishek Tiwari <abhishek2.tiwari@intel.com>
Update the README to guide users to set the CL_CONFIG_CPU_FORCE_PRIVATE_MEM_SIZE environment variable on Linux before running the emulator executable. This increases the memory allocation limit for the emulator runtime and is needed to prevent CL_OUT_OF_RESOURCES error.
No code change is being made, this is purely a documentation update.
Setting of the environment variable has been tested on:
- [ X ] Command Line
- [ X ] Visual Studio
=> Add environment variable setting info in README for FPGA Reference Design QRD

Libraries/oneMKL/black_scholes/black_scholes.cpp, Libraries/oneMKL/computed_tomography/computed_tomography.cpp, Libraries/oneMKL/monte_carlo_european_opt/mc_european.cpp
Fixes some warnings that appear when compiling some oneMKL samples with `-Wall`.
=> Fix warnings in oneMKL samples

DirectProgramming/DPC++/ParallelPatterns/histogram/README.md
Signed-off-by: Sobolev, Dmitriy <dmitriy.sobolev@intel.com>
This removes the work-around from README.md of histogram sample which irrelevant for oneAPI beta10.
I downloaded and ran the latest  Intel® oneAPI Base Toolkit docker image following these commands:
```bash
image=intel/oneapi-basekit
docker pull "$image"
docker run --device=/dev/dri -it "$image"
```
then built and ran the histogram sample:
```bash
cd oneAPI-samples/DirectProgramming/DPC++/ParallelPatterns/histogram
mkdir build
cd build
cmake ..
make
export SYCL_DEVICE_TYPE=GPU
export SYLC_BE=PI_LEVEL0
make run
```
No issue noticed during execution.
=> Remove irrelevant known issue from README.md of histogram sample

Libraries/oneMKL/block_lu_decomposition/factor.cpp, Libraries/oneMKL/block_lu_decomposition/solve.cpp, Libraries/oneMKL/monte_carlo_european_opt/mc_european_usm.cpp
* Restricts block_lu_decomposition to L0 when running on GPU (temporary)
* Removes unused variable in mc_european_usm flagged by -Wall.
=> oneMKL sample updates for Gold

Tools/Migration/rodinia-nw-dpct/src/needle.cu
The `<sys/time.h>` header file and `gettimeofday()` function were unused bits of code that was picked up with the migration of this sample from its original source. They were creating a confusing nuisance error on Windows systems, since Windows does not support the `<sys/time.h>` header file.
Fixes # ONSAM-1356 
Testing the issue is described in ONSAM-1356. Testing was performed on a Linux system and a Windows system.
FYI: @JoeOster and @srdontha
=> Remove unused references to <sys/time.h> and gettimeofday()

Libraries/oneDPL/gamma-correction/src/main.cpp, Libraries/oneDPL/stable_sort_by_key/src/main.cpp
oneDPL headers shall be placed before C++ standard library headers especially when libstdc++9 or newer is installed on the system.
=> move oneDPL headers before standard headers

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/README.md, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/sample.json, DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/src/qrd.hpp, DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fast_recompile/README.md, DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
DB Q9's report target takes an unexpectedly long time to build, ~2 hours. This leads to timeout failures in the CI test set, and it's a bad user experience too. This should be addressed at a product level, but in the short term I've pulled the tests out of CI and updated DB's README to alert the user.
Some minor typo fixes in other files are also included in this PR.
=> Address DB Q9's long build time + small README fixes

Libraries/oneTBB/tbb-async-sycl/tbb-async-sycl.vcxproj, Libraries/oneTBB/tbb-resumable-tasks-sycl/tbb-resumable-tasks-sycl.vcxproj, Libraries/oneTBB/tbb-task-sycl/tbb-task-sycl.vcxproj
Add /Od linker option for Debug configurations on Windows for three oneTBB samples
=> Add /Od linker option on Windows for oneTBB samples

Libraries/oneMKL/black_scholes/README.md, Libraries/oneMKL/block_cholesky_decomposition/README.md, Libraries/oneMKL/block_lu_decomposition/README.md, Libraries/oneMKL/computed_tomography/README.md, Libraries/oneMKL/matrix_mul_mkl/README.md, Libraries/oneMKL/monte_carlo_european_opt/README.md, Libraries/oneMKL/monte_carlo_pi/README.md, Libraries/oneMKL/random_sampling_without_replacement/README.md, Libraries/oneMKL/sparse_conjugate_gradient/README.md
This PR adds warning text to the READMEs about long link times on Windows.
FYI: @JoeOster
=> Warn about long oneMKL link times on Windows

Tools/IoTConnectionTools/hello-iot-world/README.md, Tools/IoTConnectionTools/hello-iot-world/sample.json
Removing this sample from the Windows sample feed. It will remain in the Linux sample feed. This will make it consistent with the other IoT Toolkit samples. No changes to the actual sample sources are required, only to the sample.json and README.md files.
Signed-off-by: Paul A. Fischer <paul.a.fischer@intel.com>
Addresses Teams and email thread regarding usability issues regarding this sample in the context of Visual Studio.
As part of any _possible_ future efforts to support oneAPI CMake samples in Visual Studio, we will need to:
* …
=> Remove Windows as a supported platform for the "hello iot" sample

DirectProgramming/DPC++FPGA/Tutorials/Features/pipes/README.md, DirectProgramming/DPC++FPGA/Tutorials/Features/pipes/src/pipes.cpp, DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fast_recompile/README.md, DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fast_recompile/fast_recompile.vcxproj, DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fast_recompile/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fast_recompile/src/host.cpp, DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fast_recompile/src/kernel.cpp, DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fast_recompile/src/kernel.hpp
**DPC++FPGA/GettingStarted/fast-recompile**
Internal user gave feedback that code sample was unclear about the fast recompile method demonstrated. Also, that the kernel and host code were insufficiently well separated. Minor changes to the README and cpp files were made to increase clarity, and to make a better template for splitting host/kernel code.
**DPC++FPGA/Features/pipes**
The filer of issue https://github.com/oneapi-src/oneAPI-samples/issues/360 perceived a "bug" which proved to be simply a point of confusion about the significance of timing results in the FPGA emulator vs. HW. The code sample is improved to a) dump timing information during execution, b) explain the results observed in emulation and hardware runs, and c) increase the amount of data transfer to better show the …
=> Improve clarity of two key FPGA tutorials in response to user feedback

Libraries/oneCCL/tutorials/oneCCL_Getting_Started.ipynb, Libraries/oneDNN/tutorials/CMakeLists.txt, Libraries/oneDNN/tutorials/codes_for_ipynb/cnn_inference_f32.patch, Libraries/oneDNN/tutorials/profiling/profile_utils.py, Libraries/oneDNN/tutorials/q, Libraries/oneDNN/tutorials/tutorial_analyze_isa_with_dispatcher_control.ipynb, Libraries/oneDNN/tutorials/tutorial_getting_started.ipynb, Libraries/oneDNN/tutorials/tutorial_simple_model.ipynb, Libraries/oneDNN/tutorials/tutorial_verbose_jitdump.ipynb
The change includes enablement for [the oneDNN tutorial](https://github.com/louie-tsai/oneAPI-samples/blob/master/Libraries/oneDNN/tutorials/tutorial_verbose_jitdump.ipynb) support a large oneDNN log file.
Without this change, the tutorial will crash when users input a large oneDNN log file.
This change also includes a fix for IPS#00555843. The issue only happens on DevCloud. Users wouldn't face any runtime issues on their local machine.
- [X ] Command Line
=> fix issues : no crash for parsing a large log file and IPS#00555843

DirectProgramming/C++/StructuredGrids/iso3dfd_omp_offload/include/iso3dfd.h, DirectProgramming/C++/StructuredGrids/iso3dfd_omp_offload/src/iso3dfd.cpp, DirectProgramming/C++/StructuredGrids/iso3dfd_omp_offload/src/iso3dfd_verify.cpp, DirectProgramming/C++/StructuredGrids/iso3dfd_omp_offload/src/utils.cpp
The array offset might be negative value but its type is "unsigned int", so it gets incorrect address of array element. Fixed by using "size_t" type for the related variables.
- [X ] Command Line
=> Fix iso3dfd_omp_offload issue

Libraries/oneTBB/tbb-async-sycl/src/tbb-async-sycl.cpp, Libraries/oneTBB/tbb-task-sycl/src/tbb-task-sycl.cpp
Fix tbb-async-sycl sample on Linux with oneAPI compiler 2021.2.0 (2021.x.0.0121).
=> Add numeric header for std::iota

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/compute_units/src/compute_units.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/double_buffering/src/double_buffering.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/explicit_data_movement/src/explicit_data_movement.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/loop_carried_dependency/src/loop_carried_dependency.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/n_way_buffering/src/n_way_buffering.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/onchip_memory_cache/src/onchip_memory_cache.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/optimize_inner_loop/src/optimize_inner_loop.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/pipe_array/src/pipe_array.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/shannonization/src/IntersectionKernel.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/triangular_loop/src/triangular_loop.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/buffer_kernel.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/restricted_usm_kernel.hpp, DirectProgramming/DPC++FPGA/Tutorials/Features/fpga_reg/src/fpga_reg.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/src/kernel_args_restrict.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_coalesce/src/loop_coalesce.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_ivdep/src/loop_ivdep.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_unroll/src/loop_unroll.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/lsu_control/src/lsu_control.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/max_concurrency/src/max_concurrency.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/max_interleaving/src/max_interleaving.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/memory_attributes/src/memory_attributes.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/pipes/src/pipes.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/speculated_iterations/src/speculated_iterations.cpp, DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fast_recompile/src/kernel.cpp, DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/src/fpga_compile.cpp, DirectProgramming/DPC++FPGA/Tutorials/Tools/dynamic_profiler/src/dynamic_profiler.cpp, DirectProgramming/DPC++FPGA/Tutorials/Tools/system_profiling/src/double_buffering.cpp, DirectProgramming/DPC++FPGA/Tutorials/Tools/use_library/src/use_library.cpp
Minor improvements the DPC++ files for FPGA tutorial samples, in response to user feedback.
- Motivate the forward declaration of the kernel name in each tutorial
- Improve the explanatory comments in fast_recompile and fpga_compile
- Remove a stray namespace backwards compatibility block (no longer needed)
=> Readability improvements to FPGA tutorials samples C++ files

Libraries/oneMKL/block_cholesky_decomposition/dpbltrs.cpp, Libraries/oneMKL/block_lu_decomposition/dgeblttrs.cpp
The block_cholesky_decomposition and block_lu_decomposition samples from oneMKL incorrectly handle events during the solve stage.  This may be observed when using the cpu device.  This change fixes the event handling.
Tested using both the default DPC++ device as well as explicitly setting SYCL_DEVICE_TYPE to cpu and gpu.
=> [oneMKL] Fix event handling in block LU and Cholesky solve steps

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt
The GZIP makefile has long been using an incorrect flag to dpcpp, resulting in slightly incorrectly RTL and therefore unexpected FMAX for the given seed. This change fixes the flag.
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X  ] Command Line
=> Change to -fintelfpga flag for GZIP

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/double_buffering/src/double_buffering.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/n_way_buffering/src/n_way_buffering.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/onchip_memory_cache/src/onchip_memory_cache.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/triangular_loop/src/triangular_loop.cpp, DirectProgramming/DPC++FPGA/Tutorials/Tools/system_profiling/src/double_buffering.cpp
Signed-off-by: Alain Lou alain.lou@intel.com
This is for FPGA tutorial code samples.
Instead of using unique_ptr, stack allocate sycl::queue directly. @keryell mentioned it already has share_ptr semantics under-the-hood. This way we'll have less confusion about how to use sycl.
[ X ] Bug fix (non-breaking change which fixes an issue)
[ X ] Command line
=> Remove unique_ptr to sycl::queue in some FPGA samples

Libraries/oneMKL/black_scholes/black_scholes.cpp, Libraries/oneMKL/block_cholesky_decomposition/dpbltrf.cpp, Libraries/oneMKL/block_cholesky_decomposition/dpbltrs.cpp, Libraries/oneMKL/block_cholesky_decomposition/factor.cpp, Libraries/oneMKL/block_cholesky_decomposition/solve.cpp, Libraries/oneMKL/block_lu_decomposition/dgeblttrf.cpp, Libraries/oneMKL/block_lu_decomposition/dgeblttrs.cpp, Libraries/oneMKL/block_lu_decomposition/factor.cpp, Libraries/oneMKL/block_lu_decomposition/solve.cpp, Libraries/oneMKL/computed_tomography/computed_tomography.cpp, Libraries/oneMKL/matrix_mul_mkl/matrix_mul_mkl.cpp, Libraries/oneMKL/monte_carlo_european_opt/mc_european.cpp, Libraries/oneMKL/monte_carlo_european_opt/mc_european_usm.cpp, Libraries/oneMKL/monte_carlo_pi/mc_pi.cpp, Libraries/oneMKL/monte_carlo_pi/mc_pi_device_api.cpp, Libraries/oneMKL/monte_carlo_pi/mc_pi_usm.cpp, Libraries/oneMKL/random_sampling_without_replacement/lottery.cpp, Libraries/oneMKL/random_sampling_without_replacement/lottery_device_api.cpp, Libraries/oneMKL/random_sampling_without_replacement/lottery_usm.cpp, Libraries/oneMKL/sparse_conjugate_gradient/sparse_cg.cpp
This PR removes old code that was used to support a previous oneMKL beta, prior to oneAPI header restructuring.
=> Remove beta compatibility code from oneMKL samples

AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/CMakeLists.txt, AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/README.md
To simplify the use of the PointPillars sample we added the following improvements
- Removed the need to download model files manually. This happens now automatically via cmake
- Clean up of compiler flags
=> Simplified build process of PointPillars sample

Libraries/oneVPL/dpcpp-blur/README.md, Libraries/oneVPL/dpcpp-blur/dpcpp-blur.vcxproj, Libraries/oneVPL/dpcpp-blur/src/dpcpp-blur.cpp, Libraries/oneVPL/hello-decode/CMakeLists.txt, Libraries/oneVPL/hello-decode/README.md, Libraries/oneVPL/hello-decode/hello-decode.vcxproj, Libraries/oneVPL/hello-decode/src/hello-decode.cpp, Libraries/oneVPL/hello-encode/README.md, Libraries/oneVPL/hello-encode/hello-encode.vcxproj, Libraries/oneVPL/hello-encode/src/hello-encode.cpp, Libraries/oneVPL/hello-vpp/README.md, Libraries/oneVPL/hello-vpp/hello-vpp.vcxproj, Libraries/oneVPL/hello-vpp/src/hello-vpp.cpp
This is coupled with 2021.2.2 component release.
Import lib name has been changed for oneVPL 2021.2.2.  This impacts solution files since they require explicit file names to find libraries as opposed to using package configuration methods.
Ensure implementation supports 2.0 API
The oneVPL dispatcher has been extended to support hardware implementations with API versions lower than 2.0. Samples now correctly follow the oneVPL specification and check for implementation capabilities explicitly instead of assuming the first implementation found supports API 2.0.
=> Update oneVPL samples to support 2021.2.2

DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/src/CMakeLists.txt
Signed-off-by: Abhishek Tiwari <abhishek2.tiwari@intel.com>
The -fno-fast-math flag was not being propagated to the required sub-commands of the multi-command sequence that generates the FPGA bitstream.
This change is a simple fix, it adds the flag to the right Cmake variable to ensure that it is correctly passed to all the commands. 
Without this fix the generated FPGA binary will not achieve the advertised performance on the Arria10 PAC board.
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] Command Line
- [ X ] oneapi-cli
=> [QRD-FPGA] Correctly pass the floating point optimization flag to FPGA compile step.

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/Makefile
Makefile for MandelbrotOMP sample contains the executable name of another sample: MergeSort instead of Mandelbrot.
Makefile for Mandelbrot is updated to product the executable with Mandelbrot name.
The logic of sample is not changed. Just renaming the output executable.
=> MandelbrotOMP: fix in executable name

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/sample.json, DirectProgramming/DPC++/CombinationalLogic/mandelbrot/sample.json, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/sample.json, DirectProgramming/DPC++/N-BodyMethods/Nbody/sample.json
Mandelbrot, vector-add, Nbody samples are good for showcasing the features of Intel Advisor. The lists of categories for these samples are extended with "Toolkit/oneAPI Tools/Advisor". This change allows to show the mentioned samples in 2 places of the samples tree: in their actual location (see categories in sample.json before change) and in Advisor part of tree without source code duplication. The logic of samples is not changed.
=> Mandelbrot, vector-add, Nbody samples are marked as Common+Advisor

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzip.cpp
**Description**
Fix number of reordering units for gzip-LL. Fix free() call in gzip.cpp to remove warning.
GZIP-LL was mistakenly using 6 reordering unit which is not necessary since we only have 1 global memory port (host memory), so this has been removed.
A call to free() in gzip.cpp is causing compiler warnings, this is now fixed.
Fixes # (issue)
**Type of change**
[ X] Bug fix (non-breaking change which fixes an issue)
**How Has This Been Tested?**
Ran GZIP regtest
=> Fixes to FPGA GZIP Reference Design performance and warnings

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/db_utils/fifo_sort.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query1/query1_kernel.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/StreamingQRD.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/src/qrd.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/shannonization/src/IntersectionKernel.hpp
Change [[intel::ii]] to [[intel::initiation_interval]] since the former syntax is deprecated and produces a warning as of (upcoming) release 2021.3. 
None
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration: 
Ran the original and changed example designs with 2021.3. The original versions will emit a deprecation warning for ii, whereas 2021.3 will accept them without any warnings. I observed the impact of this attribute and verified that the compiler is behaving in the way that is expected (validated using the HTML reports).
=> Change intel::ii attribute to intel::initiation_interval in all FPGA code samples

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/InputDemux.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/Transpose.hpp
Removed intel::ii which is deprecated as of 2021.3.  These files were missed in PR #482.
Add -Werror so that warnings can not slip in to this sample undetected in the future.
None
Compiled fpga_emu target with latest 21.3 SYCL resource, no warnings generated.
=> Change deprecated intel::ii to intel::initiation_interval in two files in FPGA mvdr_beamforming sample

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/FakeIOPipes.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/mvdr_beamforming.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/io_streaming/src/FakeIOPipes.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/io_streaming/src/HostSideChannel.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/io_streaming/src/LoopbackTest.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/io_streaming/src/SideChannelTest.hpp
FakeIOPipes no return a pair of events: the DMA event (a noop for USM host allocations) and the
kernel event. This allows the user of the FakeIOPipe to be more fine
grain on what they wait for. Used this in MVDR to not include the DMA
events in the throughput calculation for non-USM boards.
None
Tested both changed tests in emulation for USM and non-USM boards.
=> Changed FakeIOPipes for MVDR and IO streaming samples

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/CMakeLists.txt
Our compile/links flags as specified in the CMAKE are a bit confusing for some flows.  Link flags are actually used for compiling when targeting real hardware or reports.
Tested emulation and reports (which checks the HW compile/link flags).
=> Fixing hardware and simulator compile/link flags for FPGA Reference Design mvdr_beamforming

DirectProgramming/DPC++FPGA/Tutorials/Features/memory_attributes/README.md
This change accomplishes four small formatting issues with the memory_attributes README:
- Updated instances of `intelfpga::` to `intel::`
- Updated instances of `register` to `fpga_register`
- Updated instances of `memory` to `fpga_memory`
- Updated the table of memory attributes so that the attributes are in code font instead of just the normal font
Fixes Issue# 
N/A
I've verified that the README file produced looks as expected.
=> FPGA: memory_attributes README fix

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/StreamingQRD.hpp
The dpcpp front-end is adding a check in 2021.3 that disallows recursive functions inside kernels.  The check is currently overly restrictive, and disallows static compile-time recursive functions.  This code change converts a static compile time function to a loop instead of a recursive implementation to avoid this issue.
Fixes Issue# CMPLRLLVM-27921
None
=> Removed recursive function from kernel in FPGA Reference Design mvdr_beamforming

.github/ISSUE_TEMPLATE/new_sample.md, DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/README.md, DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/sample.json
This is a change to original sample. Originally it was written for Mac only, I am extending the sample.json so that it will work for Linux as well.
Also fixing a template
Fixes Issue# 
N/A
=> Update openOMP to compile for Linux

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/README.md
Signed-off-by: Abolfazl Shahbazi <abolfazl.shahbazi@intel.com>
This fixes the malformed title of: https://github.com/oneapi-src/oneAPI-samples/tree/master/AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8
=> Fix some formatting issue in README.md

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/buffered_host_streaming/buffered_host_streaming.vcxproj
Removing board argument from VCXPROJ file. The user is explained to do this themselves. This falls in line with the other tutorials.
Locally
=> Removing board specification from VCXPROJ file

AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/README.md
I added a jump link at the top to skip to the DevCloud directions. I am not sure if there are steps required before running a sample on the devcloud. For example, does the user need to build daal4py for CPU or activate conda before using the DevCloud? If the answer is yes, then the jump link to the DevCloud directions need to move down below the required steps.
1. If your sample runs in batch mode, please delete …
=> node and mode update for daal4py readme

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/n_way_buffering/src/CMakeLists.txt
Changed the CMakeLists.txt for the n_way_buffering tutorial. -lpthread was erroneously added back as a compiler argument for Windows and reports. I've removed it.
Ran the regtest in Windows it now passes.
Tested Linux too.
=> Fix for Windows linking error to FPGA n_way_buffering sample

AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/CMakeLists.txt, AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/src/pointpillars/nms.cpp, AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/src/pointpillars/postprocess.cpp
- include missing <numeric> header in NMS
- tested with oneAPI 2021.2
- changed include order in postprocess.cpp to ensure proper TBB
handling with C++17
=> Use C++17 for LiDAR-Object-Detection Sample

AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/README.md
The ''source activate tensorflow'' step was missing from the instructions to "run from a local terminal."
Fixes Issue# 
None
- [x ] Command Line
=> Added in activate tensorflow step

DirectProgramming/DPC++FPGA/Tutorials/Features/loop_ivdep/README.md, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_ivdep/src/loop_ivdep.cpp
Signed-off-by: horobert <horobert@intel.com>
Added "array" parameter to ivdep attribute usage in the tutorial in accordance with FPGA best practices. Updated README.md to reflect this change and to describe this best practice. Previously (prior to 2021.4), the array parameter feature was not fully functional.
none
Tested using the emulator and report flows described in the README
=> Update FPGA loop_ivdep tutorial to use the recommended best practice

AI-and-Analytics/End-to-end-Workloads/LidarObjectDetection-PointPillars/sample.json, AI-and-Analytics/End-to-end-Workloads/README.md, DirectProgramming/C++/Jupyter/OpenMP-offload-training/README.md, DirectProgramming/C++/Jupyter/OpenMP-offload-training/sample.json, DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/README.md, DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/sample.json, DirectProgramming/DPC++/OpenCLInterop/README.md, DirectProgramming/DPC++/OpenCLInterop/sample.json, DirectProgramming/Fortran/Jupyter/OpenMP-offload-training/README.md, DirectProgramming/Fortran/Jupyter/OpenMP-offload-training/sample.json
The changes required are part of the `sample.json` file, and do not modify the actual samples in any way. Also cleaned up the associated README.md files for improved readability when being viewed as a text file, as opposed via a Markdown viewer.
Fixes Issue# ONSAM-1393
N/A
View the sample tree in the `oneapi-cli` browser. Best to use `oneapi-cli --ignore-os` in order to see all available samples, regardless of your host OS.
- [NA] Command Line
- [NA ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used
=> ONSAM-1393: Correct "categories" attribute for proper display in the samples browsers.

DirectProgramming/DPC++FPGA/Tutorials/Features/lsu_control/src/lsu_control.cpp
Signed-off-by: aditi.kumaraswamy <aditikum@scc823113.sc.intel.com>
LSU control FPGA tutorial uses the deprecated "noinit", changing to the new "no_init"
Fixes Issue
ONSAM-1391
=> [FPGA] Changing the deprecated noinit to new no_init 

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/SteeringVectorGenerator.hpp
replace atomic_fence with sycl::ONEAPI::atomic_fence
Fixes Issue# 
ONSAM-1396
=> Update depricated atomic_fence to sycl::ONEAPI::atomic_fence in mvdr_beamforming FPGA design

DirectProgramming/DPC++/N-BodyMethods/Nbody/README.md
Fixed two typos in the Nbody readme.
Fixes Issue# 
- [x ] Documentation
- [ x] VSCode
=> Nbody Readme fix typo

DirectProgramming/C++/ParallelPatterns/openmp_reduction/sample.json, DirectProgramming/DPC++FPGA/ReferenceDesigns/crr/sample.json, DirectProgramming/Fortran/CombinationalLogic/openmp-primes/sample.json, DirectProgramming/Fortran/DenseLinearAlgebra/optimize-integral/sample.json, DirectProgramming/Fortran/DenseLinearAlgebra/vectorize-vecmatmult/sample.json
Several samples (Fortran) had missing GUIDs and found 2 GUIDs that were duplicated
Duplicate GUIDS were with samples:
- CRR and  Complex_Mult
- openMP Reduce and DPC Reduce
=> GUIDS repairs

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query11/query11_kernel.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query12/query12_kernel.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query9/query9_kernel.cpp
Small change that forces II=1 to all main processing loops. This works around a regression from a recent xmain integration AND is more clear since we know we want II=1 on all of these loops.
=> Small update to FPGA DB design

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/Makefile, DirectProgramming/C++/GraphTraversal/MergesortOMP/Makefile
Signed-off-by: Sergey Kiselev <sergey.kiselev@intel.com>
Modify Makefile to work with oneAPI 2021.3:
* Switch from icpc compiler to icpx
* Add -ipo flag to the linker to match the compiler interprocedural optimization settings
Fixes Issue# 
=> Switch to icpx compiler; Add -ipo flag to the linker

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/zero_copy_data_transfer.vcxproj
Removes -Xsboard argument from VCXPROJ file. This is inline with the other tutorials.
=> Small change to zero_copy_data_transfer tutorial VCXPROJ

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/FakeIOPipes.hpp
Fixed a compile issue with MVDR. The compiler is generating a header file that was searching the global namespace for a KernelID that was a class member of a class. I changed the code to just used the passed in Id. This both fixes the compile and produces much nicer reports since the amount of name mangling in the kernel name is reduced. I also removed the Id parameter from the `ProducerConsumerBaseImpl` because it was unused.
I tested the functionality in emulation.
=> Fixed for compile error in MVDR

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query11/query11_kernel.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query12/query12_kernel.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query9/query9_kernel.cpp
To align with other designs, I explicitly wait on all events. None of the kernels are intended to run forever, so this change should do nothing but make sure no kernels are hanging.
=> Updating FPGA design DB to wait on ALL events

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/FakeIOPipes.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/io_streaming/src/FakeIOPipes.hpp
In FakeIOPipes.hpp, when two Producers or Consumers that use the same type are used in the same scope, their underlying base classes alias to each other and cause a runtime error when trying to initialize the second instance.  That error does not occur in the two samples that use FakeIOPipes, but it does happen in a new design (not yet comitted) that uses them.  This bug fix is for anyone who wants to reuse the FakeIOPipes in their own designs.
Also converted all line endings to UNIX style, so recommend ignoring whitespace changes when reviewing.
=> Add ID field back to ProducerConsumerBaseImpl in FakeIOPipes.hpp

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/io_streaming/src/LoopbackTest.hpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/io_streaming/src/SideChannelTest.hpp
SYCL kernel names need to be forward declarable. The kernels in this tutorial were being falsely compiled until a recent change. This PR fixes the compile error.
Built emulation and reports.
=> Fix for FPGA io_streaming design breaking due to non-forward declarable kernel name

DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/Makefile.win
Signed-off-by: Khalik Kasimov <khalik.kasimov@intel.com>
This change includes update for vector-add sample to use dpcpp-cl for Windows instead of dpcpp for upcoming release.
The change is introduced as the Windows version of the sample uses Windows specific options.
Note: this PR does not include changes for FPGA Makefile for Windows.
Tested as described in a sample README.md
=> vector-add: use dpcpp-cl for Windows version of the sample

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzipkernel.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzipkernel_ll.cpp
We were overrunning reads to a pointer in one of the kernels that caused an intermittent segfault in emulation. In theory, this segfault could occur in hardware too, but didn't seem to happen. We also didn't see segfaults in emulation or hardware for regular gzip, but we were overrunning the pointer, so I fixed that too.
=> Fixing intermittent segfaults in gzip design

DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/README.md, DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/src/simple-add-buffers.cpp, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/README.md, DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/src/vector-add-buffers.cpp
With oneAPI 2021.4 the argument for accessors was changed from 'noinit' to 'no_init'. The change was derived from a change between the SYCL 2020 provisional spec and that of the 2020Rev3 spec
=> Update non FPGA samples no_init

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/db_query1.vcxproj, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/db_query11.vcxproj, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/db_query12.vcxproj, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/db_query9.vcxproj, DirectProgramming/DPC++FPGA/ReferenceDesigns/merge_sort/merge_sort.vcxproj, DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/mvdr_beamforming.vcxproj, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/shannonization/shannonization.vcxproj, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/simple_host_streaming/simple_host_streaming.vcxproj
The VS .vcxproj file uses "AdditionalOptions" field for compile options, and "SpecifyDevCmplAdditionalOptions" for link options. However, there is no way to specify it to use options when compiling for emulation vs reports. This causes emulation compiles to fail since they are passed a "-Xs" argument that it doesn't understand. This change removes a lot of -Xs arguments from the vcxproj file that are not necessary.
=> Removing unnecessary -Xs* options from VCXPROJ files.

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/mvdr_beamforming.cpp
We .wait() on an event that is declared inside an if-def, but didn't wrap the wait in an if-def.
=> Small change to MVDR to wrap stuff correctly in if-defs for real vs fake IO pipes

Publications/DPC++/Ch07_buffers/fig_7_10_accessors.cpp
Changing a sample to reflect changes in 2021.4 noinit vs no_init
2021.4
=> Update fig_7_10_accessors.cpp to use no_init instead of depricated noinit

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/buffered_host_streaming/README.md, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/buffered_host_streaming/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/simple_host_streaming/README.md, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/simple_host_streaming/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/README.md, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/CMakeLists.txt
Update CMakeLists.txt to error out if they select a board without USM support.
Also added a method to override this check for custom boards.
Added clearer instructions in the READMEs of these designs on the limitations to USM and how to override the check for custom BSPs.
=> Updating all FPGA tutorials that require USM support

DirectProgramming/DPC++/ProjectTemplates/cmake-fpga/src/main.cpp, DirectProgramming/DPC++/ProjectTemplates/cmake-gpu/src/main.cpp, DirectProgramming/DPC++/ProjectTemplates/makefile-fpga/src/main.cpp, DirectProgramming/DPC++/ProjectTemplates/makefile-gpu/src/main.cpp
The ProjectTemplates samples were failing at runtime with 2021.4 compiler.  Moved the declaration of the kernel name class to be global to fix the issue.
Also cleaned up depricated syntax for the FPGA versions of the templates.
- ran cmake (when present) and make on all updated samples, compiles all passed with no syntax warnings in 2021.4
- executed the emulator targets for the fpga samples, they now work
=> Declare kernel name in global namespace and update deprecated syntax in ProjectTemplates samples.

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt
Removing old compile flag from GZIP CMakeLists.txt that was causing build errors on some machines.
=> Removing old compile flag from GZIP CMakeLists.txt

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/Makefile, DirectProgramming/C++/CompilerInfrastructure/Intrinsics/Makefile, DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_dot_sample.cpp, DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_double_sample.cpp, DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_ftz_sample.cpp, DirectProgramming/C++/GraphTraversal/MergesortOMP/Makefile, DirectProgramming/C++/GraphTraversal/MergesortOMP/src/merge_sort.cpp, DirectProgramming/DPC++/SpectralMethods/DiscreteCosineTransform/src/DCT.cpp, DirectProgramming/DPC++/SpectralMethods/DiscreteCosineTransform/src/DCT.hpp
Found links in several samples to be no longer valid, so I removed the license at the head of the affected files. 
The finding is that we don't need the headers, so long as each sample has a license.txt file, so removing is not going to cause issues
Fixes Issue# ONSAM-1414
=> ONSAM-1414 Broken Link in Headers

Libraries/oneMKL/black_scholes/black_scholes.cpp, Libraries/oneMKL/black_scholes/code_wrapper.tpp
Recent dpcpp compilers issue a deprecation notice for get_cl_code(). This patch calls new code() api when possible, falling back to get_cl_code() when not.
- [ X ] Command Line (linux)
=> fix deprecation notice

Libraries/oneCCL/oneCCL_Getting_Started/CMakeLists.txt, Libraries/oneCCL/tutorials/oneCCL_Getting_Started.ipynb, Libraries/oneDNN/tutorials/CMakeLists.txt, Tools/Advisor/matrix_multiply_advisor/CMakeLists.txt, Tools/IoTConnectionTools/azure-iothub-telemetry/cpp/CMakeLists.txt
Update CMakeLists
Change minimum requaired versions to 3.4
Update CMakeLists
Change minimum requaired versions to 3.4
None
=> Update CMakeLists, minimum required version

DirectProgramming/DPC++/ParallelPatterns/histogram/src/main.cpp
Added additional buffer to fix out put of function dense_histogram.
Added two vector variables dense and sparse in main() to prevent sorted input vector when passed to
function sparse_histogram.
Fixes Issue# 
See above.
None. 
=> Update for dense bins

DirectProgramming/DPC++/N-BodyMethods/Nbody/src/GSimulation.cpp
Namespace change from ONEAPI to ext::oneapi for Nbody sample
Fixes Issue# ONSAM-1433
No external dependencies
=> Fixed the namespace issue repported in ONSAM-1433

Tools/GPU-Occupancy-Calculator/index.html
Fixed minor font alignment issue in GPU Occupancy Calculator
- Tested on Browser
=> Fixed font alignment in GPU Occupancy Calculator

DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/src/CMakeLists.txt
Signed-off-by: Aditi Kumaraswamy <aditi.kumaraswamy@intel.com>
Reverting QRD seed to 13 to get maximum performance. 
Ran a large sweep of regression sweeps.
=> Reverting QRD design default seed change

Libraries/oneCCL/oneCCL_Getting_Started/README.md, Libraries/oneCCL/oneCCL_Getting_Started/sample.json, Libraries/oneCCL/tutorials/oneCCL_Getting_Started.ipynb
oneccl 2021.5 release introduces some changes for both folder name and [cmake configuration](https://oneapi-src.github.io/oneCCL/introduction/installation.html#custom-installation).
To let samples run, we need to change samples for those new changes in oneccl release.
Fixes Issue#  https://jira.devtools.intel.com/browse/ONSAM-1439
=> fixes for ONSAM-1439 to address changes in oneccl 2021.5 release

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/Makefile, DirectProgramming/C++/CompilerInfrastructure/Intrinsics/Makefile, DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_dot_sample.cpp, DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_double_sample.cpp, DirectProgramming/C++/CompilerInfrastructure/Intrinsics/src/intrin_ftz_sample.cpp, DirectProgramming/C++/GraphTraversal/MergesortOMP/Makefile, DirectProgramming/C++/GraphTraversal/MergesortOMP/src/merge_sort.cpp, DirectProgramming/DPC++/SpectralMethods/DiscreteCosineTransform/src/DCT.cpp, DirectProgramming/DPC++/SpectralMethods/DiscreteCosineTransform/src/DCT.hpp, Libraries/oneMKL/black_scholes/black_scholes.cpp, Libraries/oneMKL/black_scholes/code_wrapper.tpp
A couple of commits were pushed to master before development  branch has been created. so pushing the initial commits to development.
=> Update initial master commits to development branch

Tools/ApplicationDebugger/array-transform/README.md, Tools/ApplicationDebugger/jacobi/README.md
README changes only.  Applying the same changes from PR792 that were applied to the development branch directly to the master branch, as the development branch has ended up in a messy state for the moment.
=> Re-creating changes from PR 792 to apply directly to master branch

DirectProgramming/DPC++FPGA/Tutorials/Features/stall_enable/src/stall_enable.cpp
Fix a deprecated message that will cause problems later when we die if there are any warnings.  Replace access::target::global_buffer with access::target::device
Ran locally:
=> FPGA sample stall_free: Remove deprecated access::target::global_buffer

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/README.md, DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt
Update Cmake file to build either high bandwidth or low latency variant based on a flag passed in to CMAKE, instead of making separate Makefile targets for the Low Latency version.
=> FPGA gzip Cmake update

DirectProgramming/DPC++FPGA/ReferenceDesigns/anr/src/anr.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/anr/src/dma_kernels.hpp
Using `q.single_task` in place of `q.submit` when the handler is not used.
=> ANR code style update

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/README.md
Update README file to fix a duplicate line, and provide output that matches the current code and gives a throughput number from a run on the FPGA instead of on the emulator.
No testing, README update only.
=> Update FPGA mvdr_beamforming design README with more typical output from a run on the FPGA.

DirectProgramming/DPC++FPGA/Tutorials/Features/mem_channel/README.md, DirectProgramming/DPC++FPGA/Tutorials/Features/mem_channel/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/mem_channel/src/mem_channel.cpp
Update messages printed when running the mem_channel tutorial, and update the sample output in the README file to match.
Also did some minor clean-up in the CMake file.
=> Update FPGA mem_channel tutorial output message and minor cmake clean up

DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/README.md, DirectProgramming/DPC++FPGA/Tutorials/Features/read_only_cache/src/read_only_cache.cpp
Reducing the size of the output and updating the sample output in the README file to match.  The smaller buffer size allows this sample to pass on Windows.
=> Reduce read only cache output size

DirectProgramming/DPC++FPGA/Tutorials/Features/dsp_control/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/dsp_control/License.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/dsp_control/README.md, DirectProgramming/DPC++FPGA/Tutorials/Features/dsp_control/dsp_control.sln, DirectProgramming/DPC++FPGA/Tutorials/Features/dsp_control/dsp_control.vcxproj, DirectProgramming/DPC++FPGA/Tutorials/Features/dsp_control/sample.json, DirectProgramming/DPC++FPGA/Tutorials/Features/dsp_control/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/dsp_control/src/dsp_control.cpp
This FPGA tutorial demonstrates how to set the implementation preference for certain math operations (addition, subtraction, and multiplication by a constant) between hardened DSP blocks and soft logic.
Administrative
Review
=> New FPGA Code Sample "DSP Control"

DirectProgramming/DPC++/ParallelPatterns/dpc_reduce/src/main.cpp
This is related to issue #750. The following comment was confusing and potentially misleading, so it was deleted after consulting with the author of the code: "Since we are using JIT compiler for samples, we need to run each step once to allow for compile to occur before we time execution of function."
=> Deleted confusing comment

DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
Clarify that -DFPGA_EMULATOR is specific to this particular code, not an option that is required for all emulator compiles.
README change only, no testing done.
=> FPGA sample fpga_compile minor readme update

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/CMakeLists.txt
Removing 'Manually-specified variables were not used by the project' warning from CMake
=> Removing CMake warning for zero_copy_data_transfer

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/gzipkernel_ll.cpp
This PR: https://github.com/oneapi-src/oneAPI-samples/pull/842 placed the PipeArray class in the fpga_tools namespace, but did not update all instance of references to PipeArray in the low latency variant of the gzip design.  This PR fixes that oversight.
Compiled the low latency variant of the gzip design by running CMAKE with -DLOW_LATENCY=1 as specified in the README file for that design.
=> Bug fix for FPGA sample gzip: add fpga_tools namespace to all instances of PipeArray in the low latency design variant

DirectProgramming/DPC++FPGA/Tutorials/Tools/dynamic_profiler/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/Tools/system_profiling/CMakeLists.txt
This change adds an early fatal error on Windows to two code samples that do not support Windows compilation. This is to make sure users who didn't notice the code sample doesn't support windows will not accidentally try running it only to hit issues further in.
N/A
Attempted to build the two code samples with cmake on both linux and windows in command line. Confirmed no issues introduced in Linux, and on Windows the sample immediately errors out when trying to cmake.
=> [FPGA] Add proper 'can't run on windows' error to FPGA tools tutorials

DirectProgramming/DPC++FPGA/include/README.md
Removes the mention of the utils.hpp file in the include folder readme as the file does not exits.
Reorganizes the table listing the files that are in the include folder.
Review
=> FPGA: Update the include folder readme

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/buffered_host_streaming/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/simple_host_streaming/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/CMakeLists.txt
Same as [this change](https://github.com/oneapi-src/oneAPI-samples/commit/95e618298f00be070c0a0b9810461a476b26ce9f).
Previous PR: #838.
=> Changing CMake file for USM-only tutorials to get rid of CMake warning

DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/README.md, DirectProgramming/DPC++FPGA/ReferenceDesigns/qri/README.md
This corrects the qrd and qri reference designs readmes.
The corrected part of the readme was mixing documentation of an older implementation of these designs with the current implementation.
Fixes Issue# 
Review
=> FPGA: Correct the qrd and qri readmes

DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/src/CMakeLists.txt
Signed-off-by: Yohann Uguen <yohann.uguen@intel.com>
When compiling on Windows, VS sets the default stack size of the resulting executable to 1MB.
This value is too small to store all the local variables of the large qrd design when targeting Stratix 10.
This change sets the stack size to 12MB, which is the default GCC value.
Ran both the emulator and the hardware flow for Arria 10 and Stratix 10 on Windows.
=> FPGA: adding stack size flag to windows linker for the qrd reference design

AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/sample.json
Signed-off-by: Dmitry Chigarev <dmitry.chigarev@intel.com>
This PR is supposed to fix [failing CI testing](https://github.com/oneapi-src/oneAPI-samples/pull/843#commitcomment-66044784) for Modin's getting started samples. The CI flow has been failing due to conda's failures during environment initialization inside the bash script (conda/conda#7980). The CI script was modified as follows to resolve the problem:
1. Source `conda.sh` before using conda to be able to activate environments inside a bash script (conda/conda#7980).
2. Use [`set -e`](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html#:~:text=%2De,function%20call%20completes.) at the beginning of the CI script to ease debugging if something goes wrong.
3. Install notebook's dependencies from …
=> MODIN: fix getting started samples testing in CI

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/README.md, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/sample.json, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/db.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/db_utils/Accumulator.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/db_utils/CachedMemory.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/db_utils/MapJoin.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/dbdata.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query11/pipe_types.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query11/query11_kernel.cpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query9/pipe_types.hpp, DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/query9/query9_kernel.cpp
This change addresses a functional bug found in DB/Q11 where ivdep was used improperly. We were using ivdep without a safelen (safe length), while the caching technique we were using meant that we needed a safelen equal to the size of the cache.
Fixing this uncovered some performance issue that were also fixed in this PR. The design is now functional and performing the same as it was before.
Additionally, I have added a line of output that prints the "queries per second"  to measure throughput.
=> Fixing functional issue in DB query 11

Libraries/oneMKL/computed_tomography/computed_tomography.cpp
Adds some additional input validation in BMP reading for the computed_tomography sample, for increased security.
=> computed_tomography: additional validation for input bitmap

DirectProgramming/DPC++/DenseLinearAlgebra/complex_mult/README.md, DirectProgramming/DPC++/DenseLinearAlgebra/complex_mult/build.sh, DirectProgramming/DPC++/DenseLinearAlgebra/complex_mult/run.sh
The DevCloud uses a batch system for processing. To get the samples to run, users need to know how to create the script or know how to request an interactive mode.
To make it easier for DevCloud users to run the sample, I created scripts to build (`build.sh`) and run (`run.sh`) on DevCloud. Proper documentation explaining the process has been added to README.md.
This is the first change for better integration of oneAPI samples repository with DevCloud. It will be later followed by others for the remaining samples, according to the guidelines from this PR.
Fixes Issue# 
Please describe the tests that you ran to verify your changes. …
=> Better integration of giuthub repo and Devcloud

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt
Updating seed for 2022.2 to meet published perf target
Ran oneapi_code_samples/gzip/gzip_high_bw and gzip_ll regtests and verified we get 11.0 GB/s and 7.0GB/s respectively
=> Update default seeds for FPGA gzip Reference Design for S10

Publications/DPC++/Ch19_memory_model_and_atomics/fig_19_7_avoid_data_race_with_atomics.cpp
atomic_ref is no longer extension
Fixes Issue# 
None
=> ONSAM-1467 atomic_ref is no longer extension

Libraries/oneDNN/tutorials/requirements.txt
add runipy for ONSAM-1465
add runipy as a required python package according to [ONSAM-1465](https://jira.devtools.intel.com/browse/ONSAM-1465)
Fixes Issue# [ONSAM-1465](https://jira.devtools.intel.com/browse/ONSAM-1465)
=> Update requirements.txt for ONSAM-1465

DirectProgramming/C++/CompilerInfrastructure/OpenMP_Offload_Features/README.md, DirectProgramming/C++/CompilerInfrastructure/OpenMP_Offload_Features/sample.json, DirectProgramming/C++/CompilerInfrastructure/OpenMP_Offload_Features/src/CMakeLists.txt
prog2 from CI automated test
There's a regression in how the compiler handles function pointers when offloading to GPU. Removing that sample from CI.
=> Removing Function Pointer from CI

DirectProgramming/DPC++FPGA/Tutorials/Features/pipes/src/pipes.cpp
Fixing a host call to std::iota in the FPGA pipes tutorial. Previously the call to iota didn't actually initialize anything.
Fixes #903
=> Fixed iota in FPGA pipes tutorial

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/buffered_host_streaming/src/streaming_with_api.hpp, DirectProgramming/DPC++FPGA/include/unrolled_loop.hpp
=> Fixing spelling of "lambda"

README.md
Fixing typo (extra parenthesis) on the "VTune Profiler" link
=> Fixing typo (extra parenthesis) on the "VTune Profiler" link

DirectProgramming/DPC++/ParallelPatterns/histogram/src/main.cpp
[oneDPL][examples] + fix a error (wrong size of passed sequence) in histogram example.
"The sum of accessRange and accessOffset should not exceed the range of buffer."
=> + fix a error (wrong size of passed sequence) in histogram example.

DirectProgramming/DPC++FPGA/Tutorials/Features/ac_int/src/ac_int.cpp
The ac_int tutorial shows how using this data type can improve the resource utilization of a design, by comparing the resource utilization of kernels such as ShiftOps and EfficientShiftOps. This change removes all loads from global memory, by changing the kernel inputs to be simple scalar kernel arguments instead of accessors. Area overhead is significantly reduced.
=> FPGA: Update ac_int tutorial to use scalar kernel arguments instead of accessors.

Libraries/oneDPL/maxloc_reductions/maxloc_usm.cpp
This PR adds use of more oneDPL functionality (default execution policy, blocking behavior) to reduce LOC of maxloc example (USM version).
=> Simplifications for oneDPL use of maxloc example

DirectProgramming/DPC++FPGA/Tutorials/Features/pipes/src/pipes.cpp
Signed-off-by: Justin Rosner <justin.rosner@intel.com>
This PR fixes array initialization in the pipes tutorial so that no integer overflow occurs, as signed integer overflow is undefined behaviour.
=> Fixing array initialization to prevent overflow

DirectProgramming/DPC++FPGA/ReferenceDesigns/anr/README.md, DirectProgramming/DPC++FPGA/ReferenceDesigns/cholesky/README.md, DirectProgramming/DPC++FPGA/ReferenceDesigns/cholesky_inversion/README.md, DirectProgramming/DPC++FPGA/ReferenceDesigns/crr/README.md, DirectProgramming/DPC++FPGA/include/README.md
First batch of changes related to DPC++ to SYCL changes in DPC++FPGA directories.
Begin work DPC++ to SYCL changes in DPC++FPGA directories.
File: ...\DirectProgramming\DPC++FPGA\include\README.md
Changes: Focus on changes from DPC++ to SYCL. Changed one instance of DPC++. Updated some formatting and fixed spelling errors.
File: **...\DirectProgramming\DPC++FPGA\ReferenceDesigns\anr\README.md**
Changes: Focus on changes from DPC++ to SYCL. (Full restructure later.) Removed or changed DPC++ instances in favor of SYCL. Corrected multiple formatting issues. Made modest/limited structural changes related to new template guidance. Updated the out-of-date documentation links and sections. Updated license information. Updated setting vars. Noted that link to precompiled binary does not work. …
=> DPC++ to SYCL changes in DPC++FPGA

DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/README.md
Corrected readme sample name to match what is shown in the sample.json file. Removed other instances of DPC++ that did not get changed previously. Made a few minor structural changes.
File: **...\oneAPI-samples\DirectProgramming\DPC++\DenseLinearAlgebra\simple-add\README.md**
Changes: Corrected readme sample name to match what is shown in the sample.json file. Removed other instances of DPC++ that did not get changed previously. Made a few minor structural changes. 
Fixes Issue# 
N/A
- [x ] VSCode
@ishaghosh27  - please review.
=> Updated readme to match sample name in .json file

DirectProgramming/DPC++/OpenCLInterop/README.md
Signed-off-by: Emmanuel Moncada <emmanuel.moncada27@gmail.com>
Updates the run command for the sample         ########OpenCLInterop
Fixes Issue #994 
None
1. navigate to DirectProgramming/DPC++/OpenCLInterop/ 
2. create a build dir `mkdir build`, then `cd build`
3. run `cmake ..` then `make`
4. running `make run_prog1` or `make run_prog2` (as per readme) will produce an error saying there are no matching targets.
5. running `make run` will run the program with the desired output.
=> Update run instructions for DPC++ OpenCL Interrogability Sample

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt
Was generating unwanted warnings, causing regtest to fail
Ran gzip emulator regtest and it now passes
=> gzip Remove -g0 from emu flags

DirectProgramming/DPC++/GraphAlgorithms/all-pairs-shortest-paths/CMakeLists.txt
Signed-off-by: Emmanuel Moncada <emmanuel.moncada27@gmail.com>
Sets compiler prior to project being configured so it actually takes effect.
Fixes Issue #1002 
None
running `mkdir build && cd build && cmake ..` now selects and configures dpcpp as the compiler to be used, shown by the output of running `cmake ..`
=> set compiler prior to project config

Tools/Advisor/matrix_multiply_advisor/README.md, Tools/ApplicationDebugger/array-transform/README.md, Tools/ApplicationDebugger/jacobi/README.md, Tools/Benchmarks/STREAM/README.md, Tools/Migration/folder-options-dpct/README.md, Tools/Migration/rodinia-nw-dpct/README.md, Tools/Migration/vector-add-dpct/README.md, Tools/VTuneProfiler/matrix_multiply_vtune/README.md
Final batch of DPC++-to-SYCL changes in README.md files.
Changing just DPC++ to SYCL where appropriate and updating branding to match legal requirements. No other restructuring except where absolutely essentials; fixed major content and formatting issues in multiple files. Fixed multiple branding issues. (Note: Excluded files in tool directory that did not contain "DPC++" instances.)
Updated the following files:
\oneAPI-samples\Tools\Advisor\matrix_multiply_advisor\README.md
\oneAPI-samples\Tools\ApplicationDebugger\array-transform\README.md
\oneAPI-samples\Tools\ApplicationDebugger\jacobi\README.md
\oneAPI-samples\Tools\Benchmarks\STREAM\README.md
\oneAPI-samples\Tools\Migration\folder-options-dpct\README.md
\oneAPI-samples\Tools\Migration\rodinia-nw-dpct\README.md …
=> Changing DPC++ to SYCL instances in Tools directory

DirectProgramming/DPC++/Jupyter/oneapi-essentials-training/07_DPCPP_Library/oneDPL_parallel_API.ipynb
Verbiage changes to oneDPL parallel API notebook . Small naming changes from from extension API to parallel API. No changes in code snippets
=> changes to oneDPL parallel API notebook

DirectProgramming/DPC++FPGA/ReferenceDesigns/mvdr_beamforming/src/mvdr_beamforming.cpp
The SYCL emulator seems to have changed it's default floating point behaviour, resulting in slightly higher noise in the final output.  Increase the allowable deviation from the expected result to account for this.
=> Increase allowable floating point rounding error in FPGA reference design mvdr_beamforming.

DirectProgramming/DPC++/DenseLinearAlgebra/jacobi_iterative/CMakeLists.txt, DirectProgramming/DPC++/GraphTraversal/bitonic-sort/CMakeLists.txt, DirectProgramming/DPC++/GraphTraversal/hidden-markov-models/CMakeLists.txt, DirectProgramming/DPC++/GraphTraversal/odd-even-merge-sort/CMakeLists.txt, DirectProgramming/DPC++/ParallelPatterns/PrefixSum/CMakeLists.txt, DirectProgramming/DPC++/ParallelPatterns/dpc_reduce/CMakeLists.txt, DirectProgramming/DPC++/ParallelPatterns/histogram/CMakeLists.txt, DirectProgramming/DPC++/ParallelPatterns/loop-unroll/CMakeLists.txt, DirectProgramming/DPC++/SparseLinearAlgebra/merge-spmv/CMakeLists.txt, DirectProgramming/DPC++/StructuredGrids/1d_HeatTransfer/CMakeLists.txt, DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/CMakeLists.txt, DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/CMakeLists.txt
Signed-off-by: Emmanuel Moncada <emmanuel.moncada@intel.com>
Updates all CMakeLists.txt for samples to set compiler prior to calling project() so that CMake selects the intended compiler.
None/N/A
Has been tested by running `cmake ..` from build directories in each of the samples under DirectProgramming/, and verifying that the selected compiler matches what is defined in its respective CMakeLists.txt, where previously other default compilers such as usr/bin/cc and user/bin/c++ were selected.
=> setting complier correctly in all samples using cmake

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/src/CMakeLists.txt
The db design was incorrectly using an hardcoded seed whereas the seed is already setup in SEED.
Fixes Issue# 
=> FPGA: fix misuse of SEED in the db design 

DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/README.md
Restructured and rewrote readme to align with new template.
Rewrote and restructured many instructions. Restructured to match new template. Updated branding and formatting (in some cases).
Fixes Issue# 
N/A
- [x ] oneapi-cli
- [x ] VSCode
=> Update the `Base: Vector Add` sample README.md

DirectProgramming/DPC++/N-BodyMethods/Nbody/README.md
Restructured to match new template. Corrected MS Build information. Updated formatting and branding.
Fixes Issue# 
N/A
=> Updated Nbody readme.md file

DirectProgramming/DPC++/StructuredGrids/iso2dfd_dpcpp/README.md
Restructured this sample to match the new sample, updated some branding, added some sections, and included Windows information as included in the samples.json file.
Fixes Issue# 
N/A
=> Updated ISO2DFD README.md file

DirectProgramming/DPC++/MapReduce/MonteCarloPi/src/monte_carlo_pi.cpp
Remove getchar() which prevents automatically exit of the application
Fixes Issue# 
=> ONSAM-1487

Publications/DPC++/Ch14_common_parallel_patterns/fig_14_15_local_stencil.cpp, Publications/DPC++/Ch14_common_parallel_patterns/fig_14_18-20_inclusive_scan.cpp, Publications/DPC++/Ch14_common_parallel_patterns/fig_14_22_local_pack.cpp, Publications/DPC++/Ch19_memory_model_and_atomics/fig_19_18_histogram.cpp
Removal of alias for local_accessor, access::target::local is now deprecated.
Fixes Issue# 
None
=> ONSAM-1506

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/README.md
The `db` design was missing instructions on how to generate the dataset with a scale factor of 1.
This PR improves the README to provide more detailed instructions.
=> FPGA: add instructions to generate the sf1 dataset in the db design

DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/src/CMakeLists.txt
A bug has been fixed in the release such that fast-math model does not drop Fmax and throughput anymore. Change to use default compiler configuration.
```
qor data change vs baseline
-----------------------------------------------------------
Fmax_kernel                     +1.834% (10)  -4.1% +29.0%
Kernel_area                     +2.843% (10)  -2.3% +48.8%
Logic_util                      -2.484% (10)  -4.4%  -0.8%
Silicon_area                    -1.089% (10)  -1.9%  -0.4%
Status                         <null>-1 (20)
passed+1
Throughput                      -0.201%  (9)  -1.9%  +1.0%
aoc_time                        +1.215% (10) -16.1% +19.5%
dsps                            +0.000% (10)  +0.0%  +0.0%
rams                            +0.000% (10)  +0.0%  +0.0%
registers …
```
=> remove fp-model precise and fp-relaxed in qrd design

DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/sample.json
It's all about the commas! Several "array of strings" were missing commas and had excess commas. Resulting in sample aggregator errors.
Sample aggregator, see statement above.
=> Fix badly formatted sample.json file in simple-add sample

DirectProgramming/DPC++FPGA/ReferenceDesigns/board_test/sample.json
The sample.json file contained a typo
=> FPGA: fix incorrect sample.json in board_test

DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/src/CMakeLists.txt
The `qactypes` flag was given at link time in the qrd reference design - which was generating warnings.
This PR removes this flag.
Fixes Issue#
=> FPGA: remove actypes link flag in qrd

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/scripts/freeze_optimize_v2.py
Signed-off-by: Om Thakkar <om.thakkar@intel.com>
While trying to freeze a (re-trained) TFHub keras model exported in the SavedModel format, the existing script was unable to convert the _Identity_ (and similar) ops to _Const_, which resulted into issues like fusions not happening in optimize_for_inference.
- Added a constant folding grappler pass before calling optimize_for_inference.
- New feature (non-breaking change which adds functionality)
- Command Line:
`python3 freeze_optimize_v2.py --input_saved_model_dir=<path-to-saved-model> --output_saved_model_dir=<path-to-generate-frozen-model>`
=> Fix to accommodate freezing a TensorFlow Hub Keras

Libraries/oneDNN/getting_started/README.md
Verified that DPCPP compiler works on windows (CMake v3.21+), and updated the getting_started sample readme to include instructions for dpcpp build.
N/A
- [ X] New feature (non-breaking change which adds functionality)
Used oneDNN instructions to build and compile using DPC++ on windows, works for CMake versions 3.21 and above.
=> Updated README - added dpcpp for windows support

DirectProgramming/DPC++FPGA/Tutorials/Features/loop_coalesce/README.md, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_coalesce/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_coalesce/src/loop_coalesce.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_initiation_interval/README.md, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_initiation_interval/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_initiation_interval/src/loop_initiation_interval.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/speculated_iterations/README.md, DirectProgramming/DPC++FPGA/Tutorials/Features/speculated_iterations/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/speculated_iterations/src/speculated_iterations.cpp
DirectProgramming/DPC++FPGA/Tutorials/Features/loop_initiation_interval
DirectProgramming/DPC++FPGA/Tutorials/Features/speculated_iterations
DirectProgramming/DPC++FPGA/Tutorials/Features/loop_coalesce
Add support for running loop_initiation_interval, loop_coalesce, and speculated_iterations on the FPGA simulator. Uses ext::intel::fpga_simulator_selector class to choose the simulator. Reduced data sizes to ensure reasonable execution times, as simulator is 1000-10000x slower than hardware
This has been run manually on Linux and Windows
=> [FPGA] FPGA Simulator support for loop_coalesce, loop_ii and spec itrs

DirectProgramming/DPC++FPGA/Tutorials/Features/pipes/src/pipes.cpp
This fixes an ambiguous reference that causes a compile time warning in this test. 
Also ran clang-format on this file. 
Fixes Issue# 14017777885
oneAPI 2023.0
=> Fix a ambigious reference to event_profiling

Tools/Migration/rodinia-nw-dpct/README.md, Tools/Migration/vector-add-dpct/README.md
Signed-off-by: Lu, John <john.lu@intel.com>
Add explanation of --in-root option for all README.md for SYCLomatic.  Make purpose of --in-root clear in every example.
=> Document --in-root option in all README.md for SYCLomatic

DirectProgramming/DPC++/StructuredGrids/iso3dfd_dpcpp/README.md
Restructured to match new template. Rewrote some sections for clarity. Updated headings and fixed formatting issues.
Fixes Issue# 
N/A
=> Update ISO3DFD readme - unguided version

AI-and-Analytics/Features-and-Functionality/IntelPython_XGBoost_daal4pyPrediction/ci_test.py, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_InferenceOptimization/scripts/ci_test.py
Updated CI scripts for AI Kit samples so they could find Jupyter notebooks to run from any pytest execution location. This is needed for samples validation automation.
Fixes Issue ONSAM-1538
=> Fix proposal for CI scripts

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/README.md, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/zero_copy_data_transfer.cpp
Add support for the FPGA simulator to run the code samples for zero_copy_data_transfer.
Uses ext::intel::fpga_simulator_selector class to choose the simulator.
Reduced data sizes to ensure reasonable execution times, as simulator is 1000-10000x slower than hardware
Fixes Issue# 
=> [FPGA] Added sim target to zero-copy-data-transfer

DirectProgramming/DPC++/DenseLinearAlgebra/vector-add/src/CMakeLists.txt
This change adds instructions for the users to modify the CMakeLists.txt of the vector-add sample.
The idea is to make the vector-add sample as the empty template sample for new users.
=> Add more comments in the vector-add CMakeLists.txt file

DirectProgramming/DPC++FPGA/Tutorials/Features/loop_fusion/src/CMakeLists.txt
The loop_fusion tutorial was missing the -fsycl compiler flag for its emulation and hw targets.
=> FPGA: fix missing -fsycl flag in loop_fusion

DirectProgramming/DPC++FPGA/ReferenceDesigns/anr/src/CMakeLists.txt
This change correctly sets the constexpr steps on Windows.
=> FPGA: Fix anr Windows compile flags

DirectProgramming/DPC++FPGA/Tutorials/Features/kernel_args_restrict/src/CMakeLists.txt
Fixed typo introduced by a merge conflict on previous submission
Fixes Issue# 
Administrative
Review
=> Fixed double definition of sim target

DirectProgramming/DPC++FPGA/Tutorials/Features/printf/README.md
DirectProgramming/DPC++FPGA/Tutorials/Features/printf
Printf generates a warning "compiler warning: argument 'llvm_fpga_printf_buffer_start' on component 'zts11basickernel' is never used by the component" that is not useful to the user. It is fixed for 2023.1, but the problem is still in 2023.0. The instruction would be added back in 2023.1.
=> Update readme since simulation is not fully supported for printf

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/double_buffering/README.md, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/double_buffering/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/double_buffering/src/double_buffering.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/n_way_buffering/README.md, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/n_way_buffering/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/n_way_buffering/src/n_way_buffering.cpp, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/simple_host_streaming/README.md, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/simple_host_streaming/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/simple_host_streaming/src/simple_host_streaming.cpp, DirectProgramming/DPC++FPGA/Tutorials/Features/printf/src/CMakeLists.txt
DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/double_buffering
DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/n_way_buffering
DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/simple_host_streaming
DirectProgramming/DPC++FPGA/Tutorials/Features/printf
Add support for the FPGA simulator to run the code samples for double_buffering, n_way_buffering, and simple_host_streaming.
Updated a comment in CMAKE file for printf since the comment is targeting simulation and not emulation.
Added additional changes to ensure the buffer and size can be allocated accordingly and can be executed within a reasonable period of time, as simulator is 1000-10000x slower than hardware.
Fixes Issue# 
Please delete options that are …
=> [FPGA] Added sim target to double_buffering, n_way_buffering, and simple_host_streaming

DirectProgramming/DPC++FPGA/Tutorials/DesignPatterns/optimize_inner_loop/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/loop_fusion/src/CMakeLists.txt
These two samples were missing the `/EHsc` Windows flags which was making the Windows compiles to fail.
=> FPGA: add Windows flags to the compile options of `loop_fusion` and `optimize_inner_loop`

DirectProgramming/DPC++/DenseLinearAlgebra/simple-add/src/simple-add-usm.cpp
This fixes a bug in the device selection of the simple-add sample (the USM version).
=> Fix `simple-add` selector in the USM version

DirectProgramming/DPC++FPGA/Tutorials/Features/private_copies/README.md, DirectProgramming/DPC++FPGA/Tutorials/Features/private_copies/src/CMakeLists.txt, DirectProgramming/DPC++FPGA/Tutorials/Features/private_copies/src/private_copies.cpp
Reverted change c2e5673ce20b478413f1075330c47f58a28575d5 as 2023.0 release cannot support simulation flow for this design. 
This change does keep the fix to prevent a warning being issued about the compiler optimizing away a key array of the design.
=> Private copies warn

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/src/CMakeLists.txt
- DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip
Changed the USER_ENABLE_USM flag to USM_HOST_ALLOCATIONS_ENABLED to accommodate the intel testing infrastructure. The setup is now similar to Tutorial/DesignPatterns/simple_host_streaming.
Removed the USM_ENABLED flag since it is no longer used in the Makefile.
=> Added USM_HOST_ALLOCATIONS_ENABLED to gzip

DirectProgramming/DPC++FPGA/ReferenceDesigns/db/README.md
This change updates the throughput expectation of the db reference design to adjust it to the current state of the compiler.
=> FPGA: update db throughput expectation

DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip/README.md
DirectProgramming/DPC++FPGA/ReferenceDesigns/gzip
S10 gzip high bandwidth code sample currently shows lower throughput in 2023.0.
=> Updated gzip README to reflex slower throughput in 2023.0

Libraries/oneDNN/tutorials/tutorial_analyze_isa_with_dispatcher_control.ipynb
add some comments and also set oneapi path to default path
=>  add some comments and also set oneapi path to default path

DirectProgramming/DPC++FPGA/ReferenceDesigns/qrd/src/CMakeLists.txt
The QRD design needs a seed update to match the expected performance with the 2023.0 version of the compiler.
=> FPGA: update qrd seed

AI-and-Analytics/Getting-Started-Samples/IntelTensorFlow_GettingStarted/README.md
enable existing TF for dGPU support, so add session about running on Intel GPU
Fixes Issue#  …
=> enable dGPU support

Libraries/oneDNN/tutorials/tutorial_getting_started.ipynb
Made modifications needed for 2023.0 Base Toolkit release
- Modified the right CMake directory for getting_started sample
- Added dpcpp driver check file to getting_started sample
- changed icc to icx compiler 
Fixes Issue# 
Tested the samples in a Linux environment with 2023.0 base Toolkit using jupyter notebook
=> [oneDNN] Sample Update: getting_started

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/shannonization/README.md
Remove Windows support in shannonization for now because HW runs hang, whether on A10 or S10.
This patch will be reverted in the future once the Windows HW run is fixed. Tracked by HSD-ES: https://hsdes.intel.com/appstore/article/#/14017819747.
The regtest will not disable the Windows flow, though, to keep a full run history for future reference.
- oneAPI Release Notes update: https://hsdes.intel.com/appstore/article/#/14018342194
- README update
=> Remove Windows support in shannonization

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/merge_sort/README.md
This PR removes the instructions on how to build and run the merge_sort sample on Windows as it is not expected to work on Windows in 2023.1
=> FPGA: remove instructions to build merge_sort on Windows

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/printf/README.md
DirectProgramming/C++SYCL_FPGA/Tutorials/Features/printf
The simulator instructions have been removed from the README of the printf code sample because it was generating a warning in the 2023.0 release.
This has been fixed in 2023.1 and we shoud re-add these instructions for the 2023.1 release of the code samples.
=> Update printf readme and fixed some typos

DirectProgramming/C++SYCL_FPGA/README.md
This PR updates the additional links that are provided in the FPGA top-level readme to match the 2023.1 release expectations.
=> FPGA: Top level readme update

DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/02_SYCL_Program_Structure/src/complex_mult_solution.cpp, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/11_Intel_Distribution_for_GDB/src/array-transform.cpp
removed dpc_common.hpp dependency which was throwing errors with 2023.0 release
=> removed dpc_common.hpp dependency

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/private_copies/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/private_copies/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/private_copies/src/private_copies.cpp
=> Private copies2

DirectProgramming/C++SYCL/CombinationalLogic/mandelbrot/src/main.cpp, DirectProgramming/C++SYCL/DenseLinearAlgebra/complex_mult/src/complex_mult.cpp, DirectProgramming/C++SYCL/DenseLinearAlgebra/matrix_mul/src/matrix_mul_sycl.cpp, DirectProgramming/C++SYCL/GraphAlgorithms/all-pairs-shortest-paths/src/apsp.cpp, DirectProgramming/C++SYCL/GraphTraversal/bitonic-sort/src/bitonic-sort.cpp, DirectProgramming/C++SYCL/GraphTraversal/hidden-markov-models/src/hidden-markov-models.cpp, DirectProgramming/C++SYCL/MapReduce/MonteCarloPi/src/monte_carlo_pi.cpp, DirectProgramming/C++SYCL/N-BodyMethods/Nbody/src/GSimulation.hpp, DirectProgramming/C++SYCL/ParallelPatterns/PrefixSum/src/PrefixSum.cpp, DirectProgramming/C++SYCL/ParallelPatterns/loop-unroll/src/loop-unroll.cpp, DirectProgramming/C++SYCL/SparseLinearAlgebra/merge-spmv/src/spmv.cpp, DirectProgramming/C++SYCL/SpectralMethods/DiscreteCosineTransform/src/DCT.cpp, DirectProgramming/C++SYCL/StructuredGrids/1d_HeatTransfer/src/1d_HeatTransfer.cpp, DirectProgramming/C++SYCL/StructuredGrids/guided_HSOpticalflow_SYCLMigration/02_sycl_dpct_migrated/src/derivativesKernel.hpp, DirectProgramming/C++SYCL/StructuredGrids/iso2dfd_dpcpp/src/iso2dfd.cpp, DirectProgramming/C++SYCL/StructuredGrids/iso3dfd_dpcpp/src/iso3dfd.cpp, DirectProgramming/C++SYCL/StructuredGrids/particle-diffusion/src/motionsim.hpp
Reverted PR#1265 and PR#1266 so that code samples will work with the latest dpc_common.hpp namespace changes and uses the right headers for the 2023.0 compilers.
Fixes Issue# 
=> Reverted PR#1265 and PR#1266

Libraries/oneMKL/matrix_mul_mkl/matrix_mul_mkl.cpp
Changes the `matrix_mul_mkl` sample to use single precision instead of double precision, as some devices don't support single precision.
None
=> matrix_mul_mkl: use single precision for compatibility with all devices

Tools/GPU-Occupancy-Calculator/index.html
updated latest GPU devices in Occupancy Calculator
added Intel Arc, Flex, ADL and RKL GPU devices to the list
=> updated latest GPU devices in Occupancy Calculator

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/crr/src/CMakeLists.txt
The simulation runtime of the CRR design is very long.
This PR adds a message that the users can see when they compile for simulation warning them about this long runtime.
=> FPGA: add a warning when compiling the CRR design in the simulation flow

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/README.md, AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/ResNet50_Inference.ipynb, AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/codes_for_ipynb/gpu.patch, AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/sample.json
Add a new Jupyter notebook in this sample which  guides users how to change PyTorch* codes to run on Intel® Data Center GPU family and how to validate the GPU or CPU usages for PyTorch* workloads on Intel CPU or GPU.
Administrative
Review
=> [New Sample] Intel Extension for PyTorch Getting Started

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/mvdr_beamforming/README.md
This change updates the throughput numbers observed for the mvdr_beamforming design to be accurate for the 2023.1 release.
Fixes Issue# 
* N/A
Since this is a README change I checked to see if the new .md file looks as intended.
=> FPGA: Update throughput numbers for mvdr_beamforming design for 2023.1 release

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/qrd/src/CMakeLists.txt
This PR updates the PAC S10 default seed of the QRD design in order to meet the expected performance for 2023.1
=> FPGA: Update QRD s10 default seed

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision/sample.json
Updated title field in sample.json in TF Transformer AMX bfloat16 Mixed Precision sample to fit within character length range
=> Sample.json fix for IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision sample

Libraries/oneMKL/monte_carlo_european_opt/GNUmakefile, Libraries/oneMKL/monte_carlo_european_opt/README.md, Libraries/oneMKL/monte_carlo_european_opt/makefile, Libraries/oneMKL/monte_carlo_european_opt/src/montecarlo_main.cpp
These changes fix the default random number generator for the european Monte-Carlo oneMKL sample.
Signed-off-by: Fedorov, Andrey <andrey.fedorov@intel.com>
=> Update the oneMKL sample with mcg59 as a default engine

AI-and-Analytics/version_check.py
Miss a architect checker class for new pytorch samples, so add it back
Fixes Issue# 
=> add arch checker class for AI version_check.py

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/codes_for_ipynb/gpu.patch
In the original gpu.patch, there are two point to be fixed
1. file name not match
2. y_ans stay on cpu not convert to gpu
Fixes Issue# 
None
=> 2023.1 ai kit ipex get started, gpu patch fix

AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.py, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision.ipynb, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision/README.md, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision/sample.json
There was a spelling mistake in AMX bfloat16 mixed precision Transformer sample (Readme.md, sample.json and *.ipynb files).
There was a error printing results for *.py files in numpy vs numba vs numba_dpex sample. 
Fixes Issue# 
=> Fixes for AMX bfloat16 transformer and numba vs numpy samples

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/README.md, AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/ResNet50_Inference.ipynb
For README file, fix a typo in the command of registering the jupyter kernel for gpu environment.
For ResNet50_Inference.ipynb, there are 6 items to be fixed:
1. align the default ONEAPI_INSTALL path with the one in README.
2. correct the conda environment name for both CPU and GPU.
3. add notes to switch jupyter kernel and run prerequisites again in the section running on CPU.
4. Modify the default FdIndex from 2 to 0 because there are only 2 indexes available in this example (i.e. 0 and 1).
5. Modify the code of showing the time breakdown for architecture type, to fix the "exception" error.
6. remove the unnecessary code of changing the directory to the initial path, in the end.
Fixes Issue# 
Please delete options that …
=> 2023.1 ai kit itex get started example fix

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/ResNet50_Inference.ipynb, AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/codes_for_ipynb/gpu.patch, AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/codes_for_py/gpu.patch
The original demo file used in ipynb for this get started samples link changed by ipex repo.
updated demo link is https://github.com/intel/intel-extension-for-pytorch/blob/master/examples/cpu/training/single_instance_training_fp32.py
Need change in the ipynb code to wget the right link.
Fixes Issue# 
=> fix resnet inference demo link from ipex repo

Libraries/oneTBB/tbb-async-sycl/src/tbb-async-sycl.cpp, Libraries/oneTBB/tbb-task-sycl/src/tbb-task-sycl.cpp
Updated oneTBB code samples to use default_selector_v to get the samples compiling and running with the latest compiler.
=> Update oneTBB samples to SYCL2020

DirectProgramming/C++/GraphTraversal/MergesortOMP/Makefile
Changing the compiler from icpc to icpx as the icc compiler has been deprecated from 2023.
Fixes Issue# 
Removes deprecation warning messages
=> update Makefile to compile with icpx

AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/IntelPython_daal4py_Distributed_Kmeans.py
Fix K-means example invalid parameters issue on 2023.
Fixes Issue# https://jira.devtools.intel.com/browse/ONSAM-1560
No.
Run the example on oneAPI 2023 before and after merge the patch.
Without this fix, it reports invalid paramters.  https://jira.devtools.intel.com/browse/ONSAM-1560
With fix, it works, output result (no errors).
It works on oneAPI 2022, with/without the fix.
```
#cd oneAPI-samples/AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans
#python IntelPython_daal4py_Distributed_Kmeans.py
```
Please describe the tests that you ran to verify your changes. Provide …
=> Fix Invalid Kmeans parameters on oneAPI 2023

DirectProgramming/C++SYCL_FPGA/include/streaming_qrd.hpp
The `mvdr` design is exposing an out of bounds memory access in the `streaming_qrd.hpp` header.
This PR fixes this issue.
=> FPGA: prevent an out of bounds memory access in `streaming_qrd.hpp`

DirectProgramming/C++SYCL/DenseLinearAlgebra/simple-add/README.md, DirectProgramming/C++SYCL/DenseLinearAlgebra/simple-add/src/CMakeLists.txt, DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/README.md, DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/src/CMakeLists.txt
This PR changes the default FPGA target of the `simple-add` and `vector-add` samples to Agilex.
It also changes the default flow from "full board" to "IP Authoring".
This change follows a similar change applied to all the FPGA code samples (https://github.com/oneapi-src/oneAPI-samples/pull/1307)
=> FPGA: Move the simple-add and vector-add samples to the IP Authoring flow

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/memory_attributes/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/memory_attributes/src/CMakeLists.txt
Currently running simulator for this design on Windows will hang, so we are removing Windows simulator command for this design.
1. Documentation change for README.md
2. Prevent Windows to run simulator target for src/CMakeLists.txt
=> FPGA: Remove Windows simulator command for memory_attributes

DirectProgramming/C++SYCL/StructuredGrids/guided_HSOpticalflow_SYCLMigration/02_sycl_dpct_migrated/src/derivativesKernel.hpp, DirectProgramming/C++SYCL/StructuredGrids/guided_HSOpticalflow_SYCLMigration/02_sycl_dpct_migrated/src/downscaleKernel.hpp, DirectProgramming/C++SYCL/StructuredGrids/guided_HSOpticalflow_SYCLMigration/02_sycl_dpct_migrated/src/solverKernel.hpp, DirectProgramming/C++SYCL/StructuredGrids/guided_HSOpticalflow_SYCLMigration/02_sycl_dpct_migrated/src/upscaleKernel.hpp, DirectProgramming/C++SYCL/StructuredGrids/guided_HSOpticalflow_SYCLMigration/02_sycl_dpct_migrated/src/warpingKernel.hpp
Fix for compilation issue in one of the samples.
Fixes Issue# 
https://jira.devtools.intel.com/browse/ONSAM-1550
https://jira.devtools.intel.com/browse/ONSAM-1553
=> Fix compilation error

AI-and-Analytics/Features-and-Functionality/README.md
Add new samples into the sample list of README
Fixes Issue# 
=> Update README to add new samples into the list

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/decompress/src/main.cpp
This decompress design was not using the correct files when running the emulator flow, resulting in runtime failures.
=> FPGA: Fix decompress emulation flow not using the correct files

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/memory_attributes/src/memory_attributes.cpp
This will make the simulation runtime faster.
=> FPGA: Reduce the design size of the memory_attributes design in simulation

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/shannonization/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_initiation_interval/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/optimization_levels/minimum_latency/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/speculated_iterations/src/CMakeLists.txt
Some of the samples required the device flags to be set using `-DDEVICE_FLAG=-DAgilex` rather than `-DDEVICE_FLAG=Agilex`.
This change makes all the samples consistent with the second option.
=> FPGA: Fix inconsistent device flags in 4 samples

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/memory_attributes/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/memory_attributes/src/CMakeLists.txt
Reverts oneapi-src/oneAPI-samples#1374
We no longer need this above commit since we believe reducing the test size is a better solution here.
=> Revert "FPGA: Remove Windows simulator command for memory_attributes"

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/buffered_host_streaming/src/HostStreamer.hpp
This PR implements a better fix for the concurrency issue than the one implemented in https://github.com/oneapi-src/oneAPI-samples/pull/1375
=> FPGA: better fix for the concurrency issue in buffered_host_streaming

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/memory_attributes/src/memory_attributes.cpp
Currently this test takes unreasonably long (hours) for Windows simulator target. Reducing the test size helps to reduce the time taken to under 10 minutes.
Reduce test size
Reducing the test size should be a safe change.
I have also test the simulator target on both Windows and Linux for my change.
=> FPGA: Reduce test size from 64 to 2 for memory_attributes simulator target

DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/04_SYCL_Sub_Groups/Sub_Groups.ipynb, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/04_SYCL_Sub_Groups/lab/sub_group_reqd_size.cpp, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/04_SYCL_Sub_Groups/lab/sub_group_votes.cpp
changed the default sub-group size from 8 to 32
Fixes Issue# 
#
Devcloud
=> changed the default sub-group size from 8 to 32

AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/README.md
Restructured to match the new readme template—more or less. Changed sample name to match the name in sample.json file. Restructured sections to increase clarity. Clarified information on running sample in devcloud. Rewrote some text to improve clarity. Updated branding based on names in database.
N/A
Fixes Issue# 
=> Update IntelPython_daal4py_DistributedKMeans readme

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/simple_host_streaming/src/simple_host_streaming.cpp
Reduce test size for simple_host_streaming simulator target since currently Questa FSE takes too long.
Fixes Issue# 
Reduce test size
Run simulator target on Linux
=> FPGA: Reduce test size for simple_host_streaming simulator target

Tools/ApplicationDebugger/array-transform/CMakeLists.txt, Tools/ApplicationDebugger/jacobi/CMakeLists.txt
I have missed this part in the previous PR: https://github.com/oneapi-src/oneAPI-samples/pull/1387
These targets are for convenience. AFAIK they are not mentioned in the documentation.
If it still can be included into 2023.1, that would be great, but it is not a stopper in my opinion.
FYI @barisaktemur
=> ApplicationDebugger: update make targets with ONEAPI_DEVICE_SELECTOR

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/anr/src/CMakeLists.txt
The `anr` sample cmake file was not allowing to target parts that did not contain the keywords "agilex" or "a10" or "s10".
This PR addresses this gap.
=> FPGA: fix `anr` cmake file

DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
Readme changes to add include folder path
No change.
- Document change
https://spetc.intel.com/testanalysis?trview=0&testRunIds=7557550&tapgsize=20 \
Tested with 2023.1 compiler targeting pac_s10_usm board
https://spetc.intel.com/testanalysis?trview=0&testRunIds=7500417&tapgsize=20 \
Tested with 2023.1 targeting IPA because ref boards on windows farm do not support USM
=> Fpga compile add include path

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_ivdep/src/CMakeLists.txt
This sample is notorious for getting a high percentage of timing failures during quartus compiles on the PAC boards.
This PR fixes the seed so that we know it compiles cleanly on PAC boards.
=> FPGA: fix the HW compile seed for the ivdep sample 

Tools/GPU-Occupancy-Calculator/index.html
updated GPU Occupancy Calculator with PVC GPU
update UI for "threads_per_ss" when large_grf mode is set
Fixes Issue# 
NA
=> updated GPU Occupancy Calculator with PVC GPU

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_matrix_mul_SYCLMigration/sample.json, Libraries/oneMKL/guided_cuBLAS_examples_SYCL_Migration/sample.json
Updated sample.json files for cuBLAS and matrix_mul_SYCLMigration
=> Updated sample.json files for cuBLAS and matrix_mul_SYCLMigration

Tools/Advisor/matrix_multiply_advisor/src/matrix.cpp, Tools/Advisor/matrix_multiply_advisor/src/multiply.hpp, Tools/ApplicationDebugger/array-transform/src/array-transform.cpp, Tools/ApplicationDebugger/array-transform/src/selector.hpp, Tools/ApplicationDebugger/jacobi/src/jacobi-bugged.cpp, Tools/ApplicationDebugger/jacobi/src/jacobi-fixed.cpp, Tools/VTuneProfiler/matrix_multiply_vtune/src/matrix.cpp, Tools/VTuneProfiler/matrix_multiply_vtune/src/multiply.hpp
Fix compilation error for oneapi 2023.0
Fixes Issue# 
Administrative
Security …
=> Need to change back to CL/sycl.hpp for Tools samples

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_unroll/src/loop_unroll.cpp
The loop unroll code sample's array size was 1024 for simulation which caused simulating with Questa FSE on Windows to be very slow (>24 hours).
This changes the array size to 16 which lets the simulation to complete in ~1 hour using Questa FSE on Windows.
None
Compiled and ran the loop unroll code sample for simulation on Windows.
=> Change array size to 16 for simulation

DirectProgramming/C++SYCL/GraphTraversal/hidden-markov-models/src/hidden-markov-models.cpp
Fixing a common error of a GPU not computing double precision floating points.
Fixes Issue# https://jira.devtools.intel.com/browse/ONSAM-1504
=> Fix for ONSAM-1504

RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/sample.json, RenderingToolkit/Tutorial/PathTracingWithEmbree/sample.json
2023.2 Development branch: Validation team needed extra references in sample.json for the rkcommon utility support library to resolve on macOS. IntroToRayTracing and PathTracingWithEmbree samples.
Fixes Issue#
workaround for reference jira: ONSAM-1563
none
Run steps in samples.json
=> Rtk development branch fix for validation 20230320

DirectProgramming/C++SYCL/DenseLinearAlgebra/matrix_mul/Makefile.win
This PR updates the Makefile.win file so that the matrix_mul code sample can compile without errors on Windows.
Fixes Issue# 
ONSAM-1578
=> Updated Makefile.win in matrix_mul to resolve Windows compilation errors

Libraries/oneMKL/fourier_correlation/makefile
Updated Makefile in Fourier corrleation sample to remove sycl.lib so that the code sample can compile on Windows.
Fixes Issue #ONSAM-1576
=> Updated Makefile in Fourier corrleation sample to remove sycl.lib

Publications/DPC++/Ch18_using_libs/CMakeLists.txt
Uncommented CMakeLists.txt in DPC++ book for Ch18 code samples.
Fixes Issue# 
ONSAM-1572
=> Allow Ch18 DPC++ book code samples to compile

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/README.md
release/2023.1 port of https://github.com/oneapi-src/oneAPI-samples/pull/1471
=> FPGA: document RTL library issue with the 2023.1 release. 

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ac_fixed/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ac_fixed/src/CMakeLists.txt
The `ac_fixed` sample breaks on emulator because the emulator default for fp model is changed to "fast-math" recently.
There's a larger gap regarding the precision between FP precise and FP fast-math (default) mode on FPGA emulator, compared with other platforms. As a result, the emulator precision cannot meet the error threshold set in the design, while the simulator precision can. 
This PR sets `-fp-model=precise`(linux) or `/fp:precise`(windows) to pass the tests on all platforms.
=> FPGA: Set fp model to "precise" for ac_fixed sample

AI-and-Analytics/Features-and-Functionality/IntelPyTorch_InferenceOptimizations_AMX_BF16_INT8/sample.json, AI-and-Analytics/Features-and-Functionality/IntelPyTorch_TrainingOptimizations_AMX_BF16/sample.json, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_AMX_BF16_Training/sample.json, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision/sample.json
Added cpuInstructionSets to sample.json for AI samples for automated CI testing.
=> Added cpuInstructionSets to sample.json for AI samples

Libraries/oneMKL/monte_carlo_european_opt/makefile
Fixed building of the `monte_carlo_european_opt` sample on Windows: refactored the makefile for Windows according to NMAKE rules.
=> Fixed building of monte_carlo_european_opt on Windows

Libraries/oneMKL/computed_tomography/computed_tomography.cpp
Removed compiler warnings for computed_tomography sample.
=> Removed compiler warnings for computed_tomography sample.

DirectProgramming/C++SYCL/DenseLinearAlgebra/simple-add/sample.json, DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/sample.json
The Windows USM `fpga_emu` targets of these two samples where missing the `cmake` option to trigger the USM compile, resulting in a CI failure.
=> Fix CI steps in vector-add and simple-add 

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/db/src/dbdata.cpp
Fixed a merge issue with master branch in dbdata.cpp. There were duplicate PrintQ9 functions.
=> Fixed merge issue in dbdata.cpp

third-party-programs.txt
- Google fonts are used in the oneAPI Samples Catalog.
=> Add entry in third-party-programs.txt for use of Google Fonts API

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/printf/README.md
The known issues with %s and %p for printf are no longer relevant.
Fixes Issue# 
Documentation change
=> FPGA: Remove resolved known issues for printf

AI-and-Analytics/End-to-end-Workloads/Census/README.md, AI-and-Analytics/End-to-end-Workloads/Census/census_modin.ipynb, AI-and-Analytics/End-to-end-Workloads/Census/sample.json
Fixes Issue# 
Administrative
Review
=> Update Census sample: Use HDK as backend of Modin

DirectProgramming/C++SYCL/DenseLinearAlgebra/simple-add/src/CMakeLists.txt, DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/src/CMakeLists.txt
The default behavior when running `make` in these two samples was to build all available targets.
This PR disables all the FPGA targets from the default `make` command, only leaving the `cpu-gpu` one.
=> Remove the FPGA targets from the default make command in the simple-add and vector-add samples

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/printf/sample.json, DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/sample.json
This PR addresses some issues in the CI steps of the following designs:
- `printf`: this sample does not support the `report` target in IP Authoring mode
- `fpga_compile`: this sample was recently significantly reworked and broke into four different part. Its `sample.json` file has not been updated in this process.
=> FPGA: fix CI steps for printf and fpga_compile

AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/IntelPytorch_Interactive_Chat_Quantization.ipynb, AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/IntelPytorch_Interactive_Chat_Quantization.py, AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/License.txt, AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/README.md, AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/insert.txt, AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/sample.json
The sample demonstrates how to create interactive chat based on pre-trained DialoGPT model and add the Intel® Extension for PyTorch* quantization to it. Within the sample, it is also possible to compare the performance of the method without and with INT8 quantization.
Administrative
Review
=> Interactive chat based on DialoGPT model using IPEX

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/anr/src/main.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/merge_sort/src/main.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/mvdr_beamforming/src/FakeIOPipes.hpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/io_streaming/src/FakeIOPipes.hpp
A recent simulator change made the device aspect to be disabled in the simulator when in an IP Authoring flow.
This makes sense as the IP Authoring flow does not support device allocations.
Therefore, we need to stop checking for this aspect when in IP Authoring flow (as the code does not use the device allocations in the case).
=> FPGA: Only check for device USM support in BSP mode

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/mem_channel/src/mem_channel.cpp
Integer division will truncate the decimals, thus the throughput being presented is incorrect
Example (incorrect) output in regtest https://psg-sc-arc.sc.intel.com/p/psg/data/sys_hld_test/job/20230331/1000/1393654676/stdout.txt 
Demo:
Fixes Issue# 
This is a small change that only affects the output in stdout, tested the output result via the demo above
=> Fix integer division bug in mem_channel

DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/README.md
Add Intel(R) PAC with Intel Arria(R) 10 GX FPGA and Intel(R) FPGA PAC D5005 FPGA BSP information in the vector-add README.md to give beginner more hint to build and run this sample on above FPGA.
Update README
Fixes Issue #1333
=> Fix oneAPI-samples issue (#1333)

.github/workflows/github-pages.yml
- Add CI job with trigger and change it from `schedule`/`cron` job to `push` to `master` branch
- New trigger aligns with quarterly release cadence of oneAPI-Samples workflow convention
- New trigger also used for out-of-cycle builds as necessary
- No new dependencies. Add `github-pages` CI script only. 
Tested on internal repo. Refer to author.
=> Add .github/workflows/github-pages.yml to build oneAPI Samples app

README.md
Adding a section on the sample catalog to the top-level readme. I thought I had done this already, but it turns out that didn't work. Second attempt.
N/A
=> add sample catalog link to top-level readme

DirectProgramming/C++/ParallelPatterns/openmp_reduction/src/main.cpp
Fix OMP Reduction sample, on TGL GPU kernel use float
Fixes Issue #755
=> Fix OMP Reduction sample, on TGL GPU kernel use float, fix #755

Libraries/oneMKL/fourier_correlation/README.md
I fixed a typo and updated some hyperlinks that were broken because the URLs on Intel Developer Zone changed.
None.
=> Fixed typo and broken hyperlinks

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_fusion/README.md
Fix broken link to the loop coalesce tutorial in the loop fusion README.
=> [FPGA] Fix broken link in LF README

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/memory_attributes/src/CMakeLists.txt
This change fixes a configuration issue that was causing the `IS_BSP` flag to not be passed in to the simulation flow.
I ran the `make fpga_sim` IPA flow (`cmake -DFPGA_DEVICE=Arria10 ..`) and checked that the `Xsuse-2xclock` flag was being passed in as intended.
=> FPGA: Update memory_attributes sample to use IS_BSP flag in the sim flow

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision.ipynb, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision/patch/mixed_precision.patch, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision/patch/time.patch, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision/run_amx.sh, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision/sample.json
API related to mixed precision learning changed since TF 2.11. There was also changes in env variables related to oneDNN default ISA. The changes apply new API and system variables to the code sample.
Fixed few spelling issues. 
Fixes Issue# 
None.
When testing, make sure intel extension for tensorflow is installed and the code runs on SPR.
=> Changes in AMX mixed precision learning Transformers sample to reflect TensorFlow version 2.11 and above

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/merge_sort/src/main.cpp
The merge_sort sample used to allocate device memory when in IPA mode, which is not a supported operation.
This PR makes the sample allocate shared memory in IPA mode.
=> FPGA: Fix merge_sort memory allocation in IPA mode

RenderingToolkit/GettingStarted/01_ospray_gsg/README.md
oneAPI Rendering Toolkit 2023.1 version's cmake file contains an errata. The errata will produce an error while building the example. Please apply the workaround described in the following page. 2023.1.1 version will address the issue.
=> Added note for erreta in README.md of RenderingToolkit

Libraries/oneDNN/tutorials/profiling/profile_utils.py
Fix for warning message output in python_utils script when passing oneDNN verbose logs with *info* lines.
Fixes  #1368 
Currently, when passing a oneDNN verbose log to python_utils script with info lines the script outputs warning messages to the user:
```profile_utils.py:354: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
log.exec_data['time'] = log.exec_data['time'].astype(float)
Total MKLDNN time: 320.32668909200004
Total MKLDNN ops: 15340
breakdown: type
C:\Users\orelyehu\profile_utils\oneAPI-samples\Libraries\oneDNN\tutorials\profiling\profile_utils. …
```
=> [oneDNN][profile_utils.py] Warning message fix

DirectProgramming/C++SYCL/MapReduce/guided_quasirandomGenerator_SYCLMigration/sample.json, DirectProgramming/C++SYCL/guided_convolutionSeparable_SYCLmigration/sample.json
After adding some samples, the sample aggregator started reporting errors in the validation of sample.json files. In two samples, due to a _categories_ field that doesn't fit the format, json files turned out to be invalid:
```
iotdk-ninja
iotdk-ninja
10.64.105.26 10.64.69.172 172.17.0.1 
Sample branch/tag: development
The following error was seen in function isValid()
In the sample named:
convolutionSeparable
The error message is:
[{"instancePath":"/categories/0","schemaPath":"#/properties/categories/items/pattern","keyword":"pattern","params":{"pattern":"^(Toolkit/.*[^/])$"},"message":"must match pattern \"^(Toolkit/.*[^/])$\""}]
```
```
iotdk-ninja
iotdk-ninja
10.64.105.26 10.64.69.172 172.17.0.1 
Sample branch/tag: development
The following error was seen in function isValid()
In the …
```
=> Fix of errors reported by the sample aggregator. Invalid sample.json 

Libraries/oneMKL/batched_linear_solver/License.txt, Libraries/oneMKL/batched_linear_solver/README.md, Libraries/oneMKL/batched_linear_solver/lu_solve_omp_offload.F90, Libraries/oneMKL/batched_linear_solver/lu_solve_omp_offload_optimized.F90, Libraries/oneMKL/batched_linear_solver/makefile, Libraries/oneMKL/batched_linear_solver/sample.json, Libraries/oneMKL/batched_linear_solver/third-party-programs.txt
This sample shows how to solve batched linear systems using oneMKL and OpenMP target offloading. The example codes are written in Fortran, but the concepts generalize to C and C++. They have been reviewed by oneMKL developers (Sarah Knepper, Louise Huot) and Fortran compiler TCEs (Shiquan Su, Ron Green).
Administrative
Review
=> Add the new batched linear solver sample

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/double_buffering/src/double_buffering.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/n_way_buffering/src/n_way_buffering.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/simple_host_streaming/src/simple_host_streaming.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/triangular_loop/src/triangular_loop.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/read_only_cache/src/read_only_cache.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/system_profiling/src/double_buffering.cpp
This change prevents the deprecation warning related to the `ulong` datatype to appear when compiling FPGA samples.
=> FPGA: replace `ulong` with `unsigned long`

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/src/CMakeLists.txt
Add a USER_FLAGS variable in the cmake file to allow users to pass in additional flags.
Fixes Issue# 
Ran some compiles to ensure flags are being passed properly.
=> FPGA: Allow users to pass in additional flags through CMake for matmul sample

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/crr/src/CMakeLists.txt
Change the Quartus seed from 2 to 3 for CRR on S10 devices.
Fixes Issue# 
None
=> Update S10 seed for CRR

RenderingToolkit/GettingStarted/01_ospray_gsg/sample.json, RenderingToolkit/GettingStarted/02_embree_gsg/sample.json, RenderingToolkit/GettingStarted/05_ispc_gsg/sample.json, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/sample.json, RenderingToolkit/Tutorial/PathTracingWithEmbree/sample.json
Best known environment setting for python validation environment process forking and reliance on DYLD_LIBRARY_PATH on macos. See ONSAM ticket for details.
No observed issues with customer facing sample program, fix is for validation only.
Fixes Issue# 
ONSAM-1602 (and others linked to it)
None
- [  ] Bug fix (non-breaking change which fixes an issue)
- [ x ] Implement fixes for ONSAM Jiras
ONSAM-1602 (and others linked to it)
- [ x ] Command Line
Applied the tested string from Alexey's branch and applied it everywhere applicable... …
=> ONSAM-1602 Rendering for macos fix... see alexeyboreiko/oneAPI-samples-boreiko 6459f16

AI-and-Analytics/Features-and-Functionality/IntelPytorch_Quantization/IntelPytorch_Quantization.ipynb
clear all the output of ipynb to avoid showing performance data which not go through PDT performance yet
Fixes Issue# 
=> clear all the ouutput of ipynb

Libraries/oneMKL/computed_tomography/computed_tomography.cpp
This PR improves error handling in the computed_tomography sample for devices that do not support double precision. This sample requires double precision, so this PR:
* Automatically looks for a device with double precision support
* If none found, returns an informative error message:
```
Could not find any device with double precision support. Exiting.
```
None
=> computed_tomography: improve error handling when double precision unavailable

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/board_test.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/helper.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/host_speed.hpp
Updated code sample to use "command_start" kernel event profiling information instead of "command_submit" to handle a [change in SYCL runtime](https://github.com/intel/llvm/commit/097d21c33599972837491378f3b9dd9094c27944). 
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] Command Line
=> FPGA reference design: Board_test patch

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/CMakeLists.txt
The previous default seed led to a routing failure when targeting the PAC A10.
This new seed makes the Quartus compile pass.
=> FPGA: update board test reference design default seed

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/pca/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/pca/src/pca_demo.cpp, DirectProgramming/C++SYCL_FPGA/include/streaming_covariance_matrix.hpp
The number of private copies for different arrays was set to 128, a large number that was optimized away by the compiler.
This change adjusts this number to a more sensible value.
=> FPGA: adjust the number of private copies in the covariance matrix kernel

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/hostpipes/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/hostpipes/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/hostpipes/src/hostpipes.cpp
Update host pipe tutorial to use native host pipes instead of prototype host pipes. This involves updating the include file, source declarations of host pipes, and README documentation. Since there are no BSPs that support native host pipes, also limit the tutorial to IP authoring flow only.
none
- [ x] New feature (non-breaking change which adds functionality)
Ran locally via command line.
=> Update host pipes tutorial for native implementation

DirectProgramming/C++SYCL_FPGA/include/streaming_qrd.hpp
The `a_i` memory was used uninitialized and assumed to be 0.
This change initializes this memory to 0 prior to using it.
=> FPGA: fix use of uninitialized memory in streaming_qrd.hpp 

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/read_only_cache/src/CMakeLists.txt
HSDES: https://hsdes.intel.com/appstore/article/#/14019335652
The default seed suffers from fitter failures in Quartus. Other seeds don't seem to suffer from this issue
Linux build: https://spetc.intel.com/testsummary?trview=0&testRunIds=8228011 
Windows Build: TBD
=> Changed default seed in read_only_cache design

RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/sample.json
Just an update for the IRTK tutorial Intro to Ray Tracing samples.json which has a duplication issue and had omitted GPU targeting.
Fixes Issue# 
ONSAM-1612
Cited thanks to @alexeyboreiko 
_Set target device in json to include GPU_
_N/A This is fix for validation only_
=> IRTK Intro to Ray Tracing val fix (duplication/GPU)

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/src/matmul.hpp
Adds a call to wait() on the feeders to guarantee that all kernels which access USM have finished before the memory is freed.
=> FPGA: Matrix multiply sample: add wait() call to feeders

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/lsu_control/src/CMakeLists.txt
This PR addresses an issue where the default seed fails consistently with fitter failures in Quartus. Other seeds do not suffer from this issue. Running 10 other seeds show that the default seed is failing, but all others are passing: https://spetc.intel.com/testsummary?trview=0&testRunIds=8264656
A similar fix was required for the read_only_cache tutorial: https://github.com/oneapi-src/oneAPI-samples/pull/1741 
* N/A
=> [FPGA] Update the default seed in lsu_control tutorial

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/src/matmul.hpp
The matmul.hpp file was using the compiler macros TILE_A and TILE_B in a function instead of the template parameters tile_a and tile_b that are passed into that function. Updating to use the template parameters.
=> FPGA: matrix multiply sample: use template param instead of macro in the code

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/src/matmul.hpp
The matmul.hpp file was using the compiler macros TILE_A and TILE_B in a function instead of the template parameters tile_a and tile_b that are passed into that function. Updating to use the template parameters.
=> FPGA: matrix multiply sample: use template param instead of macro in the code for 2023.2

RenderingToolkit/GettingStarted/02_embree_gsg/sample.json, RenderingToolkit/GettingStarted/04_oidn_gsg/sample.json, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/sample.json
Updated sample.json for IntroToRayTracingWithEmbree, 02_embree_gsg, 04_oidn_gsg to add GPU support for CI testing.
Fixes Issue#  ONSAM-1620
=> Updated sample.json for IntroToRayTracingWithEmbree, 02_embree_gsg, 04_oidn_gsg

DirectProgramming/Fortran/guided_matrix_mul_OpenMP/sample.json
Updated sample.json for guided_matrix_mul_OpenMP to use double floating point precision for CI testing.
Fixes Issue# ONSAM-1618
=> Updated sample.json for guided_matrix_mul_OpenMP

DirectProgramming/C++SYCL/ParallelPatterns/dpc_reduce/sample.json, Libraries/oneMKL/binomial/sample.json
Updated sample.json files to indicate that binomial and dpc_reduce samples use double fp precision.
Fixes Issue# ONSAM-1618
=> Updated sample.json files for binomial and dpc_reduce

DirectProgramming/C++/GraphTraversal/MergesortOMP/Makefile
Updated makefile for MergesortOMP sample to use icpc for macOS. icpx does not exist on macOS.
Fixes Issue# ONSAM-1616
=> Updated makefile for MergesortOMP sample to use icpc for macOS

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/src/memory_transfers.hpp
Updates the three DMA kernels to use variable rather than fixed latency MM hosts when compiling in the IP authoring flow.
Fixes Issue# 
=> FPGA: modify matrix multiply sample to use variable latency MM hosts

DirectProgramming/Fortran/guided_matrix_mul_OpenMP/src/03_mm_GPU.f90
Update 03_mm_GPU.f90 to resolve build error.
This addresses a reported non-zero error code. The update is correcting an inconsistency between source files with single vs double precision.
=> Update source file to resolve build error

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/simple_host_streaming/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/CMakeLists.txt
The `simple_host_streaming` and `zero_copy_data_transfer` samples used have the `DEVICE_FLAG` set in their cmake file even though it was not used. 
This change removes the `DEVICE_FLAG` from their cmake file.
=> FPGA: remove unused flag `DEVICE_FLAG`

DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/CMakeLists.txt, DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/Common/helper_cuda.h, DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/Common/helper_cuda.h.yaml, DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/MainSourceFiles.yaml, DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/Samples/5_Domain_Specific/MonteCarloMultiGPU/MonteCarloMultiGPU.cpp.dp.cpp, DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/Samples/5_Domain_Specific/MonteCarloMultiGPU/MonteCarlo_common.h, DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/Samples/5_Domain_Specific/MonteCarloMultiGPU/MonteCarlo_gold.cpp.dp.cpp, DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/Samples/5_Domain_Specific/MonteCarloMultiGPU/MonteCarlo_kernel.dp.cpp, DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/Samples/5_Domain_Specific/MonteCarloMultiGPU/MonteCarlo_reduction.dp.hpp, DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/include/dpct/device.hpp, DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/include/dpct/memory.hpp, DirectProgramming/C++SYCL/MapReduce/guided_MonteCarloMultiGPU_SYCLMigration/01_dpct_output/include/dpct/rng_utils.hpp
A different version of 01_dpct_output folder is uploaded previously and now it is replaced with the proper version.
=> Revisited MonteCarloMultiGPU SYCL Migration  with 01_dpct_output folder modification

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/latency_control/src/latency_control.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/lsu_control/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/lsu_control/src/lsu_control.cpp
The upstream commit https://github.com/intel/llvm/pull/8874 changed the return type of `accessor::get_pointer` from a `multi_ptr` to a raw pointer, which affects all uses of `lsu::load` and `lsu::store` who expect a `multi_ptr` as their first function argument.
This commit updates the two affected code samples (lsu_control, latency_control) to avoid the compile failure caused by pointer type mismatch between `accessor::get_pointer` and `lsu::load`/`lsu::store`.
Fixes Issue https://jira.devtools.intel.com/browse/HLD-2916.
Case tracker for improving LSU control API in the future: https://hsdes.intel.com/appstore/article/#/14020028781.
=> Adapt to the `get_pointer` return type change from upstream intel/llvm

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/hostpipes/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_ivdep/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_unroll/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/max_interleaving/src/CMakeLists.txt
Add -fsycl to some designs with the -fsycl missing in comments in the icpx command
-fsycl is required for compiling to FPGA
Fixes Issue# no issue code
n/a
No testing required since this is a change only to comments
=> Add -fsycl to some designs with the -fsycl missing in comments in the icpx command

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/system_profiling/src/double_buffering.cpp
This test is periodically hits timing violations in S10 compiles, and this change makes the design smaller to make it more likely to fit without timing violations.
Fixes Issue#14019796464  
Tested using a regtest to confirm timing violations no longer come up in S10: https://spetc.intel.com/testsummary?trview=0&testRunIds=8426203
Ran the executable with the openCL Intercept Layer and confirmed the difference between where double buffering is and isn't applied is still visible.
(see image below - I used an older version of the intercept layer so it doesn't look the same as in the readme, but the difference in gaps between kernel executions is still visible)
=> Make the design smaller to prevent timing violations

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/optimization_targets/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/optimization_targets/src/optimization_targets.cpp
- The `MANUAL_REVERT` compile tries to manually revert the minimum latency flow settings to match the `NO_CONTROL` compile. However, `[[intel::speculated_iterations(4)]]` becomes unnecessary in `MANUAL_REVERT` because the speculated iteration is 0 in the corresponding `NO_CONTROL` compile now.
- Also remove two unused -D macros in CMakeLists.
- IPA: https://spetc.intel.com/testsummary?trview=0&testRunIds=8501121
- Full system: https://spetc.intel.com/testsummary?trview=0&testRunIds=8496942
=> Fix and simplify `optimization_targets` for S10 compile

AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/requirements.txt, AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedKMeans/sample.json, AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/requirements.txt, AI-and-Analytics/Features-and-Functionality/IntelPython_daal4py_DistributedLinearRegression/sample.json, AI-and-Analytics/Features-and-Functionality/Intel_Extension_For_SKLearn_Performance_SVC_Adult/requirements.txt, AI-and-Analytics/Features-and-Functionality/Intel_Extension_For_SKLearn_Performance_SVC_Adult/sample.json, AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/requirements.txt, AI-and-Analytics/Getting-Started-Samples/IntelPython_XGBoost_GettingStarted/sample.json, AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/requirements.txt, AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/sample.json
Fixes for:
- ONSAM-1649: [IntelPython_XGBoost_GettingStarted] failed due to No module named 'pandas'
- ONSAM-1650: [IntelPython_daal4py_GettingStarted] failed due to No module named 'pandas'
- ONSAM-1652: [IntelPython_daal4py_DistributedLinearRegression] failed due to No module named 'pandas'
- ONSAM-1653: [IntelPython_daal4py_DistributedKMeans] failed due to No module named 'pandas'
- ONSAM-1655: [Intel_Extension_For_SKLearn_Performance_SVC_Adult] failed due to No module named 'matplotlib'
Fixes Issue#
- ONSAM-1649
- ONSAM-1650
- ONSAM-1652
- ONSAM-1653
- ONSAM-1655
Please describe the tests that you ran to verify your changes. Provide …
=> Sample.json updates for AI samples (ONSAM-1627)

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/README.md
This change removed a warning in the `use_library` sample README about the sample not working in the IP Authoring flow.
The underlying issue has been addressed in the compiler.
=> FPGA: Remove obsolete warning in the use_library sample

DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/Makefile, DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/README.md, DirectProgramming/C++/CombinationalLogic/MandelbrotOMP/sample.json, DirectProgramming/C++/CompilerInfrastructure/Intrinsics/Makefile, DirectProgramming/C++/CompilerInfrastructure/Intrinsics/README.md, DirectProgramming/C++/CompilerInfrastructure/Intrinsics/sample.json, DirectProgramming/C++/GraphTraversal/MergesortOMP/README.md, DirectProgramming/C++/GraphTraversal/MergesortOMP/sample.json, DirectProgramming/Fortran/DenseLinearAlgebra/vectorize-vecmatmult/sample.json
Removed macOS support from samples for 2024.0 and replaced it with Linux. Updated the Makefile, sample.json and READMEs.
=> Removed macOS support from samples

AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.ipynb, AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.py
Fix problem with TypeError: kernel() got an unexpected keyword argument 'access_types' for kNN numba vs numpy sample.
Update *.ipynb and *.py files.
Fixes Issue #ONSAM-1651
=> Fix numba knn sample kernel issue

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/buffered_host_streaming/src/HostStreamer.hpp
This change modifies the exit condition of HostStreamer API's Sync function to check whether all of the queues, i.e., the launch queue, the producer queue, and the consumer queue, are empty.
This fixes intermittent functional error where the code reaches HostStreamer::Sync after producer events are submitted to the producer queue but before they get transferred to the launch queue, thereby exiting too early before all user requests are finished, leading to results not yet available upon error check.
N/A
=> FPGA: revise Sync function exit condition in HostStreamer API

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/src/matmul.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/src/memory_transfers.hpp
Updating matmul sample to use annotated_arg pointers for customizing mm hosts in the IP authoring flow.
Fixes Issue# 
=> FPGA: matmul updates for 2024.0

DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_template/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_template/README.md
add debug target to CMakeLists.txt and expand documentation to explain how to use it for debugging
Fixes Issue# <none>
=> FPGA: add debug target and expand documentation to the fpga_template sample

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/experimental/platform_designer/add-oneapi/src/add.cpp
This code sample used to use the blocking pipe write mode to store output to the CSR. This is a less desirable use case than the non-blocking pipe mode. Now that https://hsdes.intel.com/appstore/article/#/14019304561 is fixed, we can set this code sample to do what users actually want.
=> FPGA: Cleanup platform_designer protocol

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/memory_attributes/src/CMakeLists.txt
This PR addresses an issue where the default seed fails consistently with fitter failures in Quartus. Other seeds do not suffer from this issue. Running 10 other seeds show that the default seed is failing, but all others are passing.
* N/A
=> FPGA: Update the default seed in memory_attributes tutorial

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/src/matmul.hpp
Updating buffer locations in Matrix Multiply sample to match requirements (BLs start at 1 instead of 0) for 2024.0 release.
Fixes Issue# 
=> FPGA: Update Buffer Locations in Matrix Multiply sample to start from 1

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/lsu_control/src/lsu_control.cpp
This PR updates all uses of `get_pointer` to `get_multi_ptr` as there is now a deprecation warning when using the latest sycl/rel version.
*N/A
Ran emulator and simulator runs and both are passing.
=> FPGA: Remove use of get_pointer from lsu_control sample

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/mvdr_beamforming/src/Transpose.hpp
Passing the functor object directly to the lambda.
Tested the `regtest/hld/sycl/oneapi_code_samples/mvdr_beamforming` regtest simulation flow with `custom_ipa:Arria10` on linux and windows.
=> FPGA: Passing Functor Directly to Lambda

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/max_interleaving/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/max_interleaving/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/max_interleaving/src/max_interleaving.cpp
This is a new PR since the old one targeted the master branch by accident.
The loops in the old code sample had memory dependencies that prevented interleaving from occurring and relied on the compiler's inability to analyze memory dependencies to demonstrate the area savings of interleaving. 
An upcoming internal compiler PR improves our compiler's analysis abilities, rendering the old sample obsolete. 
As such, the code sample has been modified to contain loops that support interleaving. The README.md has been updated with the new hardware runtime data and some structural changes, as the old README.md frequently stated how the loops did not support interleaving, which is no longer the case.
N/A
Please delete options that are not relevant. Add a 'X' to the one that is …
=> FPGA: Rewrite of Max Interleaving Code Sample So That Interleaving Is Possible

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/mvdr_beamforming/src/mvdr_beamforming.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/pca/src/golden_pca.hpp
This change adds an include which is now necessary as not included by default with sycl.hpp anymore.
Fixes Issue# 
=> FPGA: add missing fstream include to PCA and MVDR Beamforming

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/crr/src/CRR_common.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/crr/src/main.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/mvdr_beamforming/src/mvdr_beamforming.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/read_only_cache/src/read_only_cache.cpp
This PR adds `sycl::` prefix to math functions to ensure that we pick up the optimized versions of the math functions as compared to the std:: versions. 
Fixes Issue# 
n/a
Ran this test to simulation and hardware flow
=> FPGA: Add sycl:: prefix to math functions in crr, mvdr, and read_only_cache

DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part2_dpcpp_functor_usm/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part3_dpcpp_lambda_usm/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part4_dpcpp_lambda_buffers/src/CMakeLists.txt
Adding `-Xsparallel=2` to CMakeLists to fix compilation issue in this case:
https://hsdes.intel.com/appstore/article/#/15014227708
=> FPGA: add the `-xsparallel=2` flag to the `fpga_compile` sample

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/max_interleaving/src/CMakeLists.txt
Internal testing showed that the recently `max_interleaving` code sample failed to compile to hardware on Agilex 7 on Windows due to timing errors. 
This PR solves the problem by changing the default seed (from 1 to 2). 
Fixes Issue# 
I have recompiled to hardware on both Linux and Windows for both A10 and S10 and have verified that a seed of 2 compiles successfully.
=> FPGA: Update `max_interleaving` sample to use a different seed by default

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/streaming-invocation/Readme.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/streaming-invocation/src/vector_add.cpp
Change the streaming invocation kernel from a streaming-pipelined kernel to a regular streaming kernel. Pipelining this kernel don't really make sense.
=> FPGA:Component interfaces remove pipeline

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/buffer_kernel.hpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/zero_copy_data_transfer.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/zero_copy_kernel.hpp
This change updates `zero_copy_kernel` sample on how the buffer locations are being selected in the sample to match the new 2024.0 IPA interfaces definitions.
In `zero_copy_kernel` both accessor (requiring device allcoated memory) and USM host pointer are used. In full-system flow, the board spec has defined a device global memory and a host/shared global memory. While in IP-Authoring flow, `buffer_location` should be specified on `accessor` and `annotated_arg` so the compiler can infer global memory interfaces and generate board spec.
=> FPGA: Update zero_copy_kernel sample to support IP-Authoring

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/README.md
add some patter to justify the existence of this directory and explain how to navigate the samples in it
=> FPGA: add first draft of readme in ip authoring interfaces

DirectProgramming/C++SYCL/StructuredGrids/particle-diffusion/src/motionsim_kernel.cpp
The particle diffusion example was failing on Iris Xe graphics due to a lack of double precision. 
Fixes Issue# 
* Check if fp64 is supported on the device
* Fallback to single precision if double is not supported
* Add templated kernel to address the issue
=> [particle-diffuesion] Fix crash on Iris Xe Graphics due to missing fp64 support

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/niosv/README.md
The `niosv` sample relies on the `niosv-shell` toolkit which is not supported on RHEL8
=> FPGA: remove RHEL8 from OS compatibility in the niosv sample

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/sample.json, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/invocation_interfaces/sample.json, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/streaming_data_interfaces/sample.json
Some samples were recently moved to the new `ip_authoring_folder`.
Their `sample.json` files should have been updated in the process.
=> FPGA: Fix broken sample.json files in the ip_authoring_interfaces folder

Libraries/oneMKL/monte_carlo_european_opt/src/montecarlo.hpp
The current name of macro (`DataType`) cause a compilation error for some non-default configurations and, honestly saying, `DataType` doesn't look like a macro name. `DATA_TYPE` looks much better and doesn't cause errors.
Test is passed if add `-DDATA_TYPE` for `GNUmakefile`
Signed-off-by: Fedorov, Andrey <andrey.fedorov@intel.com>
=> Rename a macro for the oneMKL Monte-Carlo Sample #1661

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/sample.json
The `board_test` sample was recently updated to not have a default BSP target. 
This broke the CI tests as the `cmake` configuration failed.
This change sets a target for the CI to run, even if this IPA flow does not really make sense for this test - at least we can test the compiler with the CI.
=> FPGA: fix `board_test` `sample.json` file

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/fft2d/src/fft2d.hpp
The interface width used to be expressed in bytes, where it should have been expressed in bits.
=> FPGA: Fix interface width in the fft2d sample

DirectProgramming/C++SYCL/Jupyter/gpu-optimization-sycl-training/sample.json
=> Request CI to use PVC systems to run GPU Optimization SYCL Training sample so it doesn't time out

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/invocation_interfaces/src/CMakeLists.txt
Remove an unnecessary check for INTELFPGAOCLSDKROOT in DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/invocation_interfaces/src/CMakeLists.txt
The setup scripts should set these variables and the user shouldn't need to worry about this. 
Fixes Issue# n/a
n/a
Ran the test locally with just the base toolkit and fpga addon.
=> Remove INTELFPGAOCLSDKROOT from tutorials

Libraries/oneMKL/binomial/GNUmakefile, Libraries/oneMKL/black_scholes/GNUmakefile, Libraries/oneMKL/block_cholesky_decomposition/GNUmakefile, Libraries/oneMKL/block_cholesky_decomposition/dpbltrf.cpp, Libraries/oneMKL/block_cholesky_decomposition/dpbltrs.cpp, Libraries/oneMKL/block_cholesky_decomposition/factor.cpp, Libraries/oneMKL/block_cholesky_decomposition/solve.cpp, Libraries/oneMKL/block_lu_decomposition/GNUmakefile, Libraries/oneMKL/block_lu_decomposition/factor.cpp, Libraries/oneMKL/block_lu_decomposition/solve.cpp, Libraries/oneMKL/computed_tomography/GNUmakefile, Libraries/oneMKL/fourier_correlation/GNUmakefile, Libraries/oneMKL/matrix_mul_mkl/GNUmakefile, Libraries/oneMKL/monte_carlo_european_opt/GNUmakefile, Libraries/oneMKL/monte_carlo_pi/GNUmakefile, Libraries/oneMKL/monte_carlo_pi/mc_pi_device_api.cpp, Libraries/oneMKL/random_sampling_without_replacement/GNUmakefile, Libraries/oneMKL/sparse_conjugate_gradient/GNUmakefile, Libraries/oneMKL/student_t_test/GNUmakefile
oneAPI release for 2024 will introduce new directory layout changes for toolkits. This PR updates oneMKL samples to use the new directory layout.
run.sh:
```bash
#!/bin/bash
clean_mode=
if [[ $1 == "clean" ]]; then
clean_mode=clean
fi
for s_dir in $(find . -type f -name *GNUmake* -exec echo $(basename {}) \; | sed -e s/GNUmakefile//g);
do
if [[ $s_dir == "./fourier_correlation/" ]]; then
continue
fi
cd $s_dir;
make -f GNUmakefile ${clean_mode};
if [[ $? != 0 ]]; then
echo "$s_dir FAILED"
fi
cd -
done
```
```sh
oneMKL$ ./run.sh > onemkl_test.log 2>&1
oneMKL$ cat onemkl_test.log | grep FAILED
./monte_carlo_pi/ FAILED …
```
=> [oneMKL]Enable support for new Toolkit layout for 2024

AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.ipynb, AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.py
Change type of data provided to the numba_dpex kernel to enable proper execution of the code sample.
Fixes Issue #ONSAM-1651
=> Fix numba_dpex kernel problem

DirectProgramming/C++SYCL/StructuredGrids/guided_HSOpticalFlow_SYCLMigration/02_sycl_migrated/Samples/5_Domain_Specific/HSOpticalFlow/flowSYCL.dp.cpp, DirectProgramming/C++SYCL/StructuredGrids/guided_HSOpticalFlow_SYCLMigration/03_sycl_migrated_optimized/Samples/5_Domain_Specific/HSOpticalFlow/flowSYCL.dp.cpp, DirectProgramming/C++SYCL/VisualizedSamples/GameOfLife/CMakeLists.txt, DirectProgramming/C++SYCL/VisualizedSamples/GameOfLife/GameOfLife.cpp
* GameOfLife is using wmain which does not have support
for Linux. Add main function
* aspect::image is deprecated. ext_intel_legacy_image used instead
=>  fix: GameOfLife and guided_HSOptical Flow

DirectProgramming/C++SYCL/VisualizedSamples/VisualMandlebrot/get_sdl2.sh, DirectProgramming/C++SYCL/VisualizedSamples/VisualMandlebrot/sample.json
* Add script that will download and install SDL2
* Update CI build steps
=> fix: Make sure that VisualMandlebrot builds on linux

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/buffered_host_streaming/src/common.hpp
The amount of work per thread was computed incorrectly, leading to runtime crashes when the number of thread was very high (e.g. 224).
=> FPGA: fix work per thread computation in buffered host streaming sample

Libraries/oneMKL/fourier_correlation/makefile
Fixed the makefile of the Fourier correlation sample to build the fcorr_2d_usm executable.
Fixes Issue# ONSAM-1688 
None
=> Fixed the fcorr_2d_usm build in makefile

DirectProgramming/C++SYCL/VisualizedSamples/GameOfLife/get_sdl2.sh, DirectProgramming/C++SYCL/VisualizedSamples/GameOfLife/sample.json
* add script for SDL library build for easier CI building
=> fix: Add script for SDL2 library GameOfLife sample

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/fft2d/src/fft2d_demo.cpp
Without this explicit wait, the runtime is crashing, this was reported as an internal bug. Adding this wait is a workaround.
=> FPGA: wait for the fft kernel in the fft2d sample loop 

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/src/lib_rtl.v
The `use_library` sample used to have hardcoded `Agilex` in the RTL file.
This change makes this FPGA family parametric based on the cmake configuration.
=> FPGA: fix the `use_library` sample device selection

AI-and-Analytics/Getting-Started-Samples/IntelPython_daal4py_GettingStarted/sample.json
added oneapi setvars. Refer [ONSAM-1650](https://jira.devtools.intel.com/browse/ONSAM-1650)
=> IntelPython_daal4py_GettingStarted (ONSAM-1650)

Libraries/MPI/jacobian_solver/GNUmakefile, Libraries/MPI/jacobian_solver/License.txt, Libraries/MPI/jacobian_solver/README.md, Libraries/MPI/jacobian_solver/sample.json, Libraries/MPI/jacobian_solver/src/01_jacobian_host_mpi_one-sided/GNUmakefile, Libraries/MPI/jacobian_solver/src/01_jacobian_host_mpi_one-sided/mpi3_onesided_jacobian.c, Libraries/MPI/jacobian_solver/src/02_jacobian_device_mpi_one-sided_gpu_aware/GNUmakefile, Libraries/MPI/jacobian_solver/src/02_jacobian_device_mpi_one-sided_gpu_aware/mpi3_onesided_jacobian_gpu_openmp.c, Libraries/MPI/jacobian_solver/src/02_jacobian_device_mpi_one-sided_gpu_aware/mpi3_onesided_jacobian_gpu_sycl.cpp, Libraries/MPI/jacobian_solver/src/03_jacobian_device_mpi_one-sided_device_initiated/GNUmakefile, Libraries/MPI/jacobian_solver/src/03_jacobian_device_mpi_one-sided_device_initiated/mpi3_onesided_jacobian_gpu_sycl_device_initiated.cpp, Libraries/MPI/jacobian_solver/third-party-programs.txt, Libraries/MPI/mpi_send_gpu/GNUmakefile, Libraries/MPI/mpi_send_gpu/License.txt, Libraries/MPI/mpi_send_gpu/README.md, Libraries/MPI/mpi_send_gpu/sample.json, Libraries/MPI/mpi_send_gpu/src/GNUmakefile, Libraries/MPI/mpi_send_gpu/src/mpi_send_gpu_omp.c, Libraries/MPI/mpi_send_gpu/src/mpi_send_gpu_sycl.cpp, Libraries/MPI/mpi_send_gpu/third-party-programs.txt
Added new Libraries/MPI samples:
- The `Distributed Jacobian Solver SYCL/MPI` demonstrates using GPU-aware MPI-3, one-sided communications available in the Intel® MPI Library.
- The `MPI Communications Using GPU Buffers` sample demonstrates how to use GPU support functionality available in Intel® MPI Library.
Administrative
Review
=> Libraries/MPI: added GPU samples

DirectProgramming/C++SYCL/DenseLinearAlgebra/matrix_mul/matrix_mul_dpcpp.vcxproj, DirectProgramming/C++SYCL/GraphTraversal/hidden-markov-models/hidden-markov-models.vcxproj, DirectProgramming/C++SYCL/MapReduce/MonteCarloPi/MonteCarloPi.vcxproj, DirectProgramming/C++SYCL/VisualizedSamples/GameOfLife/GameOfLife.vcxproj
* Updated remaining VS project files to use the compiler for the 2024 version. 
=> fix: Update Visual Studio project files to 2024 compiler

DirectProgramming/C++SYCL/VisualizedSamples/VisualMandlebrot/MandelbrotSDL.vcxproj
Update Compiler version to 2024 for VisualMandlebrot example
=> fix: Update Compiler version to 2024 for Mandlebrot sample

DirectProgramming/C++SYCL/VisualizedSamples/GameOfLife/sample.json, DirectProgramming/C++SYCL/VisualizedSamples/VisualMandlebrot/sample.json
Do not run VisualSamples UI on CI
=> fix: Do not run VisualSamples UI on CI

DirectProgramming/C++SYCL/VisualizedSamples/VisualMandlebrot/Mandel.hpp, DirectProgramming/C++SYCL/VisualizedSamples/VisualMandlebrot/MandelbrotSDL.cpp
* The sample failed on devices that do not support double precision
* Modify MandelbrotParameters class to template to support float and double
* Add two kernels, one for single precision and one for double precision
=> feat: Add support for single and double precision for Mandelbrot

AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/sample.json
Updated `sample.json`. Refer [ONSAM-1694](https://jira.devtools.intel.com/browse/ONSAM-1694)
=> INC-Quantization-Sample-for-PyTorch (ONSAM-1694)

Libraries/oneMKL/matrix_mul_mkl/GNUmakefile, Libraries/oneMKL/matrix_mul_mkl/makefile, Libraries/oneMKL/matrix_mul_mkl/matrix_mul_mkl.cpp, Libraries/oneMKL/matrix_mul_mkl/utilities.hpp
This PR updates the matrix_mul_mkl sample with a much more careful and configurable performance benchmark.
No new dependencies.
=> matrix_mul_mkl: revamp sample

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/sample.json
The `use_library` sample relies on the fpga_crossgen tool which is not installed on the CI machines.
The CI tests are therefore disabled for this sample.
=> FPGA: remove CI tests for the `use_library` sample

Tools/ApplicationDebugger/array-transform/CMakeLists.txt, Tools/ApplicationDebugger/array-transform/README.md, Tools/ApplicationDebugger/jacobi/CMakeLists.txt
Some users have reported that "-g" flag is not always present in their debug builds by default.
The AoT command for the debug build does not require anymore to pass the internal options to the device compiler, and these options are actually harmful. 
sycl-ls stopped showing the device-id, so I removed that from the Readme.
Fixes Issue# 
If "-g" flag is not passed -- the debugger does not stop inside the kernel.
With the previous AoT command there was an internal BP generated at the kernel entry, so w/o the debugger the application seemed hanging.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …
=> ApplicationDebugger: simplify AoT compile command and supply "-g" flag.

RenderingToolkit/Tutorial/PathTracingWithEmbree/cpu/CMakeLists.txt, RenderingToolkit/Tutorial/PathTracingWithEmbree/cpu/README.md
Fixed RenderingToolkit/Tutorial/PathTracingWithEmbree sample for flat dirs... CMakeLists.txt and README.md updated.
Old and new vars files work OK.
CMakeLists: VS_DEBUGGER_ENVIRONMENT property appears to give bugged MSVS project generation per forums discussion, but probably best to leave it in the cmake file.
Fixes Issue# 
ONSAM-1708
Embree now requires sycl DSO even for CPU only targets. Added to README.md. Changed README to use new oneapi-vars.bat file.
Tested both oneapi-vars.bat and setvars.bat with a self-manually created …
=> IRTK embree pathtracer fixes for stb (2024.0)

Libraries/oneMKL/matrix_mul_mkl/README.md
Updates the README after the changes in #1994
=> matrix_mul_mkl: update README

RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/cpu/CMakeLists.txt, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/cpu/README.md, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/gpu/CMakeLists.txt, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/gpu/README.md, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/gpu/build-win-vs-dpcpp-toolchain.bat
Required updates to build this tutorial sample with the 2024.0 release of IRTK. This is one "sample" that has both cpu and gpu targets. The only files that have changed are CMakeLists.txt README.md and a helper script to launch the MSVS toolchain build for 2024.0 compiler.
Fixes Issue# 
N/A (No ticket)
Embree relies on sycl DSO even in CPU mode. This should be included in path automatically with toolkit vars.
Tested on Windows w 2024.0 on CPU, and GPU (NMake and deprecated MSVS Toolchain)
=> IRTK 2024.0 fixes for Tutorials/IntroToRayTracingWithEmbree (CPU and GPU)

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/ResNet50_Inference.ipynb
ONEAPI_ROOT throws error:
./run.sh: line 3: activate: No such file or directory.
Changing it to ONEAPI_INSTALL to be consistent with Tensorflow Getting Started Code
=> Update ResNet50_Inference.ipynb ONEAPI_ROOT to ONEAPI_INSTALL

Libraries/oneDNN/tutorials/sample.json
updated `sample.json` to use `jupyter nbconvert` instead of `runipy`. Refer [fix/ONSAM-1675](https://jira.devtools.intel.com/browse/ONSAM-1675)
=> oneDNN/tutorials (ONSAM-1675)

RenderingToolkit/GettingStarted/02_embree_gsg/gpu/README.md, RenderingToolkit/GettingStarted/02_embree_gsg/gpu/build-win-vs-dpcpp-toolchain.bat
IRTK 2024.0 embree gsg: README and script for windows only to point users to the 2024.0 build tools instead of 2023.
Fixes Issue# 
No ONSAM, but fixes pointing to the latest compiler year from base toolkit.
No dep changes. Just 2024.0 friendly.
Added update to cmake configure to mirror 2024.0 in instructions instead of 2023. Tested on Windows 10 + MSVS 2022 + Base toolkit 2024.0 RC.
=> IRTK 2024.0 emb gsg README and script updates

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/stall_enable/src/CMakeLists.txt
This avoids a timing failure on Stratix10 for the default seed
Generated the makefiles using cmake and looked for -Xsseed=2 argument
=> FPGA: Switch to default seed 2 to avoid Stratix10 timing failures in the `stall_enable` sample

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/stall_enable/src/CMakeLists.txt
Port of https://github.com/oneapi-src/oneAPI-samples/pull/2034
This avoids a timing failure on Stratix10 for the default seed
Generated the makefiles using cmake and looked for -Xsseed=2 argument
=> FPGA: Switch to default seed 2 to avoid Stratix10 timing failures in the stall_enable sample

AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/INC_QuantizationAwareTraining_TextClassification.ipynb, AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/INC_QuantizationAwareTraining_TextClassification.py, AI-and-Analytics/Features-and-Functionality/INC_QuantizationAwareTraining_TextClassification/requirements.txt
Change method for data tokenization to use padding='max_length'
Fixes Issue #1636
I was able to test this change on IDC.
=> Fix ONSAM 1636 - change tokenization padding to max_length

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/sample.json
The CI tests are not running for this sample, so no OS should be specified.
=> FPGA: remove os section in `use_library` `sample.json` file

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/board_test.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/helper.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/usm_speed.hpp
SYCL board_test lagged behind in kernel memory bandwidth performance compared to OpenCL. 
Changes to align performance:
* Update bandwidth calculations to report in MB (1000^2) per second instead of MiB (1024^2) per second. This results in %5 loss in reported performance.
* Add the `-Xshyper-optimized-handshaking=off` flag, which add %0.2 of performance, as it is a slightly better trade off for small designs 
*  Added `sycl::ext::oneapi::no_offset` to utilize aligned LSUs
* Removed unnecessary checks in the kernels
Fixes Issue# 
HSDES: https://hsdes.intel.com/appstore/article/#/14020467958
Test Run:
https://spetc.intel.com/testanalysis?trview=0&testRunIds=8923319
=> FPGA: update the `board_test` sample to match OpenCL performance

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/fft2d/src/fft2d_demo.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/WriteGzip.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/WriteGzip.hpp
The GZIP sample was failing to compile when using GCC 13.1.0 because of the missing include in `WriteGzip.hpp`.
This header was included from the associated `.cpp`, but is now moved to the `.hpp` file directly.
=> FPGA: move the include of `stdint` in the GZIP sample from the `.cpp` to the `.hpp` file

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/fft2d/src/fft2d.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/fft2d/src/fft2d_demo.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/pca/src/pca.hpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/explicit_data_movement/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/device_global/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/hostpipes/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/hostpipes/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/component_interfaces_comparison/sample.json, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/invocation_interfaces/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/invocation_interfaces/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/mmhost/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/mmhost/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ip_authoring_interfaces/streaming_data_interfaces/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/max_reinvocation_delay/README.md
The IP Authoring flow is being renamed to SYCL HLS flow.
=> FPGA: Replace mentions to "IP Authoring flow" to "SYCL HLS flow"

Libraries/MPI/jacobian_solver/sample.json
The code sample failed in Alder lake because Gen12 does not support double precision (float64). Added `gpuRequired` tag to make sure only `gen9` GPUs are used. 
Refer [ONSAM-1721](https://jira.devtools.intel.com/browse/ONSAM-1721) for details
=> added gpuRequired

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_ivdep/src/CMakeLists.txt
Update the default seed for the loop_ivdep code sample to avoid timing violations in Quartus compiles.
=> FPGA: Update seed for `loop_ivdep` sample

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/src/lib_rtl_model.cpp
The `fpga_crossgen` flag `emulation_model` has been renamed to `cpp_model`. The former flag is still supported, but produces a deprecation notice `Warning: --emulation_model is deprecated. Use --cpp_model instead`. This change updates the use_library sample to use the new flag.
Built the use_library sample as usual.
=> FPGA: Update emulation_model flag in use_library sample

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/optimization_targets/README.md
Add new supported flows to the README of optimization_targets.
The README will refer to the new documentation links for individual optimization targets:
- Minimum latency flow: https://www.intel.com/content/www/us/en/docs/oneapi-fpga-add-on/developer-guide/current/minimum-latency-flow.html
- Balanced Throughput-Area Trade-Offs Flow: https://www.intel.com/content/www/us/en/docs/oneapi-fpga-add-on/developer-guide/current/max-throughput.html
- Minimum Area Flow (the link will be created in 2024.1 doc): https://www.intel.com/content/www/us/en/docs/oneapi-fpga-add-on/developer-guide/current/minimum-area.html
=> FPGA: Add new flows to optimization_targets README

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_coalesce/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_coalesce/src/loop_coalesce.cpp
On S10 and Agilex7, the throughput increase described in the README does not appear. In fact, we see a slight decrease in throughput on these boards for some seeds, and the results are equivocal. I changed the sample to no longer report throughput and have the code sample readme reflect this as well.
Instead, I show users the area savings of the `loop_coalesce` sample, which is more consistent.
N/A
=> FPGA: Remove throughput metric from loop_coalesce and update README

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/hostpipes/src/CMakeLists.txt
Remove unnecessary DSP controls use in Host Pipes.
Fixes Issue# https://hsdes.intel.com/appstore/article/#/14021014436
=> FPGA: Remove unnecessary DSP controls use in Host Pipes

DirectProgramming/C++SYCL/CombinationalLogic/mandelbrot/mandelbrot.vcxproj, DirectProgramming/C++SYCL/CombinationalLogic/sepia-filter/sepia-filter.vcxproj, DirectProgramming/C++SYCL/DenseLinearAlgebra/complex_mult/complex_mult.vcxproj, DirectProgramming/C++SYCL/DenseLinearAlgebra/matrix_mul/matrix_mul_sycl.vcxproj, DirectProgramming/C++SYCL/GraphAlgorithms/all-pairs-shortest-paths/all-pairs-shortest-paths.vcxproj, DirectProgramming/C++SYCL/GraphTraversal/bitonic-sort/bitonic-sort.vcxproj, DirectProgramming/C++SYCL/GraphTraversal/hidden-markov-models/hidden-markov-models.vcxproj, DirectProgramming/C++SYCL/MapReduce/MonteCarloPi/MonteCarloPi.vcxproj, DirectProgramming/C++SYCL/N-BodyMethods/Nbody/Nbody.vcxproj, DirectProgramming/C++SYCL/ParallelPatterns/PrefixSum/PrefixSum.vcxproj, DirectProgramming/C++SYCL/ParallelPatterns/loop-unroll/loop-unroll.vcxproj, DirectProgramming/C++SYCL/SparseLinearAlgebra/merge-spmv/merge-spmv.vcxproj, DirectProgramming/C++SYCL/SpectralMethods/DiscreteCosineTransform/msvs/DCT.vcxproj, DirectProgramming/C++SYCL/StructuredGrids/1d_HeatTransfer/1d_HeatTransfer.vcxproj, DirectProgramming/C++SYCL/StructuredGrids/iso2dfd_dpcpp/iso2dfd.vcxproj, DirectProgramming/C++SYCL/StructuredGrids/iso3dfd_dpcpp/iso3dfd.vcxproj, Libraries/oneDPL/dynamic_selection/sepia-filter-ds/sepia-filter.vcxproj, Libraries/oneDPL/dynamic_selection/sepia-filter-ds/sepia-policies.vcxproj, Libraries/oneTBB/tbb-async-sycl/tbb-async-sycl.vcxproj, Libraries/oneTBB/tbb-task-sycl/tbb-task-sycl.vcxproj, Tools/Advisor/matrix_multiply_advisor/matrix_multiply.vcxproj, Tools/ApplicationDebugger/array-transform/array-transform.vcxproj, Tools/VTuneProfiler/matrix_multiply_vtune/matrix_multiply.vcxproj
Updated project files "AdditionalIncludeDirectories" to support both the unified directory layout and the old layout
=> Updated AdditionalIncludeDirectories to support unified layout

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/merge_sort/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/merge_sort/src/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/merge_sort/src/main.cpp
The merge_sort reference design fails in the SYCL HLS flow for versions of Quartus which only support up to 32 bit interrupts (22.2 and earlier). The number of kernels generated with `MERGE_UNITS=P` is `5P-2`, thus decreasing it from `P=8` to `P=4` gives us `5P-2 = 22 < 32` as required.
This change introduces a flag LIMIT_HW_MERGE_UNITS that sets the default MERGE_UNITS to 4 when specified for hardware only, and only in SYCL HLS flow (non-BSP targets). This flag is overridden by the MERGE_UNITS flag, and does not affect the MERGE_UNITS value in simulator or emulator mode.
`cmake .. -DFPGA_DEVICE=<family>` with Quartus 21.2 and 23.3
=> FPGA: Merge Sort Sample Quartus Compatibility Fix 

DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/README.md
The PAC boards are not supported by Intel anymore.
=> FPGA: removed the remaining mentions to PAC boards

DirectProgramming/C++SYCL/SpectralMethods/guided_OceanFFT_SYCLMigration/02_sycl_migrated/Samples/4_CUDA_Libraries/oceanFFT/oceanFFT.cpp.dp.cpp, DirectProgramming/C++SYCL/SpectralMethods/guided_OceanFFT_SYCLMigration/README.md
The OceanFFT sample simulates an Ocean heightfield using oneMKL FFT functionality
=> OceanFFT SYCL Migration sample - 2024.0 update

Libraries/oneDPL/dynamic_selection/sepia-filter-ds/sepia-filter.vcxproj.user, Libraries/oneDPL/dynamic_selection/sepia-filter-ds/sepia-policies.vcxproj, Libraries/oneDPL/dynamic_selection/sepia-filter-ds/sepia-policies.vcxproj.user
Sepia Filter Dynamic Selection Visual Studio Fixes
=> Sepia Filter Dynamic Selection Visual Studio Fixes

DirectProgramming/C++SYCL/guided_concurrentKernels_SYCLMigration/02_sycl_migrated/Samples/0_Introduction/concurrentKernels/concurrentKernels.dp.cpp, DirectProgramming/C++SYCL/guided_concurrentKernels_SYCLMigration/README.md
Re-tested with oneAPI 2024.0.0.
Removed checkCudaErrors from migrated source code.
Updated the Readme.
=> Updated Concurrent Kernels - oneAPI 2024.0 

RenderingToolkit/GettingStarted/01_ospray_gsg/README.md, RenderingToolkit/GettingStarted/02_embree_gsg/README.md, RenderingToolkit/GettingStarted/02_embree_gsg/cpu/README.md, RenderingToolkit/GettingStarted/02_embree_gsg/gpu/README.md, RenderingToolkit/GettingStarted/03_openvkl_gsg/README.md, RenderingToolkit/GettingStarted/03_openvkl_gsg/gpu/README.md, RenderingToolkit/GettingStarted/04_oidn_gsg/README.md, RenderingToolkit/GettingStarted/05_ispc_gsg/README.md, RenderingToolkit/GettingStarted/README.md, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/README.md, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/cpu/README.md, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/gpu/README.md, RenderingToolkit/Tutorial/PathTracingWithEmbree/cpu/README.md
README issues only with 2024.0 updates for IRTK:
- OSPRay documentation now correctly instructs required toggles to target GPU (oops) `--osp:load-modules=gpu --osp:device=gpu`
- README review: Improved GPU configuration and expectation setting for applicable programs, req'd fixes to product names.
Fixes Issue# 
N/A
N/A
Required toggle added to documentation. Testing preexisting in samples.json validation.
=> 2024.0 fix: README issues only for IRTK (GPU instructions + Product Names)

DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/sample.json
Modified sample.json in vector-add to support Eclipse IDE.
=> Update sample.json in vector-add to support Eclipse

RenderingToolkit/GettingStarted/01_ospray_gsg/README.md, RenderingToolkit/GettingStarted/02_embree_gsg/README.md, RenderingToolkit/GettingStarted/02_embree_gsg/cpu/README.md, RenderingToolkit/GettingStarted/02_embree_gsg/gpu/README.md, RenderingToolkit/GettingStarted/03_openvkl_gsg/README.md, RenderingToolkit/GettingStarted/03_openvkl_gsg/gpu/README.md, RenderingToolkit/GettingStarted/04_oidn_gsg/README.md, RenderingToolkit/GettingStarted/05_ispc_gsg/README.md, RenderingToolkit/GettingStarted/README.md, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/README.md, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/cpu/README.md, RenderingToolkit/Tutorial/IntroToRayTracingWithEmbree/gpu/README.md, RenderingToolkit/Tutorial/PathTracingWithEmbree/cpu/README.md
Same description as https://github.com/oneapi-src/oneAPI-samples/pull/2106
README issues only with 2024.0 updates for IRTK:
- OSPRay documentation now correctly instructs required toggles to target GPU (oops) `--osp:load-modules=gpu --osp:device=gpu`
- README review: Improved GPU configuration and expectation setting for applicable programs, req'd fixes to product names.
Fixes Issue# 
N/A
N/A
Required toggle added to documentation. Testing preexisting in samples.json validation.
=> 2024.0_updates branch fix: README issues only for IRTK (GPU instructions + Product Names)

DirectProgramming/C++SYCL/DenseLinearAlgebra/simple-add/sample.json, DirectProgramming/C++SYCL/DenseLinearAlgebra/vector-add/sample.json
These two samples were not working using the Eclipse plugin because the incorrect build type was specified in their `sample.json` files.
=> FPGA: fix build type in simple-add/vector-add sample.json files

DirectProgramming/Fortran/EdgeDetection/sobel-edge-detection/sobel_do_concurrent.F90
I added a dummy target region to the Fortran DO CONCURRENT example, as per our OpenMP offload best practices recommendations at https://www.intel.com/content/www/us/en/docs/oneapi/optimization-guide-gpu/2024-0/openmp-offload-best-practices.html.
Fixes Issue# 
None
=> Added OpenMP target dummy region to DO CONCURRENT example

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/max_interleaving/CMakeLists.txt
Add -Wno-unused-label to the compile flags. The unused label in the source code is part of the FPGA loop label feature, and will be used in the FPGA report. 
=> ignore unused label warning

Tools/GPU-Occupancy-Calculator/README.md, Tools/GPU-Occupancy-Calculator/index.html
updated GPU Occupancy Calculator with new PVC values, added 512 and 896 EU count, updated readme
=> updated GPU Occupancy Calculator with new PVC values

Libraries/oneMKL/batched_linear_solver/README.md
Updated README.md to use single precision option for devices not supporting double precision option(gen11, gen12).
Fixes Issue# 
=> Updated README.md with single precision option for batched_linear_solver Sample

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/README.md
Remove uses of the deprecated `--target` flag in the library flow tools (fpga_crossgen, fpga_libtool).
Use of that flag causes warning: "_The --target flag is deprecated and will be ignored! This tool can only be used to target sycl_".
Fixes Issue: https://hsdes.intel.com/appstore/article/#/14021184709
N/A
=> FPGA: Remove uses of the deprecated `--target` flag in the library flow tools

Publications/GPU-Opt-Guide/joint-matrix/joint-matrix.cpp
The test was behind compared to what we have to the GPU optimization guide.
GPU optimization guide 
tested on PVC machine 
icpx -fsycl joint-matrix.cpp
./a.out
=> [GPU opt guide][SYCL][joint matrix] update the test to match the guide

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/README.md
This reverts commit 920e25d5d95091c8f854070fd9df35e839fb0f3d on 2024.1.
The change will be re-submitted to 2024.2 later.
N/A
=> FPGA: Revert "Remove uses of the deprecated `--target` flag in the library flow tools (#2120)"

AI-and-Analytics/Features-and-Functionality/IntelPytorch_Interactive_Chat_Quantization/sample.json
Remove jupyter nbconvert from sample.json
Jupyter kernel dosen't support std input. As the python script and jupyter notebook are the same, I suggest to leave only the *.py script during CI testing.
Fixes Issue# ONSAM-1817
=> [ONSAM-1817] IntelPytorch_Interactive_Chat_Quantization 

RenderingToolkit/GettingStarted/03_openvkl_gsg/sample.json
Addresses MacOS validation in sample.json for ONSAM-1782.
Background: Env vars appeared to need to be reexported because I was told the testing environment does python forks... and those forks don't allow for inheriting dynamic runtime search paths.
Per expectations set on that system under test, this should unblock macOS runs for the 03_openvkl_gsg sample. On macOS this sample is CPU only.
The removed json script assumed (and confused) oneapi-vars and setvars.
Fixes Issue# 
ONSAM-1782.
None
N/A (Can't test a work around specifically for the test SUT)
=> [IRTK fix]: macos vklsample validation for setvars env only

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/ResNet50_Inference.ipynb
Update jupyter notebook metadata to use tensorflow kernel from sample.json file instead of custom named kernel
Fixes Issue#ONSAM-1820
Change tested on IDC using command line
=> ONSAM-1820 IntelTensorFlow_ModelZoo "jupyter_client.kernelspec.NoSuchKernel" error

Libraries/oneDNN/tutorials/profiling/profile_utils.py
Fix the parsing error in profile_utils.py when passing the [oneDNN v3.3.2 ](https://github.com/oneapi-src/oneDNN/releases/tag/v3.3.2) verbose log with `backend` (`primitive`/`graph`) information
Currently, when passing a oneDNN verbose log to python_utils script with `backend` (`primitive`/`graph`) lines, the script outputs parsing error.
A verbose log generated by [oneDNN v3.3.2](https://github.com/oneapi-src/oneDNN/releases/tag/v3.3.2):
```
onednn_verbose,info,oneDNN v3.3.2 (commit 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
onednn_verbose,info,cpu,runtime:OpenMP,nthr:1
onednn_verbose,info,cpu,isa:Intel AVX-512 with Intel DL Boost
onednn_verbose,info,gpu,runtime:none
onednn_verbose,info,graph,backend,0:dnnl_backend
onednn_verbose,primitive,info,template:timestamp,operation,engine,primitive …
```
=> [oneDNN][profile_utils.py] fix parse error with oneDNN v3.3.2

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/ResNet50_Inference.ipynb, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/ResNet50_Inference_gpu.ipynb
Updated script paths in both cpu and gpu inference jupyter notebook files. 
The path reflects install path for oneAPI AI Kit form sample.json file.
Fixes Issue#ONSAM-1820
=> ONSAM-1820 IntelTensorFlow_ModelZoo_Inference 'models/benchmarks/launch_benchmark.py' not found

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/mem_channel/src/CMakeLists.txt
Fix a compiler error for a code sample that uses an outdated CMake file.
Fixes Issue# https://jira.devtools.intel.com/browse/ONSAM-1810
=> Partial fix for onsam 1810

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/convolution2d/src/convolution_kernel.hpp
Fixes Issue# none
* Full Linux: https://spetc.intel.com/testanalysis?trview=0&testRunIds=9567514&tapgsize=20
* Single kernel linux: https://spetc.intel.com/testanalysis?trview=0&testRunIds=9567535&tapgsize=20
* Full Windows: https://spetc.intel.com/testanalysis?trview=0&testRunIds=9574476&tapgsize=2 …
=> FPGA: constrain while(1) loops in the convolution2d sample

Libraries/oneDNN/tutorials/sample.json
Removed `tutorial_vtune_profiling.ipynb` conversion step because it times out.
=> libraries tutorials::vtune_itt sample failed due to "Converting notebook tutorial_vtune_profiling.ipynb to notebook" error [ONSAM-1796]

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/board_test.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/host_speed.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/gzip.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/pca/src/golden_pca.hpp
A recent change to the compiler now makes it emit warnings about variable length arrays as not being part of C++.
This change replaces the variable lengths arrays with mallocs/vectors to avoid this warning.
=> FPGA: Stop using variable length arrays in FPGA samples

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/streaming_data_interfaces/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/streaming_data_interfaces/src/streaming_data_interfaces.cpp
Fixes Issue# https://hsdes.intel.com/appstore/article/#/14019166650
also ran clang-format on the code sample
=> FPGA: update `streaming_data_interfaces` to use correct type

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/board_test.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/gzip.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/gzipkernel.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/gzipkernel.hpp
Reduce the use of mallocs and prefer `std::vectors` instead.
=> FPGA: reduce use of mallocs

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/convolution2d/CMakeLists.txt
Renamed the exe target name from `conv` to `convolution`.
=> FPGA: rename target name in the `convolution` sample

DirectProgramming/C++SYCL/guided_simpleAtomicIntrinsics_SYCLMigration/02_sycl_migrated/Samples/0_Introduction/simpleAtomicIntrinsics/simpleAtomicIntrinsics_cpu.cpp, DirectProgramming/C++SYCL/guided_simpleAtomicIntrinsics_SYCLMigration/02_sycl_migrated/Samples/0_Introduction/simpleAtomicIntrinsics/simpleAtomicIntrinsics_kernel.dp.hpp, DirectProgramming/C++SYCL/guided_simpleAtomicIntrinsics_SYCLMigration/README.md
In the source code Atomic Inr and Atomic Dec are disabled as it has a performance issue.
=> Disabled atomic_inr and atomic_dec for guided_simpleAtomicIntrinsics_SYCLMigration sample

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/README.md
Document compiler bug exposed by use_library tutorial on Windows.
Fixes Issue# https://hsdes.intel.com/appstore/article/#/15015624709
=> FPGA: Document compiler bug exposed by `use_library` tutorial on Windows

Libraries/oneMKL/binomial/src/binomial.hpp, Libraries/oneMKL/binomial/src/binomial_main.cpp, Libraries/oneMKL/binomial/src/binomial_sycl.cpp, Libraries/oneMKL/black_scholes/src/black_scholes.hpp, Libraries/oneMKL/black_scholes/src/black_scholes_sycl.cpp, Libraries/oneMKL/monte_carlo_european_opt/src/montecarlo.hpp, Libraries/oneMKL/monte_carlo_european_opt/src/montecarlo_main.cpp
Change sources to switch to `float` if device doesn't support `fp64`. Following samples are affected by changes:
* black scholes
* binomial
* european monte-carlo
=> reworked samples to split it by fp64 support

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning/README.md, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning/sample.json
TensorFlow-hub dependency will install newer TF version and overwrite one in AI Kit.
remove the installation dependency
Fixes Issue# ONSAM-1813
NA
=> [ONSAM-1813] fix a tensorflow-hub dependency issue

AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/README.md
Modin Get Started Sample Changes by Stefana Raileanu
=> template 2024.1

Libraries/oneDNN/tutorials/profiling/profile_utils.py
oneDNN verbose log changes since 3.4. change profile_utils.py to parse the new log format
Fixes Issue# [ONSAM-1856](https://jira.devtools.intel.com/browse/ONSAM-1856)
NA
=> [ONSAM-1856 ]onednn profile util fix for v3.4

RenderingToolkit/IRTK_Learning_Path/README.md
Update learning path readme to notify users of 2-tile environment variable need
Fixes Issue# 
Email discussion
No change
Jimmy tested, reviewed changes in README.md via browser
=> IRTK Learning Path README.md Max 2-tile env var

Libraries/oneMKL/batched_linear_solver/lu_solve_omp_offload_optimized.F90
Fixes a page fault that is visible when looking at dmesg output. The ipiv array must still be allocated on the host even when using the OpenMP "map" with alloc attribute. Thanks and credit goes to Sergey Kiselev for rootcausing the issue and providing a fix!
None
Tested locally that the page fault is visible with the sample code as written and that the page fault disappears with the change in this PR.
=> [oneMKL] Fix batched linear solver sample page fault

Libraries/oneMKL/black_scholes/README.md, Libraries/oneMKL/block_cholesky_decomposition/README.md, Libraries/oneMKL/block_lu_decomposition/README.md, Libraries/oneMKL/computed_tomography/README.md, Libraries/oneMKL/monte_carlo_european_opt/README.md
It's useful to link oneMKL Samples with [oneMKL cookbook recipes](https://www.intel.com/content/www/us/en/docs/onemkl/cookbook/current/overview.html). Following samples have been changed:
* Black-Scholes
* Block Cholesky Decomposition
* Block LU Decomposition
* Computed Tomography Reconstruction
* Monte Carlo European Options
List any external dependencies created as a result of this change:
* Links to https://www.intel.com/content/www/us/en/docs/onemkl/cookbook/current/overview.html
N/A
=> Add links to Cookbook recipes for oneMKL Samples

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/board_test.hpp
Update the board_test code sample to adhere to the new reqd_work_group_size syntax.
=> FPGA: fix syntax of `reqd_work_group_size`

DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/2_guided_jacobi_iterative_solver_gpu.cpp, DirectProgramming/C++SYCL/DenseLinearAlgebra/guided_jacobi_iterative_gpu_optimization/src/3_guided_jacobi_iterative_solver_multi_gpu.cpp, DirectProgramming/C++SYCL/MapReduce/MonteCarloPi/src/monte_carlo_pi.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/hostpipes/src/hostpipes.cpp
SYCL math builtins may cause ambiguity issues with std versions of the same builtins if it is not qualified by its namespace. This commit addresses this issue in select samples.
Replaces https://github.com/oneapi-src/oneAPI-samples/pull/2289.
None
As specified in the sample directories.
=> Fix SYCL math builtin ambiguity

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/mvdr_beamforming/src/mvdr_beamforming.cpp
This PR moved a dma wait event inside the appropriate if statement it is attached to, fixing a compile error when using REAL_IO_PIPES.
Addresses https://github.com/oneapi-src/oneAPI-samples/issues/2201
=> FPGA: fix incorrectly placed event wait when using REAL_IO_PIPES in mvdr

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/mem_channel/CMakeLists.txt
This change adds a print statement of the `DEVICE_FLAG` so that a CMake "unused variable" warning is not emitted.
* N/A
Manually compiled the design to reports to make sure that the cmake warning is no longer displayed to users and that the proper flags are still being passed to the design. When users run cmake they will now see output that looks something like the following:
```
-- The CXX compiler identification is IntelLLVM 2024.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /p/psg/swip/hld/r/sycl/rel/20240417/linux64/compiler/latest/bin/icpx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- …
```
=> FPGA: Add print statement to mem_channel tutorial to avoid cmake warning

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/crr/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/crr/README.md
Modifies the CMakeLists for the CRR FPGA code sample so that we use the same unroll factors for all platforms and expose the option to modify these unroll factors to the users. The change also updates the readme to reflect these changes.
=> FPGA: Unify the `crr` configuration across FPGA targets

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/cholesky/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/cholesky_inversion/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/crr/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/fft2d/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/merge_sort/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/mvdr_beamforming/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/pca/README.md, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/qri/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/double_buffering/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/loop_carried_dependency/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/n_way_buffering/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/onchip_memory_cache/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/optimize_inner_loop/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/shannonization/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/triangular_loop/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/kernel_args_restrict/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/loop_unroll/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/max_interleaving/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/mem_channel/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/private_copies/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/read_only_cache/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/speculated_iterations/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/stall_enable/README.md, DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/system_profiling/README.md
This PR moves all the code samples HW references from the Terasic DE10 board to the N6001 board.
=> FPGA: Move all samples from the DE10 to the N6001 board

DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/CMakeLists.txt
This change fixes the CMakeLists.txt for zero_copy_data_transfer so that it adds the -DIS_BSP flag to the compile flags.
N/A
=> FPGA: fix `zero_copy_data_transfers` `CMakelist.txt` to add the appropriate `-DIS_BSP` flags

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/component_interfaces_comparison/csr-pipes/src/vector_add.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/component_interfaces_comparison/mm-host/src/vector_add.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/component_interfaces_comparison/naive/src/vector_add.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/component_interfaces_comparison/pipes/src/vector_add.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/component_interfaces_comparison/streaming-invocation/src/vector_add.cpp
- improve comparibility across code versions
- remove unnecessary ready signal from csr-pipes version
- re-run clang-format
Fixes Issue# 
=> FPGA: Tidy up Component Interfaces Comparison code sample

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/anr/src/anr.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/src/matmul_demo.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/ac_fixed/src/ac_fixed.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/optimization_targets/src/optimization_targets.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/speculated_iterations/src/speculated_iterations.cpp
Upstream LLVM removed the auto-included `math.h`, making some samples fail to compile without explicitly including `math.h` or using the `sycl::` equivalent.
=> FPGA: Fix ambiguity of math function calls

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/merge_sort/src/main.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/mvdr_beamforming/src/FakeIOPipes.hpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/buffered_host_streaming/src/HostStreamer.hpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/buffered_host_streaming/src/streaming_without_api.hpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/io_streaming/src/FakeIOPipes.hpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/simple_host_streaming/src/multi_kernel.hpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/simple_host_streaming/src/single_kernel.hpp
Raw `host_prt` and `device_ptr` are to be deprecated.
Their replacements are `sycl::ext::intel::host_ptr` and `sycl::ext::intel::device_ptr`.
This PR updates the code samples that relied on these constructs.
=> FPGA: Update `host_ptr` and `device_ptr` to appropriate namespace

Tools/GPU-Occupancy-Calculator/README.md, Tools/GPU-Occupancy-Calculator/index.html
updated GPU Occupancy Calculator - added new GPUs, updated calculator UI, added help section
=> updated GPU Occupancy Calculator

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_PyTorch_GettingStarted/README.md
Fixes Issue# 
Administrative
Review
=> Update README.md to development

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/anr/src/main.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/experimental/annotated_class_clean_coding/src/annotated_class_util.hpp
Remove redundant sycl::ext::oneapi::experimental::detail::empty_properties_t and replace it with sycl::ext::oneapi::experimental::empty_properties_t https://jira.devtools.intel.com/browse/ONSAM-1938
Specify std::log10 to avoid ambiguity. Issue was introduced with sycl/trunk/20240502 https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/1727201571
=> FPGA: Remove detail::empty_properties_t and add std::log10

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/platform_designer/README.md
Add a disclaimer for the Platform Designer code sample, since the pre-generated quartus project definitely doesn't work with Quartus® Prime 21.2. Confirm that re-building the project as shown in directions works though.
Fixes Issue# 
=> FPGA: add caveat for running the `build_system.tcl` script in the `platform_designer` code sample

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/gzipkernel_ll.cpp
This change implements a workaround for a bug affecting FPGA targets.  The bug and workaround will be documented in the upcoming 2024.2 release notes.  This workaround can be removed when the underlying bug is fixed (presumably in 2025.0).  
Specifically, when kernels are explicitly made dependent on other invocations of the same kernel through events, the FPGA runtime can occasionally hang.  The hang is rare, but since the gzip_ll code sample attempts to enqueue kernels in this way hundreds of times it has a good chance of hitting it on any given run.  
Unfortunately, this code sample seems to be affected by a second, unrelated hang though because while this fix allows the program to complete some of the time, it still hangs periodically.  Runtime traces of those remaining hangs indicate …
=> FPGA: Worked around runtime bug with event dependences between invocations of the same kernel

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/usm_speed.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/cholesky/src/cholesky.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/cholesky/src/memory_transfers.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/cholesky_inversion/src/memory_transfers.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/decompress/src/common/common.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/decompress/src/gzip/gzip_metadata_reader.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/decompress/src/snappy/snappy_reader.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/gzipkernel_ll.cpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/matmul/src/memory_transfers.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/pca/src/memory_transfers.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/qri/src/memory_transfers.hpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/explicit_data_movement/src/explicit_data_movement.cpp, DirectProgramming/C++SYCL_FPGA/Tutorials/DesignPatterns/zero_copy_data_transfer/src/zero_copy_kernel.hpp
The `host_ptr` and `device_ptr` constructs have been moved to the `sycl::ext:intel::` namespace.
=> FPGA: fix namespaces for `host_ptr` and `device_ptr`

DirectProgramming/C++SYCL/Jupyter/cuda-to-sycl-migration-training/06_SYCL_Migration_SimpleCUDAGraphs/sycl_migrated_option1/Samples/3_CUDA_Features/simpleCudaGraphs/simpleCudaGraphs.dp.cpp, DirectProgramming/C++SYCL/Jupyter/cuda-to-sycl-migration-training/06_SYCL_Migration_SimpleCUDAGraphs/sycl_migrated_option2/Samples/3_CUDA_Features/simpleCudaGraphs/simpleCudaGraphs.dp.cpp, DirectProgramming/C++SYCL/SYCLMigration/guided_simpleCudaGraphs_SYCLMigration/02_sycl_migrated_option1/Samples/3_CUDA_Features/simpleCudaGraphs/simpleCudaGraphs.dp.cpp, DirectProgramming/C++SYCL/SYCLMigration/guided_simpleCudaGraphs_SYCLMigration/02_sycl_migrated_option2/Samples/3_CUDA_Features/simpleCudaGraphs/simpleCudaGraphs.dp.cpp, DirectProgramming/C++SYCL/SYCLMigration/guided_simpleCudaGraphs_SYCLMigration/README.md
Updated/bug fix for guided_simpleCudaGraph_SYCLMigration sample in SYCLMigration and Jupyter/cuda-to-sycl-migration-training folder.
=> Updated simpleCudaGraphs migration sample for oneAPI 2024.2 release. 

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/db/src/db_utils/fifo_sort.hpp
This reverts commit 75397ca0f4d3618f570188297b1e896d0409b18c that initially went in to prevent an error from being emitted to customers.
* N/A
* I manually compiled the DB code sample, specifically query 9, and the compiler no longer emits an error (crash)
=> FPGA: Revert "Remove fpga_register annotations from fifo_sort"

Publications/GPU-Opt-Guide/explicit-scaling/07_explicit_subdevice/explicit_subdevice.cpp
Use default array size 128 if no array size is specified
Gracefully exit if a device does not have subdevices
Remove compilation warnings with the latest compiler
Fixes Issue# ONSAM-1905
None
=> Fix ONSAM-1905

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/fft2d/src/fft2d.hpp
1. Fix array index out of bound in function `ReorderData`
2. Fix use of uninitialized array `fft_delay_elements`
=> FPGA: Bug fixes for the `fft2d` sample

DirectProgramming/C++SYCL/SYCLMigration/guided_radixSortThrust_SYCLMigration/02_sycl_dpct_migrated/src/radixSortMigrated.cpp
Fix for ONSAM-1942. Adding explicit headers.
Fixes Issue# 
https://jira.devtools.intel.com/browse/ONSAM-1942
Tests rran in CL and VSCode.
=> Add explicit headers for radix_sort_migrated

DirectProgramming/C++SYCL/StructuredGrids/guided_iso3dfd_GPUOptimization/src/Utils.hpp
Fix for ONSAM JIRA 1941. Explicitly adding headers.
Fixes Issue# 
https://jira.devtools.intel.com/browse/ONSAM-1941
Tested in CL and VSCode
=> Add explicit headers for iso3dfd

DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/component_interfaces_comparison/sample.json, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/mmhost/sample.json, DirectProgramming/C++SYCL_FPGA/Tutorials/Features/hls_flow_interfaces/streaming_data_interfaces/sample.json
Correct 'categories' for hls flow/interfaces code samples so they group together nicely in the sample browser
No tests as this is a metadata change to group items correctly in the sample browser.
=> FPGA: correct 'categories' for hls flow/interfaces code samples

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/gzip.cpp
The gzip code sample included a memory allocation of the size of the file to be compressed, which was issued for every repeated iteration of the kernel.
This led to increasingly large host memory allocation when the file to compress was increasing in size.
However, the allocated memory was never used.
This change therefore removes the unneeded allocation.
=> FPGA: Remove unused memory allocation in the gzip sample

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_ModelZoo_Inference_with_FP32_Int8/README.md, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Transformer_AMX_bfloat16_MixedPrecision/sample.json, AI-and-Analytics/Getting-Started-Samples/INC-Sample-for-Tensorflow/sample.json
intel uses conda forge channel instead of default channel, so instructions needed to be updated.
Fixes Issue# 
ONSAM-1973, 1972, 1970
NA
=> 2024.2 install changes for conda forge 

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/board_test/src/board_test.hpp
This changes follows up the removal of `cmath` from the `sycl.hpp` header - which now requires to be added manually for designs that require it.
In addition, `fabs` lives in both `std::` and `sycl::` and should therefore be qualified to remove the ambiguity.
=> FPGA: Qualify fabs in the `board_test` sample

DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part3_dpcpp_lambda_usm/src/vector_add.cpp
Replace CL/sycl.hpp with sycl/sycl.hpp for fpga_compile because it is deprecated
=> FPGA: Replace CL/sycl.hpp with sycl/sycl.hpp for fpga_compile

Publications/GPU-Opt-Guide/sub-group/transpose.cpp
Replace deprecated SYCL APIs with new APIs in Publications/GPU-Opt-Guide/sub-group/transpose.cpp
Fixes Issue# 
ONSAM-1997
None
=> Fix ONSAM-1997

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/decompress/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/decompress/src/gzip/byte_bit_stream.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/decompress/src/snappy/snappy_reader.hpp
This PR adds a template argument list after the template keyword. This is now required with newer versions of SYCL.
This change also adds a print message for the DEVICE_FLAG variable so that we are not getting any CMake unused variable warnings when running this design.
* Manually compiled the design with `make report` to make sure that there is no longer a CMake warning, and that the SYCL error is gone.
=> FPGA: Add in template argument list after template keyword

AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/README.md
Update README.md file for IntelPython_Numpy_Numba_dpex_kNN code sample to reflect new AI README Template and explain how to install IDP using offline installer.
Code sample maintenece
N/A
=> Upadte readme IntelPython_Numpy_Numba_dpex_kNN

DirectProgramming/Fortran/guided_Coarray/README.md
Adding quotation marks on setvars command in README from `C:\Program Files (x86)\Intel\oneAPI\setvars.bat` to `C:\"Program Files (x86)"\Intel\oneAPI\setvars.bat`
Fixes Issue# ONSAM-1989
None
=> Fix Coarray Sample setvars command in README (dev)

DirectProgramming/Fortran/guided_Coarray/README.md
Adding quotation marks on setvars command in README from `C:\Program Files (x86)\Intel\oneAPI\setvars.bat` to `C:\"Program Files (x86)"\Intel\oneAPI\setvars.bat`
Fixes Issue# ONSAM-1989
None
=> Fix Coarray Sample setvars command in README (rel)

Tools/VTuneProfiler/tachyon/README.md
This change fixes an error in the Taychon Sample README. The filename for the optimized OpenMP executable should be `tachyon.openmp_optimized`, not `tachyon.openmp_solution`.
Fixes Issue# ONSAM-2000
None.
=> Fix Tachyon filename in README (dev)

Tools/VTuneProfiler/tachyon/README.md
This change fixes an error in the Taychon Sample README. The filename for the optimized OpenMP executable should be `tachyon.openmp_optimized`, not `tachyon.openmp_solution`.
Fixes Issue# ONSAM-2000
None.
=> Fix Tachyon filename in README (rel)

DirectProgramming/C++SYCL/ParallelPatterns/PrefixSum/src/PrefixSum.cpp, DirectProgramming/C++SYCL/ParallelPatterns/histogram/src/main.cpp, DirectProgramming/C++SYCL/StructuredGrids/1d_HeatTransfer/src/1d_HeatTransfer.cpp
Explicit add of two headers for a bunch of samples
Fixes Issue# 
https://jira.devtools.intel.com/browse/ONSAM-1869
=> Add headers

DirectProgramming/Fortran/DenseLinearAlgebra/vectorize-vecmatmult/README.md
This changes added the steps/instructions to run the Vectorize VecMatMult Sample on Windows OS.
Fixes Issue# ONSAM-1988
None.
=> Add Vectorize VecMatMult Windows instruction (rel)

DirectProgramming/Fortran/DenseLinearAlgebra/vectorize-vecmatmult/README.md
This changes added the steps/instructions to run the Vectorize VecMatMult Sample on Windows OS.
Fixes Issue# ONSAM-1988
None.
=> Add Vectorize VecMatMult Windows instruction (dev)

Tools/Advisor/matrix_multiply_advisor/README.md
This changes fixed the "How to run the sample" section to be consistent with other sample's README format. It updated the how to build section on Linux and Windows OS and added How to run on Linux environment, Windows Visual Studio, and Windows CLI. Besides, it modified Example of Output based on the result obtained when run this sample code.
Fixes Issue# ONSAM-1993
None.
=> Fix matrix_multiply_advisor README format (dev)

Libraries/oneDNN/getting_started/README.md
This change fixes the compiler environment variables in the oneDNN getting started README.
For GNU C++ Compiler, `CC=GCC CXX=g++ cmake ..` should be `CC=gcc CXX=g++ cmake ..`.
For Intel C++ Compiler, `CC=icc CXX=icpc cmake ..` should be `CC=icx CXX=icpx cmake ..`.
Fixes Issue# ONSAM-1992
None.
=> Fix compiler env variable in oneDNN README (dev)

Libraries/oneDNN/getting_started/README.md
This change fixes the compiler environment variables in the oneDNN getting started README.
For GNU C++ Compiler, `CC=GCC CXX=g++ cmake ..` should be `CC=gcc CXX=g++ cmake ..`.
For Intel C++ Compiler, `CC=icc CXX=icpc cmake ..` should be `CC=icx CXX=icpx cmake ..`.
Fixes Issue# ONSAM-1992
None.
=> Fix compiler env variable in oneDNN README (rel)

Libraries/oneTBB/tbb-async-sycl/README.md
This change fixes some formatting issues with the TBB-Async-Sycl sample README. When the README is rendered, commands can now be copied directly using the copy icon to the right of the code snippet. The "Visual Studio IDE" bullet list is no longer rendered as a code snippet. Finally, the "Example of Output" is now formatted as a code snippet rather than indented for clarity.
Fixes Issue# ONSAM-1987
None.
=> Fix TBB-Async-Sycl README format (dev)

Libraries/oneTBB/tbb-async-sycl/README.md
This change fixes some formatting issues with the TBB-Async-Sycl sample README. When the README is rendered, commands can now be copied directly using the copy icon to the right of the code snippet. The "Visual Studio IDE" bullet list is no longer rendered as a code snippet. Finally, the "Example of Output" is now formatted as a code snippet rather than indented for clarity.
Fixes Issue# ONSAM-1987
None.
=> Fix TBB-Async-Sycl README format (rel)

AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpex_kNN/IntelPython_Numpy_Numba_dpex_kNN.ipynb
added missing argument when calling numba_dpex kernel.
=> [release/2024.2_AITools] added missing argument in numba_dpex kernel call

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning/README.md, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning/enabling_automixed_precision_for_transfer_learning_with_tensorflow.ipynb, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning/requirements.txt, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning/scripts/tf_benchmark.py
- Remove TF Serving from the jupyter notebook and add it to the README for user's reference.
- Choose precision for inference based on the underlying architecture.
- Update `requirements.txt` to include `neural_compressor` (used to load the model for inference) and `py-cpuinfo`.
Fixes Issue# 
- CI was failing as the port for TF Serving was not exposed to the public.
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
=> [release/2024.2_AITools] Remove TF Serving

AI-and-Analytics/Features-and-Functionality/IntelTransformers_Quantization/sample.json
sample.json file used `jupyter nbconvert` command to execute the notebook. But since the notebook required manual restart after loading each model, it was not possible to run it in CI. So, replace notebook execution command with python script. 
=> removed notebook execution command

AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/ResNet50_Inference.ipynb, AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/requirements.txt, AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/sample.json
- Updated jupter nbconvert command sample.json file
- Updated AI_Toolkit activation path and other minor changes to the notebook.
Fixes Issue# 
=> [release/2024.2_AITools] updated ITEX Getting Started sample

AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_TextGeneration_with_LSTM/TextGenerationModelTraining.ipynb, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_TextGeneration_with_LSTM/TextGenerationModelTraining.py, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_TextGeneration_with_LSTM/sample.json
Running training with 200 epoch is too long for CI.  Add env variable to control number of epochs.
=> ci: Enable faster execution on CI

Libraries/oneMKL/sparse_conjugate_gradient/sparse_cg.cpp
Updated oneMKL API for the Sparse Conjugate Gradient sample
=> [oneMKL] Updated oneMKL API for Sparse Conjugate Gradient 

Libraries/oneMKL/student_t_test/t_test.cpp
Replaced `sycl::` with `std::` for math functions in the Student's T-test sample
=> [oneMKL] Fixed namespace for math functions in Student's T-test

Libraries/oneMKL/student_t_test/t_test_usm.cpp
Replaced `sycl::` with `std::` for math functions in the Student's T-test sample (USM version)
=> [oneMKL] Fixed namespace for math functions in Student's T-test. USM version

Publications/GPU-Opt-Guide/joint-matrix/joint-matrix.cpp
Updated oneAPI-samples/Publications/GPU-Opt-Guide/joint-matrix/joint-matrix.cpp
Add explicit std to the math function used in the test and include <cmath>
Fixes Issue# 
https://jira.devtools.intel.com/browse/ONSAM-1933
- [x ] Implement fixes for ONSAM Jiras
tested on PVC machine
icpx -fsycl joint-matrix.cpp
./a.out
=> [GPU opt guide][SYCL][joint matrix] Add explicit std <cmath> to math function

DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/06_Intel_VTune_Profiler/vtune_collect.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_binary_search.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_counting_iterator.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_discard_iterator.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_ex_scan.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_in_scan.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_lower_bound.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_max.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_min.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_permutation_iterator.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_ranges.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_reduce_segment.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_stable_sort.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_transform_iterator.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_upper_bound.sh, DirectProgramming/C++SYCL/Jupyter/oneapi-essentials-training/07_oneDPL_Library/run_zip_iterator.sh, DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/run_all.sh, DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/run_mm_basic.sh, DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/run_mm_basic_full.sh, DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/run_mm_localmem.sh, DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/run_mm_localmem_wg.sh, DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/run_mm_mkl.sh, DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/run_mm_ndrange.sh, DirectProgramming/C++SYCL/Jupyter/sycl-performance-portability-training/run_mm_ndrange_var.sh
Fixed oneapi env var path in trainings from old IDC path to current
=> Fixed oneapi env var path in trainings

Libraries/oneMKL/guided_cuBLAS_examples_SYCL_Migration/README.md
This change fixes a wrong folder specified in the cuBLAS Migration README. Running `make run_amax` in `02_sycl_dpct_migrated` folder instead of `build` folder previously resulted in a make error.
Fixes Issue# ONSAM-1991
None.
=> Fix wrong folder specified in cuBLAS Migration README

Tools/VTuneProfiler/tachyon/README.md
This change explicitly instructs the user to run `cd linux` in the Tachyon README. Not changing the working directory previously resulted in a make error.
Fixes Issue# ONSAM-1999
None.
=> Update Tachyon build instructions for Linux

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/pca/src/memory_transfers.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/pca/src/pca.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/qrd/src/memory_transfers.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/qrd/src/qrd.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/qri/src/memory_transfers.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/qri/src/qri.hpp
A recent functional change to the compiler means that it will now correctly identify memory dependences. As a side effect, this will now cause for the compiler to emit a message that it is unable to achieve a user specified II for the `MatrixReadPipeToDDR` function in memory_transfers.hpp. 
To regain this performance we can use annotated_ptr's in the SYCL HLS flow to specify a larger interface width which will allow for the compiler to coalesce stores to memory, thus resulting in being able to achieve the user specified II again.
* N/A
Ran all of the tests manually in their reports and simulation flows.
=> FPGA: Update MatrixReadPipeToDDR to use ptr_annotations

DirectProgramming/C++SYCL_FPGA/Tutorials/Tools/use_library/README.md
Minor change in Readme
Device selection not longer hard-coded in .xml or .v file
Fixes Issue# 
=> FPGA: Remove outdated note in use_library README.md

Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/README.md
This change removes mention of Windows support for the Guided Matrix Multiplication Race Condition sample README. Only Linux is supported.
Fixes Issue# ONSAM-1984
None
=> Remove mention of Windows support

DirectProgramming/Fortran/guided_matrix_mul_OpenMP/README.md
This change fixes an error in the Matrix Multiply Sample README. The filename for working sequential version should be `01_mm_CPU_sequential.exe`, not `01_mm_sequential.exe`
Fixes Issue# ONSAM-1982
None
=> Fix Matrix Multiply Sample filename in README

DirectProgramming/C++SYCL/StructuredGrids/iso2dfd_dpcpp/src/iso2dfd.cpp, DirectProgramming/C++SYCL/StructuredGrids/iso3dfd_dpcpp/src/utils.cpp
Fix compilation failures after math builtin API updates 
Fixes Issue#:
(ONSAM-1948)
None
=> Fix compilation failures after math builtin API updates (ONSAM-1948).

DirectProgramming/C++SYCL/CombinationalLogic/sepia-filter/src/sepia_sycl.cpp, DirectProgramming/C++SYCL/SpectralMethods/DiscreteCosineTransform/src/DCT.cpp
Fix for ONSAM 1926.
Fixes Issue#  ONSAM1926
Tested locally with the 2025.0 version of the compiler.
=> Fix onsam 1926

Tools/ApplicationDebugger/jacobi/src/bugged.cpp, Tools/ApplicationDebugger/jacobi/src/fixed.cpp
… sample.
The "get_pointer" function is deprecated so it is replaced with the new function "get_multi_ptr". This function returns multi_ptr with the "const" qualifier for the READ_ONLY accessor.  So, "const" is added to the "compute_x_k1_kernel" function arguments of this type.
Fixes Issue#  https://jira.devtools.intel.com/browse/IGDB-5200
None
Follow steps mentioned here to compile jacobi application. This changes fixes the compilation error seen with latest 2025.0 compiler.
https://github.com/oneapi-src/oneAPI-samples/blob/master/Tool …
=> ApplicationDebugger: Replace get_pointer with get_multi_ptr in jacobi.

Publications/GPU-Opt-Guide/OpenMP/07_loop_bounds/test_loop_bounds_fp.cpp, Publications/GPU-Opt-Guide/OpenMP/07_loop_bounds/test_loop_bounds_map.cpp, Publications/GPU-Opt-Guide/OpenMP/07_loop_bounds/test_loop_bounds_nofp_nomap.cpp, Publications/GPU-Opt-Guide/OpenMP/10_map/test_map_to_or_from.cpp, Publications/GPU-Opt-Guide/OpenMP/10_map/test_map_tofrom.cpp
This change fixes bug in loop_bounds and map examples for access to index of array which is out of bounds.
Fixes Issue:  ONSAM-2016
None
Local validation of impacted tests with printf's added to verify oob accesses were resolved.
=> fix out-of-bounds bug in loop_bounds and map examples

Libraries/oneMKL/matrix_mul_mkl/matrix_mul_mkl.cpp, Libraries/oneMKL/matrix_mul_mkl/utilities.hpp
Adds basic verification to oneMKL sample `matrix_mul_mkl.cpp`. A step is added where we multiply two matrices of all ones and check the resulting values.
No external dependencies were added.
Tested locally on linux.
=> Add basic verification to oneMKL matmul sample

Libraries/oneMKL/matrix_mul_mkl/matrix_mul_mkl.cpp
Update #2512 by adding an exit if verification fails.
No external dependencies.
Tested locally on linux.
=> Add exit if MKL matrix mul sample fails verification

Libraries/oneMKL/computed_tomography/computed_tomography.cpp, Libraries/oneMKL/fourier_correlation/README.md, Libraries/oneMKL/fourier_correlation/fcorr_1d_buffers.cpp, Libraries/oneMKL/fourier_correlation/fcorr_1d_usm.cpp, Libraries/oneMKL/fourier_correlation/fcorr_2d_usm.cpp, Libraries/oneMKL/fourier_correlation/sample.json
This pull request
- updates `Libraries/oneMKL/computed_tomography/computed_tomography.cpp` according to the recommended usage for oneMKL DFT APIs, starting from oneMKL-2025.0;
- modifies the content of `Libraries/oneMKL/fourier_correlation`
- updating it to the recommended usage for oneMKL DFT SYCL APIs, starting from oneMKL-2025.0;
- revising, _correcting_ and generalizing the operations at play therein. The `README` file was updated accordingly and captures the essence of the changes suggested herein in more details.
No new dependency is introduced,
The samples were executed (as documented), on an Intel(R) Data Center GPU Max 1550 GPU machine. The typical output was updated in the `README` for the "Fourier correlation" samples.
=> Updates and revisions to the oneAPI samples involving oneMKL DFT domain

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/svd/src/svd.hpp
This PR fixes a typo that was introduced in a previous PR that was to address some compilation crashes. This typo was leading to functional incorrectness (i.e., failures).
* N/A
* Manually ran this through full-system and SYCL-HLS flows in Emulation and in Simulation.
=> FPGA: Fix typo in SVD code sample

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/svd/src/memory_transfers.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/svd/src/svd.hpp
There was a functional change that went into the compiler recently that means it will now correctly identify memory dependences. One of the results of this is that this design will now emit a message that it is unable to achieve a user specified II. 
To regain this performance we can use annotated_ptr's in the SYCL HLS flow to specify a larger interface width which will allow for the compiler to coalesce stores to memory, thus resulting in being able to achieve the user specified II again.
This change also corrects the address space of a call to `device_ptr`
* N/A
* Manually ran the full-system and IPA flows through …
=> FPGA: Fix II error and update namespace for device_ptr

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/svd/src/memory_transfers.hpp, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/svd/src/svd.hpp, Publications/GPU-Opt-Guide/OpenMP/22_mkl_dispatch/CMakeLists.txt, Publications/GPU-Opt-Guide/sub-group/sg-max-size.cpp, Publications/GPU-Opt-Guide/sub-group/sub-group-0.cpp, Publications/GPU-Opt-Guide/sub-group/sub-group-1.cpp, Publications/GPU-Opt-Guide/sub-group/sub-group-2.cpp, Publications/GPU-Opt-Guide/sub-group/sub-group-3.cpp, Publications/GPU-Opt-Guide/sub-group/sub-group-4.cpp, Publications/GPU-Opt-Guide/sub-group/sub-group-5.cpp, Publications/GPU-Opt-Guide/sub-group/sub-group-6.cpp, Publications/GPU-Opt-Guide/sub-group/sub-group-7.cpp, Publications/GPU-Opt-Guide/sub-group/sub-group-8.cpp, Publications/GPU-Opt-Guide/sub-group/sub-group-sizes.cpp, Publications/GPU-Opt-Guide/sub-group/transpose.cpp, Publications/GPU-Opt-Guide/usm/usm-buffer.cpp, Publications/GPU-Opt-Guide/work-group-size/reduction-wg-size.cpp, Publications/GPU-Opt-Guide/work-group-size/vec-copy.cpp, README.md
Some features are deprecated in 2025.0 release and the deprecation causes build errors and warning in the GoG samples.
Fixes Issue# 
GoG samples build errors and warnings
None
=> Fix 2025.0 build errors and warnings

Libraries/oneCCL/tutorials/oneCCL_Getting_Started.ipynb
This change updates the path to copy oneCCL source code and removes mention of DevCloud and qsub.
Fixes Issue# ONSAM-1998 and ONSAM-2044
None.
=> Update oneCCL Getting Started Jupyter Notebook

DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/CMakeLists.txt, DirectProgramming/C++SYCL_FPGA/ReferenceDesigns/gzip/src/gzipkernel_ll.cpp
The sample was relying on undocumented compiler flags.
This change updated the sample to instead use the documented LSU builtins to achieve the same goal.
=> FPGA: Update the `gzip` code sample to use LSU builtins

AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpnp_kNN/IntelPython_Numpy_Numba_dpnp_kNN.ipynb, AI-and-Analytics/Features-and-Functionality/IntelPython_Numpy_Numba_dpnp_kNN/IntelPython_Numpy_Numba_dpnp_kNN.py
**#** Existing Sample Changes
Move kNN numba-dpex code sample to dpnp. Update script and jupyter notebook to reflect the change.
=> Updated numba kNN script

Libraries/oneMKL/monte_carlo_european_opt/makefile
Corrected the flag for the OpenCL library on Windows since it leads to the warning: `unknown argument ignored in clang-cl: -lOpenCL [-Wunknown-argument]`.
=> [oneMKL] Corrected the flag for the OpenCL library on Windows

Tools/GPU-Occupancy-Calculator/index.html
updated LNL and BMG device details to GPU Occupancy Calculator
=> updated LNL and BMG device details to GPU Occupancy Calculator

DirectProgramming/C++SYCL_FPGA/include/streaming_cholesky_inversion.hpp
This change forces the main compute loop of the Cholesky matrix inversion IP to have an II of 1.
=> FPGA: Force II=1 in Cholesky inversion IP

Libraries/oneMKL/binomial/src/binomial_sycl.cpp, Libraries/oneMKL/black_scholes/src/black_scholes_sycl.cpp
namespace for `reqd_sub_group_size` has been changed from `intel::` to `sycl::`
=> [oneMKL] Replaced namespace for reqd_sub_group_size

Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/README.md, Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/src/a1_matrix_mul_zero_buff.cpp, Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/src/a2_matrix_mul.cpp, Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/src/b1_matrix_mul_null_usm.cpp, Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/src/b2_matrix_mul_usm.cpp
Fixes Issue# ONSAM-1870, ONSAM-2056
=> Updates to BadBuffers tutorial for 2025.0 and 2502.18 rolling release

DirectProgramming/C++/ParallelPatterns/openmp_reduction/README.md
=> update formula in readme fix #2136

DirectProgramming/C++SYCL/ParallelPatterns/histogram/src/main.cpp
fix #2292
When there is exception, will show something like:
`Native API failed. Native API returns: -45 (PI_ERROR_INVALID_PROGRAM_EXECUTABLE)`
=> add exception code to histogram sample

AI-and-Analytics/End-to-end-Workloads/JobRecommendationSystem/requirements.txt, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_AMX_BF16_Inference/requirements.txt, AI-and-Analytics/Features-and-Functionality/IntelTensorFlow_Enabling_Auto_Mixed_Precision_for_TransferLearning/requirements.txt, AI-and-Analytics/Features-and-Functionality/IntelTransformers_Quantization/requirements.txt, AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/requirements.txt, AI-and-Analytics/Getting-Started-Samples/Intel_Extension_For_TensorFlow_GettingStarted/requirements.txt
Pip normalizes all package names which shouldn't have any errors when installing packages e.g., tensorflow_hub and tensorflow-hub is treated as the same and will install tensorflow-hub, however if users install using 'conda install' it will encounter module not found errors as conda does not normalize module package names. This change is also to standardize those module names to be the same as the names in package repositories.
Not related to any issue tickets.
No additional external dependencies.
=> Standardize module naming in requirements.txt files

Libraries/oneDNN/tutorials/profiling/profile_utils.py
fix ONSAM-2061
after apply this PR, can handle following logs
```
onednn_verbose,info,oneDNN v3.3.0 (commit 08fea71aff4c273e34579e86396405f95d34aa74)
onednn_verbose,info,cpu,runtime:OpenMP,nthr:24
onednn_verbose,info,cpu,isa:Intel AVX2 with Intel DL Boost
onednn_verbose,info,gpu,runtime:none
onednn_verbose,info,graph,backend,0:compiler_backend
onednn_verbose,info,graph,backend,1:dnnl_backend
onednn_verbose,primitive,info,template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,graph,info,template:operation,engine,partition_id,partition_kind,op_names,data_formats,logical_tensors,fpmath_mode,backend,exec_time
onednn_verbose,primitive,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:cdba::f0 …
```
=> fix for ipex extension ONSAM-2061

Tools/GPU-Occupancy-Calculator/index.html
fixed BMG EU counts in GPU Occupancy Calculator
=> fixed BMG EU counts

Tools/GPU-Occupancy-Calculator/index.html
fixed MTL configs in GPU occupancy calculator, from max WG per Xe-core from 64 to 128
=> fixed MTL configs

Tools/GPU-Occupancy-Calculator/index.html
fixed MTL configs in GPU occupancy calculator, from max WG per Xe-core from 64 to 128
=> fixed MTL configs in GPU occupancy calculator

AI-and-Analytics/Getting-Started-Samples/README.md
The sample link for the “ONNX Runtime” sample is not present in the Getting Started samples README
Fixes Issue# ONSAM-2071
Signed-off-by: Ooi Boon Sin [boon.sin.ooi@intel.com](mailto:boon.sin.ooi@intel.com)
Signed-off-by: Frankie Wei Quan Ong [frankie.wei.quan.ong@intel.com](mailto:frankie.wei.quan.ong@intel.com)
None
=> [ONSAM-2071] Fix ONNX Runtime sample link not present in Getting Started samples README

AI-and-Analytics/Getting-Started-Samples/INC-Quantization-Sample-for-PyTorch/README.MD
In README, a step on registering Conda kernel with Jupyter kernel is missing for AI Tools Offline Installer (Validated) and Conda/PIP. This PR adds the step and the command with descriptions.
Fixes Issue# ONSAM-2066
Co-authored-by: Ooi Boon Sin <boon.sin.ooi@intel.com>
Signed-off-by: Frankie Wei Quan Ong <frankie.wei.quan.ong@intel.com>
Signed-off-by: Ooi Boon Sin <boon.sin.ooi@intel.com>
None
=> [ONSAM-2066] Update README with adding command to register Conda kernel with Jupyter kernel

Libraries/oneMKL/computed_tomography/GNUmakefile, Libraries/oneMKL/computed_tomography/README.md, Libraries/oneMKL/computed_tomography/computed_tomography.cpp, Libraries/oneMKL/computed_tomography/makefile
This PR revises the "computed tomography" oneAPI sample.
The sample itself was revised so that the application creates reconstructed signal/image samples that are real (no longer complex) and so that those generated real values are directly comparable to the input image's (gray-scale-converted) values themselves. These changes are motivated by the desire to introduce a legitimate functional validation step (introduced herein as well), but that need triggered more thorough revision(s) of the sample's source code.
Extensive explanatory comments were added to the source code, explaining the mathematical nature of the operations at play and/or the technical details related to the suggested implementation.
This was extensively tested on a PVC GPU (512 EUs) and a SPR CPU using a machine …
=> [oneMKL samples][computed tomography] Revisions, refactoring and addition of a functional verification

Tools/ApplicationDebugger/guided_matrix_mult_Exceptions/README.md, Tools/ApplicationDebugger/guided_matrix_mult_RaceCondition/README.md, Tools/ApplicationDebugger/guided_matrix_mult_SLMSize/README.md
Behavior/output changed between 2025.0 and 2025.1, so updated for the changes in the documentation
Fixes Issue#  none
Behavior depends on specific oneAPI (2025.1) and driver versions (Rolling Stable 2507.12) to attain desired behavior.
- Command Line
- Followed tutorial directions line-by-line, updating any observed changes in behavior, and otherwise verifying correct operation
=> Updates for oneAPI 2025.1

Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/README.md, Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/src/a1_matrix_mul_zero_buff.cpp, Tools/ApplicationDebugger/guided_matrix_mult_BadBuffers/src/a2_matrix_mul.cpp
Behavior/output changed between 2025.0 and 2025.1, so updated for the changes.   I also changed to a new debugging approach that does not rely on segfault functionality in the GPU driver (doesn't rely on GPU debugging at all), and re-ordered two operations to make it easier to demonstrate correct vs. incorrect configurations
Fixes Issue#  <none>
Behavior depends on specific oneAPI (2025.1) and driver versions (Rolling Stable 2507.12) to attain desired behavior.
- Command Line
- Followed tutorial directions line-by-line, updating any observed changes in behavior and fixing build issues as I went, and otherwise verifying correct operation
=> Updates for oneAPI 2025.1 and client GPU debugging
